project_id = "lpmtmxzlgbenmsnodalw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.ai-source-generator]
verify_jwt = false

[functions.gemini-source-agent]
verify_jwt = false