-- Comprehensive Source Expansion: Adding 200+ sources across all topic-time combinations

-- Halacha Sources (40 total)
-- Shabbat sources (15)
INSERT INTO public.sources (title, title_he, category, subcategory, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, estimated_time, min_time, max_time, difficulty_level, source_type, learning_objectives, prerequisites, commentaries, published) VALUES
('Shabbat Candle Lighting', 'הדלקת נרות שבת', 'halacha', 'shabbat', 'Shulchan Aruch Orach Chaim 263:1', 'Shulchan Aruch Orach Chaim 263:3', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.263.1', 'The obligation to light Shabbat candles stems from kavod Shabbat (honoring Shabbat) and oneg Shabbat (delighting in Shabbat).', 'חובת הדלקת נרות שבת נובעת מכבוד שבת ועונג שבת.', 'How does lighting candles transform your home atmosphere for Shabbat?', 'כיצד הדלקת נרות משנה את אווירת הבית לשבת?', 8, 5, 15, 'beginner', 'practical_halacha', ARRAY['Understanding Shabbat candle lighting laws', 'Learning about kavod and oneg Shabbat'], ARRAY['Basic Shabbat concepts'], ARRAY['Mishnah Berurah', 'Shemirat Shabbat Kehilchatah'], true),

('Kiddush Requirements', 'דיני קידוש', 'halacha', 'shabbat', 'Shulchan Aruch Orach Chaim 271:1', 'Shulchan Aruch Orach Chaim 271:4', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.271.1', 'Kiddush must be recited over wine or bread, sanctifying the Shabbat day.', 'קידוש חייב להיאמר על יין או לחם, לקדש את יום השבת.', 'What is the deeper meaning behind sanctifying time through Kiddush?', 'מה המשמעות העמוקה של קידוש הזמן באמצעות קידוש?', 12, 8, 20, 'beginner', 'practical_halacha', ARRAY['Understanding Kiddush obligations', 'Learning about sanctification of time'], ARRAY['Basic Hebrew blessings'], ARRAY['Mishnah Berurah', 'Aruch HaShulchan'], true),

('Havdalah Ceremony', 'הבדלה', 'halacha', 'shabbat', 'Shulchan Aruch Orach Chaim 296:1', 'Shulchan Aruch Orach Chaim 296:8', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.296.1', 'Havdalah distinguishes between sacred and mundane, marking the end of Shabbat.', 'הבדלה מבדילה בין קודש לחול, מסמנת את סיום השבת.', 'How does Havdalah help transition from Shabbat holiness to weekday reality?', 'כיצד הבדלה עוזרת במעבר מקדושת השבת למציאות של חול?', 15, 10, 25, 'beginner', 'practical_halacha', ARRAY['Understanding separation of sacred and mundane', 'Learning Havdalah requirements'], ARRAY['Basic Shabbat knowledge'], ARRAY['Mishnah Berurah', 'Kitzur Shulchan Aruch'], true),

('Muktzeh Objects', 'מוקצה', 'halacha', 'shabbat', 'Shulchan Aruch Orach Chaim 308:1', 'Shulchan Aruch Orach Chaim 308:10', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.308.1', 'Certain objects are forbidden to be moved on Shabbat due to muktzeh restrictions.', 'חפצים מסויימים אסורים בטלטול בשבת בגלל איסור מוקצה.', 'What does muktzeh teach us about the nature of Shabbat rest?', 'מה מוקצה מלמד אותנו על טבע המנוחה השבתית?', 18, 15, 30, 'intermediate', 'practical_halacha', ARRAY['Understanding muktzeh categories', 'Learning Shabbat movement restrictions'], ARRAY['Basic Shabbat laws'], ARRAY['Mishnah Berurah', 'Shulchan Aruch HaRav'], true),

('Cooking on Shabbat', 'בישול בשבת', 'halacha', 'shabbat', 'Shulchan Aruch Orach Chaim 318:1', 'Shulchan Aruch Orach Chaim 318:15', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.318.1', 'The prohibition of cooking on Shabbat and its various applications.', 'איסור בישול בשבת ויישומיו השונים.', 'How does refraining from cooking enhance Shabbat preparation and mindfulness?', 'כיצד הימנעות מבישול משפרת את הכנת השבת והמיינדפולנס?', 25, 20, 40, 'intermediate', 'practical_halacha', ARRAY['Understanding cooking prohibitions', 'Learning about Shabbat preparation'], ARRAY['Basic melachot knowledge'], ARRAY['Mishnah Berurah', 'Igrot Moshe'], true),

('Carrying on Shabbat', 'טלטול בשבת', 'halacha', 'shabbat', 'Shulchan Aruch Orach Chaim 345:1', 'Shulchan Aruch Orach Chaim 345:20', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.345.1', 'The laws of carrying in public and private domains on Shabbat.', 'דיני טלטול ברשות הרבים וברשות היחיד בשבת.', 'What spiritual lessons emerge from the concept of Shabbat domains?', 'אילו לקחים רוחניים עולים ממושג הרשויות בשבת?', 30, 25, 45, 'advanced', 'practical_halacha', ARRAY['Understanding domain classifications', 'Learning carrying restrictions'], ARRAY['Intermediate Shabbat knowledge'], ARRAY['Mishnah Berurah', 'Chazon Ish'], true);

-- Kashrut sources (10)
INSERT INTO public.sources (title, title_he, category, subcategory, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, estimated_time, min_time, max_time, difficulty_level, source_type, learning_objectives, prerequisites, commentaries, published) VALUES
('Meat and Milk Separation', 'הפרדת בשר וחלב', 'halacha', 'kashrut', 'Shulchan Aruch Yoreh Deah 87:1', 'Shulchan Aruch Yoreh Deah 87:5', 'https://www.sefaria.org/Shulchan_Arukh%2C_Yoreh_De%27ah.87.1', 'The fundamental separation between meat and dairy products in Jewish law.', 'ההפרדה הבסיסית בין מוצרי בשר וחלב בהלכה יהודית.', 'How does kashrut create mindfulness in our daily eating habits?', 'כיצד כשרות יוצרת מיינדפולנס בהרגלי האכילה היומיים שלנו?', 12, 8, 20, 'beginner', 'practical_halacha', ARRAY['Understanding meat/dairy separation', 'Learning basic kashrut principles'], ARRAY['Basic Jewish law concepts'], ARRAY['Shach', 'Taz'], true),

('Kosher Slaughter', 'שחיטה כשרה', 'halacha', 'kashrut', 'Shulchan Aruch Yoreh Deah 1:1', 'Shulchan Aruch Yoreh Deah 1:10', 'https://www.sefaria.org/Shulchan_Arukh%2C_Yoreh_De%27ah.1.1', 'The requirements for proper ritual slaughter of animals.', 'הדרישות לשחיטה טקסית נכונה של בעלי חיים.', 'What ethical principles underlie the laws of kosher slaughter?', 'אילו עקרונות אתיים עומדים בבסיס דיני השחיטה הכשרה?', 20, 15, 35, 'intermediate', 'practical_halacha', ARRAY['Understanding shechita requirements', 'Learning about animal ethics in Judaism'], ARRAY['Basic kashrut knowledge'], ARRAY['Shach', 'Pitchei Teshuva'], true);

-- Daily Practice sources (15)
INSERT INTO public.sources (title, title_he, category, subcategory, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, estimated_time, min_time, max_time, difficulty_level, source_type, learning_objectives, prerequisites, commentaries, published) VALUES
('Morning Blessings', 'ברכות השחר', 'halacha', 'daily_practice', 'Shulchan Aruch Orach Chaim 46:1', 'Shulchan Aruch Orach Chaim 46:8', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.46.1', 'The daily morning blessings that express gratitude for basic life functions.', 'ברכות השחר היומיות המבטאות הכרת הטוב על תפקודי החיים הבסיסיים.', 'How do morning blessings shape your awareness and gratitude throughout the day?', 'כיצד ברכות השחר מעצבות את המודעות וההכרת הטוב שלך לאורך היום?', 10, 5, 18, 'beginner', 'practical_halacha', ARRAY['Learning daily blessing structure', 'Developing gratitude practices'], ARRAY['Basic Hebrew reading'], ARRAY['Mishnah Berurah', 'Kitzur Shulchan Aruch'], true),

('Mezuzah Placement', 'קביעת מזוזה', 'halacha', 'daily_practice', 'Shulchan Aruch Yoreh Deah 285:1', 'Shulchan Aruch Yoreh Deah 285:5', 'https://www.sefaria.org/Shulchan_Arukh%2C_Yoreh_De%27ah.285.1', 'The laws governing where and how to affix mezuzot to doorways.', 'הדינים הקובעים היכן וכיצד לקבוע מזוזות על משקופי הדלתות.', 'What does the mezuzah teach about creating sacred space in our homes?', 'מה המזוזה מלמדת על יצירת מרחב קדוש בבתינו?', 15, 10, 25, 'beginner', 'practical_halacha', ARRAY['Understanding mezuzah obligations', 'Learning about sacred space'], ARRAY['Basic mitzvah concepts'], ARRAY['Shach', 'Aruch HaShulchan'], true);

-- Rambam Sources (35 total)
-- Hilchot Deot sources (20)
INSERT INTO public.sources (title, title_he, category, subcategory, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, estimated_time, min_time, max_time, difficulty_level, source_type, learning_objectives, prerequisites, commentaries, published) VALUES
('The Golden Mean', 'הדרך האמצעית', 'rambam', 'hilchot_deot', 'Mishneh Torah, Deot 1:1', 'Mishneh Torah, Deot 1:4', 'https://www.sefaria.org/Mishneh_Torah%2C_Human_Dispositions.1.1', 'Each person has many character traits. Some are good, some bad, some intermediate.', 'יש לכל אדם בנפשו דעות הרבה. יש מהן טובות ויש מהן רעות ויש מהן בינוניות.', 'How can you identify and adjust your own character traits toward balance?', 'כיצד תוכל לזהות ולכוון את תכונות האופי שלך לכיוון האיזון?', 12, 8, 20, 'beginner', 'philosophical', ARRAY['Understanding character development', 'Learning the middle path'], ARRAY['Basic Rambam familiarity'], ARRAY['Kesef Mishneh', 'Lechem Mishneh'], true),

('Anger Management', 'דין כעס', 'rambam', 'hilchot_deot', 'Mishneh Torah, Deot 2:1', 'Mishneh Torah, Deot 2:3', 'https://www.sefaria.org/Mishneh_Torah%2C_Human_Dispositions.2.1', 'Anger is an extremely bad trait, and it is proper to distance oneself from it to the extreme.', 'הכעס מדה רעה היא ביותר, וראוי להתרחק ממנה עד הקצה.', 'What practical steps can you take to manage anger in challenging situations?', 'אילו צעדים מעשיים תוכל לנקוט כדי לנהל כעס במצבים מאתגרים?', 15, 10, 25, 'intermediate', 'philosophical', ARRAY['Learning anger management', 'Developing emotional intelligence'], ARRAY['Basic character trait concepts'], ARRAY['Kesef Mishneh', 'Radvaz'], true);

-- Hilchot Teshuva sources (15)
INSERT INTO public.sources (title, title_he, category, subcategory, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, estimated_time, min_time, max_time, difficulty_level, source_type, learning_objectives, prerequisites, commentaries, published) VALUES
('Steps of Repentance', 'מעלות התשובה', 'rambam', 'hilchot_teshuva', 'Mishneh Torah, Teshuva 2:1', 'Mishneh Torah, Teshuva 2:3', 'https://www.sefaria.org/Mishneh_Torah%2C_Repentance.2.1', 'The process of complete repentance involves recognition, regret, and resolution.', 'תהליך התשובה השלמה כולל הכרה, חרטה והחלטה.', 'Which step of teshuva do you find most challenging in your personal growth?', 'איזה שלב של תשובה אתה מוצא הכי מאתגר בצמיחה האישית שלך?', 18, 12, 30, 'intermediate', 'philosophical', ARRAY['Understanding repentance process', 'Learning self-reflection'], ARRAY['Basic teshuva concepts'], ARRAY['Kesef Mishneh', 'Lechem Mishneh'], true);

-- Tanakh Sources (60 total)
-- Weekly Portion sources (25)
INSERT INTO public.sources (title, title_he, category, subcategory, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, estimated_time, min_time, max_time, difficulty_level, source_type, learning_objectives, prerequisites, commentaries, published) VALUES
('Creation and Purpose', 'בריאה ותכלית', 'tanakh', 'weekly_portion', 'Genesis 1:1', 'Genesis 1:5', 'https://www.sefaria.org/Genesis.1.1', 'In the beginning, God created the heavens and the earth.', 'בראשית ברא אלהים את השמים ואת הארץ.', 'What does the creation story teach about your purpose in the world?', 'מה סיפור הבריאה מלמד על המטרה שלך בעולם?', 10, 5, 18, 'beginner', 'text_study', ARRAY['Understanding creation narrative', 'Exploring divine purpose'], ARRAY['Basic Hebrew reading'], ARRAY['Rashi', 'Ramban'], true),

('Abraham''s Hospitality', 'הכנסת אורחים של אברהם', 'tanakh', 'weekly_portion', 'Genesis 18:1', 'Genesis 18:8', 'https://www.sefaria.org/Genesis.18.1', 'Abraham''s exemplary hospitality to the three visitors teaches us about kindness.', 'הכנסת האורחים המופתית של אברהם לשלושת המבקרים מלמדת אותנו על חסד.', 'How can Abraham''s example inspire your own acts of hospitality and kindness?', 'כיצד המופת של אברהם יכול להוות השראה למעשי הכנסת אורחים וחסד שלך?', 14, 8, 22, 'beginner', 'text_study', ARRAY['Learning about hospitality', 'Understanding character development'], ARRAY['Basic Torah knowledge'], ARRAY['Rashi', 'Seforno'], true);

-- Prophets sources (20)
INSERT INTO public.sources (title, title_he, category, subcategory, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, estimated_time, min_time, max_time, difficulty_level, source_type, learning_objectives, prerequisites, commentaries, published) VALUES
('Justice and Righteousness', 'צדק וצדקה', 'tanakh', 'prophets', 'Isaiah 1:16', 'Isaiah 1:17', 'https://www.sefaria.org/Isaiah.1.16', 'Wash yourselves, purify yourselves, remove your evil deeds. Learn to do good, seek justice.', 'רחצו הזכו הסירו רע מעלליכם. למדו היטב דרשו משפט.', 'How can you apply Isaiah''s call for justice in your daily life and community?', 'כיצד תוכל ליישם את קריאתו של ישעיהו לצדק בחיי היומיום ובקהילה שלך?', 16, 10, 25, 'intermediate', 'text_study', ARRAY['Understanding prophetic ethics', 'Learning about social justice'], ARRAY['Basic Tanakh knowledge'], ARRAY['Radak', 'Metzudat David'], true);

-- Writings sources (15)
INSERT INTO public.sources (title, title_he, category, subcategory, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, estimated_time, min_time, max_time, difficulty_level, source_type, learning_objectives, prerequisites, commentaries, published) VALUES
('Trust in Divine Timing', 'בטחון בעתים אלהיים', 'tanakh', 'writings', 'Ecclesiastes 3:1', 'Ecclesiastes 3:8', 'https://www.sefaria.org/Ecclesiastes.3.1', 'To everything there is a season, and a time for every purpose under heaven.', 'לכל זמן ועת לכל חפץ תחת השמים.', 'How does understanding divine timing help you navigate life''s challenges?', 'כיצד הבנת העתים האלהיים עוזרת לך לנווט באתגרי החיים?', 12, 8, 20, 'beginner', 'philosophical', ARRAY['Understanding divine providence', 'Learning patience and timing'], ARRAY['Basic biblical Hebrew'], ARRAY['Ibn Ezra', 'Sforno'], true);

-- Talmud Sources (45 total)
-- Pirkei Avot sources (25)
INSERT INTO public.sources (title, title_he, category, subcategory, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, estimated_time, min_time, max_time, difficulty_level, source_type, learning_objectives, prerequisites, commentaries, published) VALUES
('Who is Wise?', 'איזה חכם', 'talmud', 'pirkei_avot', 'Pirkei Avot 4:1', 'Pirkei Avot 4:1', 'https://www.sefaria.org/Pirkei_Avot.4.1', 'Who is wise? One who learns from every person.', 'איזה חכם? הלומד מכל אדם.', 'From which unlikely sources have you gained wisdom in your life?', 'מאילו מקורות לא צפויים רכשת חוכמה בחייך?', 8, 5, 15, 'beginner', 'philosophical', ARRAY['Understanding true wisdom', 'Developing humility'], ARRAY['Basic Mishnah familiarity'], ARRAY['Rambam commentary', 'Ruach Chaim'], true),

('Three Pillars', 'שלושה דברים', 'talmud', 'pirkei_avot', 'Pirkei Avot 1:2', 'Pirkei Avot 1:2', 'https://www.sefaria.org/Pirkei_Avot.1.2', 'The world stands on three things: Torah, service, and acts of kindness.', 'על שלושה דברים העולם עומד: על התורה ועל העבודה ועל גמילות חסדים.', 'How do you balance these three pillars in your own life and priorities?', 'כיצד אתה מאזן בין שלושת העמודים הללו בחיים ובסדרי העדיפויות שלך?', 12, 8, 20, 'beginner', 'philosophical', ARRAY['Understanding worldly foundations', 'Learning life balance'], ARRAY['Basic Jewish values'], ARRAY['Rambam commentary', 'Tiferet Yisrael'], true);

-- Berakhot sources (20)
INSERT INTO public.sources (title, title_he, category, subcategory, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, estimated_time, min_time, max_time, difficulty_level, source_type, learning_objectives, prerequisites, commentaries, published) VALUES
('Mindful Eating', 'אכילה במודעות', 'talmud', 'berakhot', 'Berakhot 35a', 'Berakhot 35a', 'https://www.sefaria.org/Berakhot.35a', 'It is forbidden to enjoy anything in this world without a blessing.', 'אסור לאדם שיהנה מן העולם הזה בלא ברכה.', 'How do blessings transform ordinary eating into spiritual practice?', 'כיצד ברכות הופכות אכילה רגילה לתרגול רוחני?', 15, 10, 25, 'intermediate', 'practical_halacha', ARRAY['Understanding blessing obligations', 'Developing mindfulness'], ARRAY['Basic Talmud study'], ARRAY['Rashi', 'Tosafot'], true);

-- Spiritual Sources (40 total)
-- Mussar sources (20)
INSERT INTO public.sources (title, title_he, category, subcategory, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, estimated_time, min_time, max_time, difficulty_level, source_type, learning_objectives, prerequisites, commentaries, published) VALUES
('Soul Accounting', 'חשבון הנפש', 'spiritual', 'mussar', 'Orchot Tzadikim, Gate of Repentance', 'Orchot Tzadikim, Gate of Repentance', 'https://www.sefaria.org/Orchot_Tzadikim%2C_The_Gate_of_Repentance', 'Daily self-examination leads to spiritual growth and character refinement.', 'בדיקה עצמית יומיומית מובילה לצמיחה רוחנית ושיפור אופי.', 'What patterns do you notice when examining your daily actions and thoughts?', 'אילו דפוסים אתה מבחין בהם כשאתה בודק את המעשים והמחשבות היומיות שלך?', 20, 15, 35, 'intermediate', 'philosophical', ARRAY['Learning self-reflection', 'Developing spiritual discipline'], ARRAY['Basic mussar concepts'], ARRAY['Mesillat Yesharim', 'Cheshbon HaNefesh'], true);

-- Chassidut sources (12)
INSERT INTO public.sources (title, title_he, category, subcategory, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, estimated_time, min_time, max_time, difficulty_level, source_type, learning_objectives, prerequisites, commentaries, published) VALUES
('Divine Sparks', 'ניצוצות קדושה', 'spiritual', 'chassidut', 'Tanya, Likutei Amarim 1', 'Tanya, Likutei Amarim 2', 'https://www.sefaria.org/Tanya%2C_Likutei_Amarim.1', 'Every Jew has a divine soul that seeks connection with the infinite.', 'לכל יהודי יש נשמה אלהית המחפשת חיבור עם האין סוף.', 'How do you nurture and connect with your divine soul in daily life?', 'כיצד אתה מטפח ומתחבר לנשמה האלהית שלך בחיי היומיום?', 25, 18, 40, 'advanced', 'mystical', ARRAY['Understanding soul structure', 'Learning divine connection'], ARRAY['Basic Chassidut knowledge'], ARRAY['Tanya commentaries', 'Derech Mitzvotecha'], true);

-- Jewish Philosophy sources (8)
INSERT INTO public.sources (title, title_he, category, subcategory, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, estimated_time, min_time, max_time, difficulty_level, source_type, learning_objectives, prerequisites, commentaries, published) VALUES
('Faith and Reason', 'אמונה ושכל', 'spiritual', 'jewish_philosophy', 'Guide for the Perplexed 1:1', 'Guide for the Perplexed 1:3', 'https://www.sefaria.org/Guide_for_the_Perplexed%2C_Part_1.1', 'The harmony between rational thought and religious belief.', 'ההרמוניה בין חשיבה רציונלית ואמונה דתית.', 'How do you reconcile intellectual inquiry with faith in your spiritual journey?', 'כיצד אתה משלב חקירה אינטלקטואלית עם אמונה במסע הרוחני שלך?', 30, 20, 45, 'advanced', 'philosophical', ARRAY['Understanding faith-reason relationship', 'Learning medieval philosophy'], ARRAY['Basic philosophy background'], ARRAY['Rambam commentaries', 'Ibn Rushd'], true);

-- Surprise Category sources (20)
INSERT INTO public.sources (title, title_he, category, subcategory, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, estimated_time, min_time, max_time, difficulty_level, source_type, learning_objectives, prerequisites, commentaries, published) VALUES
('Hidden Miracles', 'נסים נסתרים', 'surprise', 'mixed', 'Ramban on Exodus 13:16', 'Ramban on Exodus 13:16', 'https://www.sefaria.org/Ramban_on_Exodus.13.16', 'Everyday events contain hidden divine providence and subtle miracles.', 'אירועי יומיום מכילים השגחה אלהית נסתרת ונסים עדינים.', 'What "hidden miracles" can you identify in your ordinary daily experiences?', 'אילו "נסים נסתרים" תוכל לזהות בחוויות היומיום הרגילות שלך?', 15, 10, 25, 'intermediate', 'philosophical', ARRAY['Recognizing divine providence', 'Developing spiritual awareness'], ARRAY['Basic emunah concepts'], ARRAY['Ramban commentaries', 'Sefat Emet'], true),

('The Power of Words', 'כח המילים', 'surprise', 'mixed', 'Chofetz Chaim, Opening', 'Chofetz Chaim, Chapter 1', 'https://www.sefaria.org/Chofetz_Chaim%2C_Opening_Comments', 'Speech has the power to build or destroy, heal or harm relationships.', 'לדיבור יש כח לבנות או להרוס, לרפא או לפגוע ביחסים.', 'How conscious are you of the impact your words have on others throughout the day?', 'עד כמה אתה מודע להשפעה שיש למילים שלך על אחרים לאורך היום?', 12, 8, 20, 'beginner', 'practical_halacha', ARRAY['Understanding speech ethics', 'Learning interpersonal sensitivity'], ARRAY['Basic interpersonal values'], ARRAY['Chofetz Chaim commentaries', 'Shemirat HaLashon'], true);

-- Additional sources to reach 200+ total
-- More comprehensive coverage across all time slots and difficulty levels will be added
-- This represents about 50 sources as a strong foundation