-- Continue Phase 1: Adding Shabbat, Kashrut, Prayer sources + Rambam sources + Tanakh sources

-- Shabbat (8 sources)
INSERT INTO sources (title, title_he, category, subcategory, estimated_time, min_time, max_time, difficulty_level, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, commentaries, learning_objectives, published) VALUES
('Shabbat Candle Lighting', 'הדלקת נרות שבת', 'halacha', 'shabbat', 12, 8, 18, 'beginner', 'Orach Chaim 263:1', 'Orach Chaim 263:5', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.263.1', 'Laws and customs of lighting Shabbat candles', 'הלכות ומנהגי הדלקת נרות שבת', 'How does lighting Shabbat candles transform your home and mindset for Shabbat?', 'כיצד הדלקת נרות שבת משנה את הבית והמחשבה לקראת שבת?', ARRAY['Mishnah Berurah', 'Aruch HaShulchan', 'Kaf HaChaim'], ARRAY['Shabbat preparation', 'Home sanctification'], true),
('Kiddush Requirements', 'דיני קידוש', 'halacha', 'shabbat', 18, 15, 25, 'intermediate', 'Orach Chaim 271:1', 'Orach Chaim 271:10', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.271.1', 'Complete laws governing Kiddush on Shabbat', 'הלכות מלאות של קידוש בשבת', 'What does the act of Kiddush teach us about sanctifying time?', 'מה מלמד אותנו מעשה הקידוש על קידוש הזמן?', ARRAY['Mishnah Berurah', 'Aruch HaShulchan', 'Kaf HaChaim'], ARRAY['Kiddush mastery', 'Time sanctification concepts'], true),
('Carrying on Shabbat', 'איסור טלטול בשבת', 'halacha', 'shabbat', 25, 20, 30, 'advanced', 'Orach Chaim 308:1', 'Orach Chaim 308:20', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.308.1', 'Laws of carrying and moving objects on Shabbat', 'הלכות טלטול והעברת חפצים בשבת', 'How do carrying restrictions on Shabbat help create a different relationship with physical objects?', 'כיצד הגבלות הטלטול בשבת עוזרות ליצור יחס שונה לחפצים הפיזיים?', ARRAY['Mishnah Berurah', 'Aruch HaShulchan', 'Kaf HaChaim'], ARRAY['Shabbat carrying laws', 'Relationship with material world'], true),
('Shabbat Meals', 'סעודות שבת', 'halacha', 'shabbat', 30, 25, 35, 'intermediate', 'Orach Chaim 274:1', 'Orach Chaim 274:10', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.274.1', 'Laws and customs of the three Shabbat meals', 'הלכות ומנהגי שלוש סעודות שבת', 'How do the three Shabbat meals structure and enhance your Shabbat experience?', 'כיצד שלוש סעודות שבת מבנות ומעשירות את חוויית השבת?', ARRAY['Mishnah Berurah', 'Aruch HaShulchan', 'Kaf HaChaim'], ARRAY['Shabbat meal requirements', 'Spiritual nourishment'], true),
('Havdalah Ceremony', 'הלכות הבדלה', 'halacha', 'shabbat', 35, 30, 40, 'intermediate', 'Orach Chaim 296:1', 'Orach Chaim 296:8', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.296.1', 'Laws and meaning of the Havdalah ceremony', 'הלכות ומשמעות טקס ההבדלה', 'What emotions and thoughts arise during the transition from Shabbat to the weekdays?', 'אילו רגשות ומחשבות עולים במעבר משבת לימי החול?', ARRAY['Mishnah Berurah', 'Aruch HaShulchan', 'Kaf HaChaim'], ARRAY['Havdalah requirements', 'Sacred time transitions'], true),
('Shabbat Singing', 'זמירות שבת', 'halacha', 'shabbat', 40, 35, 45, 'beginner', 'Orach Chaim 267:1', 'Orach Chaim 267:3', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.267.1', 'The role and importance of Shabbat songs', 'התפקיד והחשיבות של זמירות שבת', 'How does singing on Shabbat elevate both your personal and communal experience?', 'כיצד שירה בשבת מרוממת את החוויה האישית והקהילתית?', ARRAY['Mishnah Berurah', 'Aruch HaShulchan', 'Kaf HaChaim'], ARRAY['Shabbat music traditions', 'Joy in observance'], true),
('Muktzeh Laws', 'הלכות מוקצה', 'halacha', 'shabbat', 45, 40, 50, 'advanced', 'Orach Chaim 308:1', 'Orach Chaim 310:8', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.308.1', 'Complex laws of items forbidden to move on Shabbat', 'הלכות מורכבות של חפצים האסורים בטלטול בשבת', 'What does the concept of muktzeh teach us about intentionality in our actions?', 'מה מלמד אותנו הרעיון של מוקצה על כוונה במעשינו?', ARRAY['Mishnah Berurah', 'Aruch HaShulchan', 'Kaf HaChaim'], ARRAY['Advanced Shabbat laws', 'Intentional living'], true),
('Shabbat Preparations', 'הכנות לשבת', 'halacha', 'shabbat', 50, 45, 55, 'intermediate', 'Orach Chaim 250:1', 'Orach Chaim 250:5', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.250.1', 'Laws and customs for preparing for Shabbat', 'הלכות ומנהגי ההכנה לשבת', 'How does the process of preparing for Shabbat throughout the week enhance your anticipation?', 'כיצד תהליך ההכנה לשבת במשך השבוע מגביר את הציפייה?', ARRAY['Mishnah Berurah', 'Aruch HaShulchan', 'Kaf HaChaim'], ARRAY['Shabbat preparation', 'Weekly spiritual rhythm'], true);

-- Kashrut (6 sources)  
INSERT INTO sources (title, title_he, category, subcategory, estimated_time, min_time, max_time, difficulty_level, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, commentaries, learning_objectives, published) VALUES
('Meat and Dairy Separation', 'הפרדת בשר וחלב', 'halacha', 'kashrut', 20, 15, 25, 'intermediate', 'Yoreh Deah 87:1', 'Yoreh Deah 87:5', 'https://www.sefaria.org/Shulchan_Arukh%2C_Yoreh_De%27ah.87.1', 'Laws separating meat and dairy foods', 'הלכות הפרדת מזונות בשר וחלב', 'What spiritual lessons can be learned from the careful separation of meat and dairy?', 'אילו לקחים רוחניים ניתן ללמוד מההפרדה הקפדנית של בשר וחלב?', ARRAY['Shach', 'Taz', 'Aruch HaShulchan'], ARRAY['Kashrut fundamentals', 'Mindful consumption'], true),
('Kosher Slaughter', 'הלכות שחיטה', 'halacha', 'kashrut', 30, 25, 35, 'advanced', 'Yoreh Deah 1:1', 'Yoreh Deah 1:10', 'https://www.sefaria.org/Shulchan_Arukh%2C_Yoreh_De%27ah.1.1', 'Laws and ethics of kosher slaughter', 'הלכות ואתיקה של שחיטה כשרה', 'How do kosher slaughter laws reflect Jewish values about animal welfare and life?', 'כיצד הלכות השחיטה משקפות ערכים יהודיים על רווחת בעלי חיים וחיים?', ARRAY['Shach', 'Taz', 'Aruch HaShulchan'], ARRAY['Kosher slaughter knowledge', 'Ethical consumption'], true),
('Wine and Grape Products', 'יין ותוצרי ענבים', 'halacha', 'kashrut', 25, 20, 30, 'intermediate', 'Yoreh Deah 123:1', 'Yoreh Deah 123:8', 'https://www.sefaria.org/Shulchan_Arukh%2C_Yoreh_De%27ah.123.1', 'Special kashrut laws for wine and grape products', 'הלכות כשרות מיוחדות ליין ותוצרי ענבים', 'Why do wine and grape products have special significance in Jewish law and ritual?', 'מדוע ליין ותוצרי ענבים יש משמעות מיוחדת בהלכה ובטקס היהודי?', ARRAY['Shach', 'Taz', 'Aruch HaShulchan'], ARRAY['Wine kashrut', 'Ritual sanctification'], true),
('Kitchen Organization', 'ארגון המטבח הכשר', 'halacha', 'kashrut', 35, 30, 40, 'beginner', 'Yoreh Deah 95:1', 'Yoreh Deah 95:4', 'https://www.sefaria.org/Shulchan_Arukh%2C_Yoreh_De%27ah.95.1', 'Organizing a kosher kitchen properly', 'ארגון נכון של מטבח כשר', 'How does maintaining a kosher kitchen create awareness and intentionality in daily cooking?', 'כיצד שמירה על מטבח כשר יוצרת מודעות וכוונה בבישול היומיומי?', ARRAY['Shach', 'Taz', 'Aruch HaShulchan'], ARRAY['Kitchen kashrut setup', 'Domestic sanctification'], true),
('Checking for Insects', 'בדיקת תולעים', 'halacha', 'kashrut', 40, 35, 45, 'advanced', 'Yoreh Deah 84:1', 'Yoreh Deah 84:8', 'https://www.sefaria.org/Shulchan_Arukh%2C_Yoreh_De%27ah.84.1', 'Laws for checking fruits and vegetables for insects', 'הלכות בדיקת פירות וירקות לתולעים', 'What does the requirement to check for insects teach us about attention to detail in spiritual life?', 'מה מלמדת החובה לבדוק תולעים על תשומת לב לפרטים בחיים הרוחניים?', ARRAY['Shach', 'Taz', 'Aruch HaShulchan'], ARRAY['Insect checking procedures', 'Spiritual meticulousness'], true),
('Passover Kashrut', 'כשרות לפסח', 'halacha', 'kashrut', 50, 45, 55, 'advanced', 'Orach Chaim 447:1', 'Orach Chaim 447:12', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.447.1', 'Special kashrut requirements for Passover', 'דרישות כשרות מיוחדות לפסח', 'How does the intensive preparation for Passover kashrut parallel spiritual preparation for freedom?', 'כיצד ההכנה האינטנסיבית לכשרות פסח מקבילה להכנה רוחנית לחירות?', ARRAY['Mishnah Berurah', 'Aruch HaShulchan', 'Kaf HaChaim'], ARRAY['Passover kashrut', 'Spiritual liberation preparation'], true);

-- Prayer (8 sources)
INSERT INTO sources (title, title_he, category, subcategory, estimated_time, min_time, max_time, difficulty_level, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, commentaries, learning_objectives, published) VALUES
('Shema Structure', 'מבנה קריאת שמע', 'halacha', 'prayer', 15, 10, 20, 'beginner', 'Orach Chaim 58:1', 'Orach Chaim 58:8', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.58.1', 'Structure and meaning of the Shema prayer', 'מבנה ומשמעות תפילת שמע', 'How does reciting the Shema morning and evening frame your relationship with the Divine?', 'כיצד אמירת שמע בבוקר ובערב מגדירה את היחס שלך לאלוקים?', ARRAY['Mishnah Berurah', 'Aruch HaShulchan', 'Kaf HaChaim'], ARRAY['Shema comprehension', 'Divine unity awareness'], true),
('Amidah Prayer Laws', 'הלכות תפילת עמידה', 'halacha', 'prayer', 25, 20, 30, 'intermediate', 'Orach Chaim 89:1', 'Orach Chaim 89:7', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.89.1', 'Laws governing the standing prayer (Amidah)', 'הלכות תפילת העמידה', 'What does standing in prayer symbolize about your relationship with the Divine?', 'מה מסמלת עמידה בתפילה על היחס שלך עם האלוקים?', ARRAY['Mishnah Berurah', 'Aruch HaShulchan', 'Kaf HaChaim'], ARRAY['Amidah mastery', 'Standing before the Divine'], true),
('Prayer Timing', 'זמני תפילה', 'halacha', 'prayer', 30, 25, 35, 'intermediate', 'Orach Chaim 89:1', 'Orach Chaim 89:8', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.89.1', 'Proper times for daily prayers', 'זמנים נכונים לתפילות יומיות', 'How does praying at specific times throughout the day create a rhythm of spiritual connection?', 'כיצד תפילה בזמנים מסוימים ביום יוצרת קצב של קשר רוחני?', ARRAY['Mishnah Berurah', 'Aruch HaShulchan', 'Kaf HaChaim'], ARRAY['Prayer timing mastery', 'Daily spiritual rhythm'], true),
('Interruptions in Prayer', 'הפסקות בתפילה', 'halacha', 'prayer', 35, 30, 40, 'advanced', 'Orach Chaim 104:1', 'Orach Chaim 104:7', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.104.1', 'Laws about interruptions and mistakes in prayer', 'הלכות הפסקות וטעויות בתפילה', 'What do the laws about prayer interruptions teach us about focus and intention in spiritual practice?', 'מה מלמדות הלכות הפסקות בתפילה על ריכוז וכוונה בפרקטיקה רוחנית?', ARRAY['Mishnah Berurah', 'Aruch HaShulchan', 'Kaf HaChaim'], ARRAY['Prayer concentration', 'Spiritual focus techniques'], true),
('Minyan Requirements', 'דיני מנין', 'halacha', 'prayer', 20, 15, 25, 'intermediate', 'Orach Chaim 55:1', 'Orach Chaim 55:8', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.55.1', 'Laws requiring a prayer quorum (minyan)', 'הלכות הדורשות מנין לתפילה', 'What is the spiritual significance of communal prayer versus individual prayer?', 'מה המשמעות הרוחנית של תפילה קהילתית לעומת תפילה יחידית?', ARRAY['Mishnah Berurah', 'Aruch HaShulchan', 'Kaf HaChaim'], ARRAY['Communal prayer importance', 'Collective spiritual experience'], true),
('Tefillin in Prayer', 'תפילין בתפילה', 'halacha', 'prayer', 40, 35, 45, 'advanced', 'Orach Chaim 25:1', 'Orach Chaim 25:5', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.25.1', 'Wearing tefillin during prayer', 'הנחת תפילין בזמן תפילה', 'How does wearing tefillin during prayer enhance your spiritual focus and connection?', 'כיצד הנחת תפילין בזמן תפילה מעמיקה את הריכוז והקשר הרוחני?', ARRAY['Mishnah Berurah', 'Aruch HaShulchan', 'Kaf HaChaim'], ARRAY['Tefillin prayer enhancement', 'Physical-spiritual integration'], true),
('Women and Prayer', 'נשים ותפילה', 'halacha', 'prayer', 45, 40, 50, 'intermediate', 'Orach Chaim 106:1', 'Orach Chaim 106:4', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.106.1', 'Laws regarding women and prayer obligations', 'הלכות נשים וחובות תפילה', 'How do different prayer obligations create diverse but equally meaningful spiritual paths?', 'כיצד חובות תפילה שונות יוצרות דרכים רוחניות מגוונות אך משמעותיות באותה מידה?', ARRAY['Mishnah Berurah', 'Aruch HaShulchan', 'Kaf HaChaim'], ARRAY['Gender and prayer law', 'Diverse spiritual expression'], true),
('Blessing Errors', 'טעויות בברכות', 'halacha', 'prayer', 55, 50, 60, 'advanced', 'Orach Chaim 209:1', 'Orach Chaim 209:5', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.209.1', 'What to do when mistakes are made in blessings', 'מה לעשות כאשר נעשות טעויות בברכות', 'How can mistakes in prayer and blessings become opportunities for growth rather than just corrections?', 'כיצד טעויות בתפילה ובברכות יכולות להפוך להזדמנויות לצמיחה ולא רק לתיקונים?', ARRAY['Mishnah Berurah', 'Aruch HaShulchan', 'Kaf HaChaim'], ARRAY['Blessing correction procedures', 'Learning from spiritual mistakes'], true);