-- Continue Phase 1: Adding TANAKH sources (30 total) + TALMUD sources (25 total) + SPIRITUAL sources (25 total) + SURPRISE sources (15 total)

-- TANAKH SOURCES - weekly_portion (15 sources)
INSERT INTO sources (title, title_he, category, subcategory, estimated_time, min_time, max_time, difficulty_level, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, commentaries, learning_objectives, published) VALUES
('Creation and Human Purpose', 'בריאה ותכלית האדם', 'tanakh', 'weekly_portion', 20, 15, 25, 'beginner', 'Genesis 1:26', 'Genesis 1:28', 'https://www.sefaria.org/Genesis.1.26', 'The creation of humanity in God image and the divine mandate', 'בריאת האדם בצלם אלוקים והמנדט האלוקי', 'What does it mean to you to be created in the image of God and how does this affect your daily choices?', 'מה זה אומר לך להיבראות בצלם אלוקים וכיצד זה משפיע על הבחירות היומיומיות שלך?', ARRAY['Rashi', 'Ramban', 'Ibn Ezra'], ARRAY['Divine image understanding', 'Human purpose exploration'], true),
('Cain and Abel', 'קין והבל', 'tanakh', 'weekly_portion', 25, 20, 30, 'intermediate', 'Genesis 4:3', 'Genesis 4:8', 'https://www.sefaria.org/Genesis.4.3', 'The first brothers and the first murder', 'האחים הראשונים והרצח הראשון', 'How do jealousy and competition affect your relationships with siblings or close friends?', 'כיצד קנאה ותחרות משפיעות על היחסים שלך עם אחים או חברים קרובים?', ARRAY['Rashi', 'Ramban', 'Ibn Ezra'], ARRAY['Sibling rivalry lessons', 'Jealousy management'], true),
('Abraham Call', 'קריאת אברהם', 'tanakh', 'weekly_portion', 18, 12, 25, 'beginner', 'Genesis 12:1', 'Genesis 12:3', 'https://www.sefaria.org/Genesis.12.1', 'God call to Abraham to leave his homeland', 'קריאת האלוקים לאברהם לעזוב את מולדתו', 'When have you had to leave your comfort zone for spiritual growth, and what did you learn?', 'מתי היית צריך לעזוב את אזור הנוחות שלך לצמיחה רוחנית, ומה למדת?', ARRAY['Rashi', 'Ramban', 'Ibn Ezra'], ARRAY['Faith journeys', 'Spiritual courage'], true),
('Binding of Isaac', 'עקדת יצחק', 'tanakh', 'weekly_portion', 35, 30, 40, 'advanced', 'Genesis 22:1', 'Genesis 22:14', 'https://www.sefaria.org/Genesis.22.1', 'Abraham ultimate test of faith', 'המבחן האולטימטיבי של אברהם באמונה', 'How do you respond when your deepest values seem to conflict with what you believe God is asking of you?', 'כיצד אתה מגיב כשהערכים העמוקים ביותר שלך נראים מתנגשים עם מה שאתה מאמין שהאלוקים מבקש ממך?', ARRAY['Rashi', 'Ramban', 'Ibn Ezra'], ARRAY['Ultimate sacrifice', 'Faith testing'], true),
('Jacob Dream', 'חלום יעקב', 'tanakh', 'weekly_portion', 22, 18, 28, 'intermediate', 'Genesis 28:10', 'Genesis 28:17', 'https://www.sefaria.org/Genesis.28.10', 'Jacob ladder and divine encounter', 'סולם יעקב והפגישה האלוקית', 'When have you felt most connected to the Divine, and what was that experience like?', 'מתי הרגשת הכי מחובר לאלוקים, ואיך הייתה החוויה הזו?', ARRAY['Rashi', 'Ramban', 'Ibn Ezra'], ARRAY['Divine encounters', 'Spiritual awakening'], true),
('Joseph Forgiveness', 'סליחת יוסף', 'tanakh', 'weekly_portion', 30, 25, 35, 'intermediate', 'Genesis 45:4', 'Genesis 45:8', 'https://www.sefaria.org/Genesis.45.4', 'Joseph reveals himself and forgives his brothers', 'יוסף מגלה את עצמו וסולח לאחיו', 'How do you find the strength to forgive someone who has deeply hurt you?', 'כיצד אתה מוצא את הכוח לסלוח למישהו שפגע בך עמוקות?', ARRAY['Rashi', 'Ramban', 'Ibn Ezra'], ARRAY['Forgiveness power', 'Sibling reconciliation'], true),
('Burning Bush', 'הסנה הבוער', 'tanakh', 'weekly_portion', 28, 22, 35, 'intermediate', 'Exodus 3:2', 'Exodus 3:6', 'https://www.sefaria.org/Exodus.3.2', 'Moses encounters God at the burning bush', 'משה פוגש את האלוקים בסנה הבוער', 'What burning bushes - moments of unexpected divine presence - have you experienced in your life?', 'אילו סנים בוערים - רגעים של נוכחות אלוקית בלתי צפויה - חווית בחייך?', ARRAY['Rashi', 'Ramban', 'Ibn Ezra'], ARRAY['Divine calling', 'Leadership reluctance'], true),
('Ten Commandments', 'עשרת הדברות', 'tanakh', 'weekly_portion', 40, 35, 45, 'beginner', 'Exodus 20:1', 'Exodus 20:14', 'https://www.sefaria.org/Exodus.20.1', 'The giving of the Ten Commandments at Sinai', 'מתן עשרת הדברות בסיני', 'Which of the Ten Commandments do you find most challenging to observe in modern life?', 'איזה מעשרת הדברות אתה מוצא הכי מאתגר לקיים בחיים המודרניים?', ARRAY['Rashi', 'Ramban', 'Ibn Ezra'], ARRAY['Fundamental ethics', 'Divine law comprehension'], true),
('Golden Calf', 'עגל הזהב', 'tanakh', 'weekly_portion', 45, 40, 50, 'advanced', 'Exodus 32:1', 'Exodus 32:6', 'https://www.sefaria.org/Exodus.32.1', 'The sin of the golden calf and its aftermath', 'חטא עגל הזהב והשלכותיו', 'What are the golden calves in your life - things that compete with your spiritual focus?', 'מה הם עגלי הזהב בחייך - דברים שמתחרים עם המיקוד הרוחני שלך?', ARRAY['Rashi', 'Ramban', 'Ibn Ezra'], ARRAY['Idolatry recognition', 'Spiritual priorities'], true),
('Spies Report', 'דוח המרגלים', 'tanakh', 'weekly_portion', 32, 28, 38, 'intermediate', 'Numbers 13:25', 'Numbers 13:33', 'https://www.sefaria.org/Numbers.13.25', 'The report of the spies and the people reaction', 'דוח המרגלים ותגובת העם', 'How do fear and doubt prevent you from pursuing goals that you know are worthwhile?', 'כיצד פחד וספק מונעים ממך לרדוף אחרי מטרות שאתה יודע שהן כדאיות?', ARRAY['Rashi', 'Ramban', 'Ibn Ezra'], ARRAY['Overcoming fear', 'Faith vs doubt'], true),
('Shema Declaration', 'הצהרת שמע', 'tanakh', 'weekly_portion', 15, 10, 20, 'beginner', 'Deuteronomy 6:4', 'Deuteronomy 6:7', 'https://www.sefaria.org/Deuteronomy.6.4', 'The central declaration of Jewish faith', 'ההצהרה המרכזית של האמונה היהודית', 'How does declaring God is One impact the way you see unity and division in the world?', 'כיצד הצהרת האלוקים אחד משפיעה על הדרך שבה אתה רואה אחדות וחלוקה בעולם?', ARRAY['Rashi', 'Ramban', 'Ibn Ezra'], ARRAY['Unity concepts', 'Faith declaration'], true),
('Moses Final Blessing', 'ברכת משה האחרונה', 'tanakh', 'weekly_portion', 50, 45, 55, 'advanced', 'Deuteronomy 33:1', 'Deuteronomy 33:5', 'https://www.sefaria.org/Deuteronomy.33.1', 'Moses blesses the tribes before his death', 'משה מברך את השבטים לפני מותו', 'What legacy do you hope to leave, and how are you building that legacy now?', 'איזו מורשת אתה מקווה להשאיר, וכיצד אתה בונה את המורשת הזו עכשיו?', ARRAY['Rashi', 'Ramban', 'Ibn Ezra'], ARRAY['Legacy building', 'Leadership transition'], true),
('Isaiah Vision', 'חזון ישעיהו', 'tanakh', 'prophets', 25, 20, 30, 'intermediate', 'Isaiah 6:1', 'Isaiah 6:8', 'https://www.sefaria.org/Isaiah.6.1', 'Isaiah prophetic calling and vision of God', 'קריאתו הנבואית של ישעיהו וחזון האלוקים', 'When have you felt overwhelmed by a sense of purpose or calling in your life?', 'מתי הרגשת המום מתחושת מטרה או קריאה בחייך?', ARRAY['Rashi', 'Radak', 'Metzudat David'], ARRAY['Prophetic calling', 'Divine vision'], true),
('Comfort My People', 'נחמו עמי', 'tanakh', 'prophets', 20, 15, 25, 'beginner', 'Isaiah 40:1', 'Isaiah 40:5', 'https://www.sefaria.org/Isaiah.40.1', 'God message of comfort to the exiled people', 'מסר הנחמה של האלוקים לעם הגולה', 'How do you find comfort and hope during your most difficult times?', 'כיצד אתה מוצא נחמה ותקווה בזמנים הקשים ביותר שלך?', ARRAY['Rashi', 'Radak', 'Metzudat David'], ARRAY['Divine comfort', 'Hope in exile'], true),
('Jonah Flight', 'בריחת יונה', 'tanakh', 'prophets', 28, 22, 35, 'intermediate', 'Jonah 1:1', 'Jonah 1:6', 'https://www.sefaria.org/Jonah.1.1', 'Jonah attempts to flee from his divine mission', 'יונה מנסה לברוח משליחותו האלוקית', 'When have you tried to run away from something you knew you needed to do?', 'מתי ניסית לברוח ממשהו שידעת שאתה צריך לעשות?', ARRAY['Rashi', 'Radak', 'Metzudat David'], ARRAY['Avoiding responsibility', 'Divine pursuit'], true);

-- TANAKH - Writings (15 sources)
INSERT INTO sources (title, title_he, category, subcategory, estimated_time, min_time, max_time, difficulty_level, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, commentaries, learning_objectives, published) VALUES
('Psalms of Praise', 'תהילים של שבח', 'tanakh', 'writings', 15, 10, 20, 'beginner', 'Psalms 150:1', 'Psalms 150:6', 'https://www.sefaria.org/Psalms.150.1', 'King David call to praise God with all instruments', 'קריאתו של דוד המלך לשבח את האלוקים בכל הכלים', 'What moves you to feel most grateful and full of praise in your daily life?', 'מה גורם לך להרגיש הכי אסיר תודה ומלא שבח בחיים היומיומיים שלך?', ARRAY['Rashi', 'Radak', 'Metzudat David'], ARRAY['Gratitude expression', 'Worship diversity'], true),
('Job Suffering', 'סבל איוב', 'tanakh', 'writings', 45, 40, 50, 'advanced', 'Job 1:8', 'Job 1:12', 'https://www.sefaria.org/Job.1.8', 'Job initial trial and his response to loss', 'המבחן הראשוני של איוב ותגובתו לאובדן', 'How do you maintain faith and integrity when everything seems to be going wrong?', 'כיצד אתה שומר על אמונה ויושרה כשנראה שהכל משתבש?', ARRAY['Rashi', 'Radak', 'Metzudat David'], ARRAY['Suffering theology', 'Faith under trial'], true),
('Ecclesiastes Wisdom', 'חוכמת קהלת', 'tanakh', 'writings', 30, 25, 35, 'intermediate', 'Ecclesiastes 3:1', 'Ecclesiastes 3:8', 'https://www.sefaria.org/Ecclesiastes.3.1', 'A time for everything under heaven', 'עת לכל חפץ תחת השמים', 'How do you find meaning and purpose in the seemingly cyclical nature of life?', 'כיצד אתה מוצא משמעות ומטרה בטבע המחזורי לכאורה של החיים?', ARRAY['Rashi', 'Radak', 'Metzudat David'], ARRAY['Life seasons', 'Meaning in temporality'], true),
('Proverbs Advice', 'עצות משלי', 'tanakh', 'writings', 20, 15, 25, 'beginner', 'Proverbs 3:5', 'Proverbs 3:8', 'https://www.sefaria.org/Proverbs.3.5', 'Trust in God with all your heart', 'בטח באלוקים בכל לבך', 'When do you find it hardest to trust in God rather than relying solely on your own understanding?', 'מתי אתה מוצא הכי קשה לבטוח באלוקים במקום להסתמך רק על ההבנה שלך?', ARRAY['Rashi', 'Radak', 'Metzudat David'], ARRAY['Trust development', 'Wisdom vs understanding'], true),
('Ruth Loyalty', 'נאמנות רות', 'tanakh', 'writings', 25, 20, 30, 'intermediate', 'Ruth 1:16', 'Ruth 1:17', 'https://www.sefaria.org/Ruth.1.16', 'Ruth declaration of loyalty to Naomi', 'הצהרת הנאמנות של רות לנעמי', 'What relationships in your life are worth maintaining even when it requires significant sacrifice?', 'אילו יחסים בחייך שווים שמירה גם כשזה דורש הקרבה משמעותית?', ARRAY['Rashi', 'Radak', 'Metzudat David'], ARRAY['Loyalty demonstration', 'Conversion commitment'], true),
('Esther Courage', 'אומץ אסתר', 'tanakh', 'writings', 40, 35, 45, 'intermediate', 'Esther 4:13', 'Esther 4:16', 'https://www.sefaria.org/Esther.4.13', 'Esther decision to risk her life for her people', 'החלטתה של אסתר לסכן את חייה למען עמה', 'When have you had to choose between personal safety and standing up for what is right?', 'מתי היית צריך לבחור בין בטיחות אישית לעמידה על מה שנכון?', ARRAY['Rashi', 'Radak', 'Metzudat David'], ARRAY['Moral courage', 'Personal risk for others'], true),
('Daniel Faith', 'אמונת דניאל', 'tanakh', 'writings', 50, 45, 55, 'advanced', 'Daniel 6:11', 'Daniel 6:17', 'https://www.sefaria.org/Daniel.6.11', 'Daniel continues praying despite the king decree', 'דניאל ממשיך להתפלל למרות גזירת המלך', 'How do you maintain your religious practices when they conflict with social or legal pressures?', 'כיצד אתה שומר על הפרקטיקות הדתיות שלך כשהן מתנגשות עם לחצים חברתיים או משפטיים?', ARRAY['Rashi', 'Radak', 'Metzudat David'], ARRAY['Religious courage', 'Faith under persecution'], true),
('Song of Songs Love', 'אהבת שיר השירים', 'tanakh', 'writings', 35, 30, 40, 'advanced', 'Song of Songs 2:10', 'Song of Songs 2:13', 'https://www.sefaria.org/Song_of_Songs.2.10', 'The beloved calls: arise, my love, and come away', 'הקורא הקרוב: קומי לך רעייתי', 'How do you experience the connection between human love and divine love?', 'כיצד אתה חווה את הקשר בין אהבה אנושית לאהבה אלוקית?', ARRAY['Rashi', 'Radak', 'Ibn Ezra'], ARRAY['Love mysticism', 'Divine-human intimacy'], true),
('Psalms of Longing', 'תהילים של כמיהה', 'tanakh', 'writings', 18, 12, 25, 'intermediate', 'Psalms 42:2', 'Psalms 42:4', 'https://www.sefaria.org/Psalms.42.2', 'As the deer pants for streams of water', 'כאיל תערוג על אפיקי מים', 'What spiritual thirst do you experience, and how do you seek to quench it?', 'איזה צמא רוחני אתה חווה, וכיצד אתה מבקש להרוות אותו?', ARRAY['Rashi', 'Radak', 'Metzudat David'], ARRAY['Spiritual longing', 'Divine thirst'], true),
('Lamentations Grief', 'אבל איכה', 'tanakh', 'writings', 38, 32, 45, 'advanced', 'Lamentations 3:22', 'Lamentations 3:24', 'https://www.sefaria.org/Lamentations.3.22', 'God mercies never cease, they are new every morning', 'חסדי ה לא תמנו כי לא כלו רחמיו', 'How do you find hope and renewal even in times of profound loss or disappointment?', 'כיצד אתה מוצא תקווה והתחדשות גם בזמנים של אובדן או אכזבה עמוקים?', ARRAY['Rashi', 'Radak', 'Metzudat David'], ARRAY['Hope in suffering', 'Divine mercy awareness'], true),
('Chronicles Leadership', 'מנהיגות דברי הימים', 'tanakh', 'writings', 42, 38, 48, 'intermediate', '1 Chronicles 29:11', '1 Chronicles 29:13', 'https://www.sefaria.org/I_Chronicles.29.11', 'David prayer of gratitude for the Temple preparations', 'תפילת דוד של הכרת הטוב להכנות המקדש', 'How do you acknowledge that your accomplishments depend on divine blessing and community support?', 'כיצד אתה מכיר בכך שההישגים שלך תלויים בברכה אלוקית ובתמיכה קהילתית?', ARRAY['Rashi', 'Radak', 'Metzudat David'], ARRAY['Humble leadership', 'Gratitude in success'], true),
('Ezra Return', 'שיבת עזרא', 'tanakh', 'writings', 33, 28, 38, 'intermediate', 'Ezra 7:27', 'Ezra 7:28', 'https://www.sefaria.org/Ezra.7.27', 'Blessed be God who put it in the heart of the king', 'ברוך ה אלוקי אבותינו אשר נתן כזאת בלב המלך', 'How do you recognize divine guidance working through unexpected human agents?', 'כיצד אתה מזהה הדרכה אלוקית הפועלת דרך שליחים אנושיים בלתי צפויים?', ARRAY['Rashi', 'Radak', 'Metzudat David'], ARRAY['Divine orchestration', 'Unexpected providence'], true),
('Nehemiah Rebuilding', 'בנייה מחדש נחמיה', 'tanakh', 'writings', 44, 38, 50, 'intermediate', 'Nehemiah 2:17', 'Nehemiah 2:20', 'https://www.sefaria.org/Nehemiah.2.17', 'Come, let us rebuild the wall of Jerusalem', 'לכו ונבנה את חומת ירושלים', 'What broken things in your community or life are you called to help rebuild?', 'אילו דברים שבורים בקהילה או בחיים שלך אתה נקרא לעזור לבנות מחדש?', ARRAY['Rashi', 'Radak', 'Metzudat David'], ARRAY['Community rebuilding', 'Collective responsibility'], true),
('Psalms Protection', 'תהילים של הגנה', 'tanakh', 'writings', 22, 18, 28, 'beginner', 'Psalms 91:1', 'Psalms 91:4', 'https://www.sefaria.org/Psalms.91.1', 'He who dwells in the shelter of the Most High', 'יושב בסתר עליון בצל שדי יתלונן', 'When do you feel most protected and secure, and what creates that sense of safety for you?', 'מתי אתה מרגיש הכי מוגן ובטוח, ומה יוצר את תחושת הבטיחות הזו עבורך?', ARRAY['Rashi', 'Radak', 'Metzudat David'], ARRAY['Divine protection', 'Trust in security'], true),
('Proverbs Woman of Valor', 'אשת חיל משלי', 'tanakh', 'writings', 26, 20, 32, 'intermediate', 'Proverbs 31:10', 'Proverbs 31:15', 'https://www.sefaria.org/Proverbs.31.10', 'A woman of valor, who can find?', 'אשת חיל מי ימצא', 'What qualities of strength, wisdom and capability do you most admire in the people around you?', 'אילו תכונות של כוח, חוכמה ויכולת אתה הכי מעריך באנשים סביבך?', ARRAY['Rashi', 'Radak', 'Metzudat David'], ARRAY['Strength appreciation', 'Character recognition'], true);