-- Phase 1: Massive Source Content Expansion
-- Adding 150+ sources across all categories with proper time distribution and commentaries

-- HALACHA SOURCES (30 total)
-- Daily Practice (8 sources)
INSERT INTO sources (title, title_he, category, subcategory, estimated_time, min_time, max_time, difficulty_level, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, commentaries, learning_objectives, published) VALUES
('Morning Blessings Structure', 'סדר ברכות השחר', 'halacha', 'daily_practice', 10, 5, 15, 'beginner', 'Orach Chaim 46:1', 'Orach Chaim 46:3', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.46.1', 'The structure and meaning of morning blessings that begin our day', 'מבנה ומשמעות ברכות השחר המתחילות את יומנו', 'How do morning blessings set the tone for your entire day?', 'כיצד ברכות השחר קובעות את הטון לכל היום שלך?', '["Mishnah Berurah", "Aruch HaShulchan", "Kaf HaChaim"]', '["Understanding daily blessing structure", "Spiritual preparation for the day"]', true),
('Hand Washing Laws', 'הלכות נטילת ידיים', 'halacha', 'daily_practice', 15, 10, 20, 'intermediate', 'Orach Chaim 158:1', 'Orach Chaim 158:12', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.158.1', 'Complete laws governing when and how we wash our hands', 'הלכות המפרטות מתי וכיצד נוטלים ידיים', 'What spiritual significance do you find in the act of washing hands before eating?', 'איזה משמעות רוחנית אתה מוצא במעשה נטילת הידיים לפני האכילה?', '["Mishnah Berurah", "Shaar HaTziyun", "Biur Halakha"]', '["Practical hand washing knowledge", "Understanding ritual purity"]', true),
('Daily Torah Study Obligation', 'חובת תלמוד תורה יומי', 'halacha', 'daily_practice', 20, 15, 25, 'intermediate', 'Yoreh Deah 246:1', 'Yoreh Deah 246:5', 'https://www.sefaria.org/Shulchan_Arukh%2C_Yoreh_De%27ah.246.1', 'The obligation and methods for daily Torah study', 'החובה והשיטות ללימוד תורה יומי', 'How can you structure your day to fulfill the mitzvah of daily Torah study?', 'כיצד תוכל לארגן את יומך כדי לקיים את מצוות תלמוד תורה יומי?', '["Shach", "Taz", "Aruch HaShulchan"]', '["Understanding Torah study requirements", "Creating sustainable learning habits"]', true),
('Mezuzah Placement', 'מקום קביעת המזוזה', 'halacha', 'daily_practice', 25, 20, 30, 'advanced', 'Yoreh Deah 289:1', 'Yoreh Deah 289:6', 'https://www.sefaria.org/Shulchan_Arukh%2C_Yoreh_De%27ah.289.1', 'Detailed laws about where and how to place mezuzot', 'הלכות מפורטות על מיקום וקביעת מזוזות', 'What does the mezuzah represent in terms of sanctifying your living space?', 'מה המזוזה מייצגת מבחינת קידוש מקום המגורים?', '["Shach", "Taz", "Pitchei Teshuvah"]', '["Mezuzah placement requirements", "Home sanctification concepts"]', true),
('Tefillin Laws Overview', 'כללי הלכות תפילין', 'halacha', 'daily_practice', 30, 25, 35, 'advanced', 'Orach Chaim 25:1', 'Orach Chaim 25:15', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.25.1', 'Comprehensive overview of tefillin laws and customs', 'סקירה מקיפה של הלכות ומנהגי תפילין', 'How does wearing tefillin create a connection between thought, speech, and action?', 'כיצד הנחת תפילין יוצרת קשר בין מחשבה, דיבור ומעשה?', '["Mishnah Berurah", "Aruch HaShulchan", "Kaf HaChaim"]', '["Tefillin requirements", "Mind-body spiritual connection"]', true),
('Charity Obligations', 'חובות צדקה', 'halacha', 'daily_practice', 35, 30, 40, 'intermediate', 'Yoreh Deah 249:1', 'Yoreh Deah 249:10', 'https://www.sefaria.org/Shulchan_Arukh%2C_Yoreh_De%27ah.249.1', 'Laws governing our obligations to give charity', 'הלכות החובות לתת צדקה', 'How can giving charity become a meaningful daily practice rather than just an obligation?', 'כיצד נתינת צדקה יכולה להפוך להרגל יומי משמעותי ולא רק חובה?', '["Shach", "Taz", "Aruch HaShulchan"]', '["Charity obligations", "Developing generosity"]', true),
('Blessings on Food', 'ברכות על המזון', 'halacha', 'daily_practice', 40, 35, 45, 'beginner', 'Orach Chaim 202:1', 'Orach Chaim 202:20', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.202.1', 'Comprehensive guide to blessings before and after eating', 'מדריך מקיף לברכות לפני ואחרי האכילה', 'How do food blessings transform eating from a physical act into a spiritual experience?', 'כיצד ברכות על המזון הופכות את האכילה ממעשה גשמי לחוויה רוחנית?', '["Mishnah Berurah", "Aruch HaShulchan", "Kaf HaChaim"]', '["Food blessing mastery", "Mindful eating practices"]', true),
('Evening Prayer Structure', 'מבנה תפילת ערבית', 'halacha', 'daily_practice', 45, 40, 50, 'intermediate', 'Orach Chaim 235:1', 'Orach Chaim 235:5', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.235.1', 'Structure and laws of the evening prayer service', 'מבנה והלכות תפילת ערבית', 'What themes in the evening prayers help you reflect on and conclude your day?', 'אילו נושאים בתפילת ערבית עוזרים לך להרהר ולסיים את יומך?', '["Mishnah Berurah", "Aruch HaShulchan", "Kaf HaChaim"]', '["Evening prayer structure", "Daily spiritual closure"]', true),

-- Shabbat (8 sources)
('Shabbat Candle Lighting', 'הדלקת נרות שבת', 'halacha', 'shabbat', 12, 8, 18, 'beginner', 'Orach Chaim 263:1', 'Orach Chaim 263:5', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.263.1', 'Laws and customs of lighting Shabbat candles', 'הלכות ומנהגי הדלקת נרות שבת', 'How does lighting Shabbat candles transform your home and mindset for Shabbat?', 'כיצד הדלקת נרות שבת משנה את הבית והמחשבה לקראת שבת?', '["Mishnah Berurah", "Aruch HaShulchan", "Kaf HaChaim"]', '["Shabbat preparation", "Home sanctification"]', true),
('Kiddush Requirements', 'דיני קידוש', 'halacha', 'shabbat', 18, 15, 25, 'intermediate', 'Orach Chaim 271:1', 'Orach Chaim 271:10', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.271.1', 'Complete laws governing Kiddush on Shabbat', 'הלכות מלאות של קידוש בשבת', 'What does the act of Kiddush teach us about sanctifying time?', 'מה מלמד אותנו מעשה הקידוש על קידוש הזמן?', '["Mishnah Berurah", "Aruch HaShulchan", "Kaf HaChaim"]', '["Kiddush mastery", "Time sanctification concepts"]', true),
('Carrying on Shabbat', 'איסור טלטול בשבת', 'halacha', 'shabbat', 25, 20, 30, 'advanced', 'Orach Chaim 308:1', 'Orach Chaim 308:20', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.308.1', 'Laws of carrying and moving objects on Shabbat', 'הלכות טלטול והעברת חפצים בשבת', 'How do carrying restrictions on Shabbat help create a different relationship with physical objects?', 'כיצד הגבלות הטלטול בשבת עוזרות ליצור יחס שונה לחפצים הפיזיים?', '["Mishnah Berurah", "Aruch HaShulchan", "Kaf HaChaim"]', '["Shabbat carrying laws", "Relationship with material world"]', true),
('Shabbat Meals', 'סעודות שבת', 'halacha', 'shabbat', 30, 25, 35, 'intermediate', 'Orach Chaim 274:1', 'Orach Chaim 274:10', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.274.1', 'Laws and customs of the three Shabbat meals', 'הלכות ומנהגי שלוש סעודות שבת', 'How do the three Shabbat meals structure and enhance your Shabbat experience?', 'כיצד שלוש סעודות שבת מבנות ומעשירות את חוויית השבת?', '["Mishnah Berurah", "Aruch HaShulchan", "Kaf HaChaim"]', '["Shabbat meal requirements", "Spiritual nourishment"]', true),
('Havdalah Ceremony', 'הלכות הבדלה', 'halacha', 'shabbat', 35, 30, 40, 'intermediate', 'Orach Chaim 296:1', 'Orach Chaim 296:8', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.296.1', 'Laws and meaning of the Havdalah ceremony', 'הלכות ומשמעות טקס ההבדלה', 'What emotions and thoughts arise during the transition from Shabbat to the weekdays?', 'אילו רגשות ומחשבות עולים במעבר משבת לימי החול?', '["Mishnah Berurah", "Aruch HaShulchan", "Kaf HaChaim"]', '["Havdalah requirements", "Sacred time transitions"]', true),
('Shabbat Singing', 'זמירות שבת', 'halacha', 'shabbat', 40, 35, 45, 'beginner', 'Orach Chaim 267:1', 'Orach Chaim 267:3', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.267.1', 'The role and importance of Shabbat songs', 'התפקיד והחשיבות של זמירות שבת', 'How does singing on Shabbat elevate both your personal and communal experience?', 'כיצד שירה בשבת מרוממת את החוויה האישית והקהילתית?', '["Mishnah Berurah", "Aruch HaShulchan", "Kaf HaChaim"]', '["Shabbat music traditions", "Joy in observance"]', true),
('Muktzeh Laws', 'הלכות מוקצה', 'halacha', 'shabbat', 45, 40, 50, 'advanced', 'Orach Chaim 308:1', 'Orach Chaim 310:8', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.308.1', 'Complex laws of items forbidden to move on Shabbat', 'הלכות מורכבות של חפצים האסורים בטלטול בשבת', 'What does the concept of muktzeh teach us about intentionality in our actions?', 'מה מלמד אותנו הרעיון של מוקצה על כוונה במעשינו?', '["Mishnah Berurah", "Aruch HaShulchan", "Kaf HaChaim"]', '["Advanced Shabbat laws", "Intentional living"]', true),
('Shabbat Preparations', 'הכנות לשבת', 'halacha', 'shabbat', 50, 45, 55, 'intermediate', 'Orach Chaim 250:1', 'Orach Chaim 250:5', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.250.1', 'Laws and customs for preparing for Shabbat', 'הלכות ומנהגי ההכנה לשבת', 'How does the process of preparing for Shabbat throughout the week enhance your anticipation?', 'כיצד תהליך ההכנה לשבת במשך השבוע מגביר את הציפייה?', '["Mishnah Berurah", "Aruch HaShulchan", "Kaf HaChaim"]', '["Shabbat preparation", "Weekly spiritual rhythm"]', true),

-- Kashrut (6 sources)  
('Meat and Dairy Separation', 'הפרדת בשר וחלב', 'halacha', 'kashrut', 20, 15, 25, 'intermediate', 'Yoreh Deah 87:1', 'Yoreh Deah 87:5', 'https://www.sefaria.org/Shulchan_Arukh%2C_Yoreh_De%27ah.87.1', 'Laws separating meat and dairy foods', 'הלכות הפרדת מזונות בשר וחלב', 'What spiritual lessons can be learned from the careful separation of meat and dairy?', 'אילו לקחים רוחניים ניתן ללמוד מההפרדה הקפדנית של בשר וחלב?', '["Shach", "Taz", "Aruch HaShulchan"]', '["Kashrut fundamentals", "Mindful consumption"]', true),
('Kosher Slaughter', 'הלכות שחיטה', 'halacha', 'kashrut', 30, 25, 35, 'advanced', 'Yoreh Deah 1:1', 'Yoreh Deah 1:10', 'https://www.sefaria.org/Shulchan_Arukh%2C_Yoreh_De%27ah.1.1', 'Laws and ethics of kosher slaughter', 'הלכות ואתיקה של שחיטה כשרה', 'How do kosher slaughter laws reflect Jewish values about animal welfare and life?', 'כיצד הלכות השחיטה משקפות ערכים יהודיים על רווחת בעלי חיים וחיים?', '["Shach", "Taz", "Aruch HaShulchan"]', '["Kosher slaughter knowledge", "Ethical consumption"]', true),
('Wine and Grape Products', 'יין ותוצרי ענבים', 'halacha', 'kashrut', 25, 20, 30, 'intermediate', 'Yoreh Deah 123:1', 'Yoreh Deah 123:8', 'https://www.sefaria.org/Shulchan_Arukh%2C_Yoreh_De%27ah.123.1', 'Special kashrut laws for wine and grape products', 'הלכות כשרות מיוחדות ליין ותוצרי ענבים', 'Why do wine and grape products have special significance in Jewish law and ritual?', 'מדוע ליין ותוצרי ענבים יש משמעות מיוחדת בהלכה ובטקס היהודי?', '["Shach", "Taz", "Aruch HaShulchan"]', '["Wine kashrut", "Ritual sanctification"]', true),
('Kitchen Organization', 'ארגון המטבח הכשר', 'halacha', 'kashrut', 35, 30, 40, 'beginner', 'Yoreh Deah 95:1', 'Yoreh Deah 95:4', 'https://www.sefaria.org/Shulchan_Arukh%2C_Yoreh_De%27ah.95.1', 'Organizing a kosher kitchen properly', 'ארגון נכון של מטבח כשר', 'How does maintaining a kosher kitchen create awareness and intentionality in daily cooking?', 'כיצד שמירה על מטבח כשר יוצרת מודעות וכוונה בבישול היומיומי?', '["Shach", "Taz", "Aruch HaShulchan"]', '["Kitchen kashrut setup", "Domestic sanctification"]', true),
('Checking for Insects', 'בדיקת תולעים', 'halacha', 'kashrut', 40, 35, 45, 'advanced', 'Yoreh Deah 84:1', 'Yoreh Deah 84:8', 'https://www.sefaria.org/Shulchan_Arukh%2C_Yoreh_De%27ah.84.1', 'Laws for checking fruits and vegetables for insects', 'הלכות בדיקת פירות וירקות לתולעים', 'What does the requirement to check for insects teach us about attention to detail in spiritual life?', 'מה מלמדת החובה לבדוק תולעים על תשומת לב לפרטים בחיים הרוחניים?', '["Shach", "Taz", "Aruch HaShulchan"]', '["Insect checking procedures", "Spiritual meticulousness"]', true),
('Passover Kashrut', 'כשרות לפסח', 'halacha', 'kashrut', 50, 45, 55, 'advanced', 'Orach Chaim 447:1', 'Orach Chaim 447:12', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.447.1', 'Special kashrut requirements for Passover', 'דרישות כשרות מיוחדות לפסח', 'How does the intensive preparation for Passover kashrut parallel spiritual preparation for freedom?', 'כיצד ההכנה האינטנסיבית לכשרות פסח מקבילה להכנה רוחנית לחירות?', '["Mishnah Berurah", "Aruch HaShulchan", "Kaf HaChaim"]', '["Passover kashrut", "Spiritual liberation preparation"]', true),

-- Prayer (8 sources)
('Shema Structure', 'מבנה קריאת שמע', 'halacha', 'prayer', 15, 10, 20, 'beginner', 'Orach Chaim 58:1', 'Orach Chaim 58:8', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.58.1', 'Structure and meaning of the Shema prayer', 'מבנה ומשמעות תפילת שמע', 'How does reciting the Shema morning and evening frame your relationship with the Divine?', 'כיצד אמירת שמע בבוקר ובערב מגדירה את היחס שלך לאלוקים?', '["Mishnah Berurah", "Aruch HaShulchan", "Kaf HaChaim"]', '["Shema comprehension", "Divine unity awareness"]', true),
('Amidah Prayer Laws', 'הלכות תפילת עמידה', 'halacha', 'prayer', 25, 20, 30, 'intermediate', 'Orach Chaim 89:1', 'Orach Chaim 89:7', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.89.1', 'Laws governing the standing prayer (Amidah)', 'הלכות תפילת העמידה', 'What does standing in prayer symbolize about your relationship with the Divine?', 'מה מסמלת עמידה בתפילה על היחס שלך עם האלוקים?', '["Mishnah Berurah", "Aruch HaShulchan", "Kaf HaChaim"]', '["Amidah mastery", "Standing before the Divine"]', true),
('Prayer Timing', 'זמני תפילה', 'halacha', 'prayer', 30, 25, 35, 'intermediate', 'Orach Chaim 89:1', 'Orach Chaim 89:8', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.89.1', 'Proper times for daily prayers', 'זמנים נכונים לתפילות יומיות', 'How does praying at specific times throughout the day create a rhythm of spiritual connection?', 'כיצד תפילה בזמנים מסוימים ביום יוצרת קצב של קשר רוחני?', '["Mishnah Berurah", "Aruch HaShulchan", "Kaf HaChaim"]', '["Prayer timing mastery", "Daily spiritual rhythm"]', true),
('Interruptions in Prayer', 'הפסקות בתפילה', 'halacha', 'prayer', 35, 30, 40, 'advanced', 'Orach Chaim 104:1', 'Orach Chaim 104:7', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.104.1', 'Laws about interruptions and mistakes in prayer', 'הלכות הפסקות וטעויות בתפילה', 'What do the laws about prayer interruptions teach us about focus and intention in spiritual practice?', 'מה מלמדות הלכות הפסקות בתפילה על ריכוז וכוונה בפרקטיקה רוחנית?', '["Mishnah Berurah", "Aruch HaShulchan", "Kaf HaChaim"]', '["Prayer concentration", "Spiritual focus techniques"]', true),
('Minyan Requirements', 'דיני מנין', 'halacha', 'prayer', 20, 15, 25, 'intermediate', 'Orach Chaim 55:1', 'Orach Chaim 55:8', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.55.1', 'Laws requiring a prayer quorum (minyan)', 'הלכות הדורשות מנין לתפילה', 'What is the spiritual significance of communal prayer versus individual prayer?', 'מה המשמעות הרוחנית של תפילה קהילתית לעומת תפילה יחידית?', '["Mishnah Berurah", "Aruch HaShulchan", "Kaf HaChaim"]', '["Communal prayer importance", "Collective spiritual experience"]', true),
('Tefillin in Prayer', 'תפילין בתפילה', 'halacha', 'prayer', 40, 35, 45, 'advanced', 'Orach Chaim 25:1', 'Orach Chaim 25:5', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.25.1', 'Wearing tefillin during prayer', 'הנחת תפילין בזמן תפילה', 'How does wearing tefillin during prayer enhance your spiritual focus and connection?', 'כיצד הנחת תפילין בזמן תפילה מעמיקה את הריכוז והקשר הרוחני?', '["Mishnah Berurah", "Aruch HaShulchan", "Kaf HaChaim"]', '["Tefillin prayer enhancement", "Physical-spiritual integration"]', true),
('Women and Prayer', 'נשים ותפילה', 'halacha', 'prayer', 45, 40, 50, 'intermediate', 'Orach Chaim 106:1', 'Orach Chaim 106:4', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.106.1', 'Laws regarding women and prayer obligations', 'הלכות נשים וחובות תפילה', 'How do different prayer obligations create diverse but equally meaningful spiritual paths?', 'כיצד חובות תפילה שונות יוצרות דרכים רוחניות מגוונות אך משמעותיות באותה מידה?', '["Mishnah Berurah", "Aruch HaShulchan", "Kaf HaChaim"]', '["Gender and prayer law", "Diverse spiritual expression"]', true),
('Blessing Errors', 'טעויות בברכות', 'halacha', 'prayer', 55, 50, 60, 'advanced', 'Orach Chaim 209:1', 'Orach Chaim 209:5', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.209.1', 'What to do when mistakes are made in blessings', 'מה לעשות כאשר נעשות טעויות בברכות', 'How can mistakes in prayer and blessings become opportunities for growth rather than just corrections?', 'כיצד טעויות בתפילה ובברכות יכולות להפוך להזדמנויות לצמיחה ולא רק לתיקונים?', '["Mishnah Berurah", "Aruch HaShulchan", "Kaf HaChaim"]', '["Blessing correction procedures", "Learning from spiritual mistakes"]', true);

-- RAMBAM SOURCES (25 total)
-- Hilchot Deot (10 sources)
INSERT INTO sources (title, title_he, category, subcategory, estimated_time, min_time, max_time, difficulty_level, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, commentaries, learning_objectives, published) VALUES
('The Golden Mean', 'שביל הזהב', 'rambam', 'hilchot_deot', 15, 10, 20, 'beginner', 'Mishneh Torah, Deot 1:4', 'Mishneh Torah, Deot 1:6', 'https://www.sefaria.org/Mishneh_Torah%2C_Deot.1.4', 'Rambam teaches the middle path in character traits', 'הרמב"ם מלמד על דרך האמצע בתכונות האופי', 'How can you identify and work towards the golden mean in your own character traits?', 'כיצד תוכל לזהות ולפעול לקראת דרך האמצע בתכונות האופי שלך?', '["Lechem Mishneh", "Kesef Mishneh", "Radbaz"]', '["Character development", "Emotional balance"]', true),
('Anger Management', 'ניהול כעס', 'rambam', 'hilchot_deot', 20, 15, 25, 'intermediate', 'Mishneh Torah, Deot 2:3', 'Mishneh Torah, Deot 2:4', 'https://www.sefaria.org/Mishneh_Torah%2C_Deot.2.3', 'Rambam's approach to controlling anger', 'גישת הרמב"ם לשליטה בכעס', 'What triggers your anger most, and how can you apply Rambam's advice to manage it?', 'מה הכי מעורר את הכעס שלך, וכיצד תוכל ליישם את עצת הרמב"ם לנהל אותו?', '["Lechem Mishneh", "Kesef Mishneh", "Radbaz"]', '["Anger management", "Emotional self-control"]', true),
('Humility and Pride', 'ענווה וגאווה', 'rambam', 'hilchot_deot', 25, 20, 30, 'intermediate', 'Mishneh Torah, Deot 2:3', 'Mishneh Torah, Deot 2:5', 'https://www.sefaria.org/Mishneh_Torah%2C_Deot.2.3', 'The balance between humility and healthy self-regard', 'האיזון בין ענווה להערכה עצמית בריאה', 'How do you distinguish between healthy confidence and harmful pride in your daily interactions?', 'כיצד אתה מבחין בין ביטחון עצמי בריא לגאווה מזיקה באינטראקציות היומיומיות?', '["Lechem Mishneh", "Kesef Mishneh", "Radbaz"]', '["Humility cultivation", "Self-awareness development"]', true),
('Social Interaction', 'יחסים חברתיים', 'rambam', 'hilchot_deot', 30, 25, 35, 'intermediate', 'Mishneh Torah, Deot 6:1', 'Mishneh Torah, Deot 6:3', 'https://www.sefaria.org/Mishneh_Torah%2C_Deot.6.1', 'Guidelines for proper social behavior and relationships', 'הנחיות להתנהגות חברתית נאותה ויחסים', 'How do Rambam's social guidelines apply to modern relationship challenges?', 'כיצד ההנחיות החברתיות של הרמב"ם חלות על אתגרי יחסים מודרניים?', '["Lechem Mishneh", "Kesef Mishneh", "Radbaz"]', '["Social ethics", "Relationship building"]', true),
('Truth and Honesty', 'אמת ויושר', 'rambam', 'hilchot_deot', 35, 30, 40, 'intermediate', 'Mishneh Torah, Deot 2:6', 'Mishneh Torah, Deot 2:7', 'https://www.sefaria.org/Mishneh_Torah%2C_Deot.2.6', 'The imperative of truthfulness in speech and action', 'החובה של אמתיות בדיבור ובמעשה', 'When have you found it challenging to be completely truthful, and what did you learn from that experience?', 'מתי מצאת את זה מאתגר להיות אמתי לחלוטין, ומה למדת מהחוויה הזו?', '["Lechem Mishneh", "Kesef Mishneh", "Radbaz"]', '["Honesty cultivation", "Integrity development"]', true),
('Generosity Guidelines', 'הנחיות נדיבות', 'rambam', 'hilchot_deot', 40, 35, 45, 'advanced', 'Mishneh Torah, Deot 1:5', 'Mishneh Torah, Deot 1:7', 'https://www.sefaria.org/Mishneh_Torah%2C_Deot.1.5', 'Proper balance in giving and generosity', 'איזון נכון בנתינה ונדיבות', 'How can you ensure your generosity helps others without enabling dependency?', 'כיצד תוכל להבטיח שהנדיבות שלך עוזרת לאחרים מבלי ליצור תלות?', '["Lechem Mishneh", "Kesef Mishneh", "Radbaz"]', '["Ethical giving", "Wise generosity"]', true),
('Speech Ethics', 'אתיקה בדיבור', 'rambam', 'hilchot_deot', 12, 8, 18, 'beginner', 'Mishneh Torah, Deot 7:1', 'Mishneh Torah, Deot 7:3', 'https://www.sefaria.org/Mishneh_Torah%2C_Deot.7.1', 'Guidelines for proper and ethical speech', 'הנחיות לדיבור נכון ואתי', 'What words do you wish you could take back, and how can you speak more thoughtfully going forward?', 'אילו מילים היית רוצה לקחת בחזרה, וכיצד תוכל לדבר בצורה מחושבת יותר בהמשך?', '["Lechem Mishneh", "Kesef Mishneh", "Radbaz"]', '["Ethical communication", "Mindful speech"]', true),
('Personal Health', 'בריאות אישית', 'rambam', 'hilchot_deot', 45, 40, 50, 'intermediate', 'Mishneh Torah, Deot 4:1', 'Mishneh Torah, Deot 4:4', 'https://www.sefaria.org/Mishneh_Torah%2C_Deot.4.1', 'Rambam's approach to maintaining physical and mental health', 'גישת הרמב"ם לשמירה על בריאות גופנית ונפשית', 'How does taking care of your physical health serve your spiritual development?', 'כיצד דאגה לבריאות הגופנית משרתת את ההתפתחות הרוחנית שלך?', '["Lechem Mishneh", "Kesef Mishneh", "Radbaz"]', '["Holistic health", "Body-soul connection"]', true),
('Learning and Teaching', 'למידה והוראה', 'rambam', 'hilchot_deot', 50, 45, 55, 'advanced', 'Mishneh Torah, Deot 6:6', 'Mishneh Torah, Deot 6:8', 'https://www.sefaria.org/Mishneh_Torah%2C_Deot.6.6', 'The character traits needed for effective learning and teaching', 'תכונות האופי הדרושות ללמידה והוראה יעילות', 'What makes someone an effective teacher, and how can you cultivate those qualities?', 'מה הופך מישהו למורה יעיל, וכיצד תוכל לטפח את התכונות הללו?', '["Lechem Mishneh", "Kesef Mishneh", "Radbaz"]', '["Educational excellence", "Character-based teaching"]', true),
('Friendship Ethics', 'אתיקה בידידות', 'rambam', 'hilchot_deot', 28, 22, 35, 'intermediate', 'Mishneh Torah, Deot 6:2', 'Mishneh Torah, Deot 6:4', 'https://www.sefaria.org/Mishneh_Torah%2C_Deot.6.2', 'Guidelines for being a good friend and choosing friends wisely', 'הנחיות להיות חבר טוב ולבחור חברים בחוכמה', 'What qualities do you most value in a friend, and how well do you embody those qualities yourself?', 'אילו תכונות אתה הכי מעריך בחבר, ועד כמה אתה מגלם את התכונות הללו בעצמך?', '["Lechem Mishneh", "Kesef Mishneh", "Radbaz"]', '["Friendship wisdom", "Social character development"]', true),

-- Hilchot Teshuva (8 sources)
('Nature of Repentance', 'טבע התשובה', 'rambam', 'hilchot_teshuva', 18, 12, 25, 'beginner', 'Mishneh Torah, Teshuva 1:1', 'Mishneh Torah, Teshuva 1:3', 'https://www.sefaria.org/Mishneh_Torah%2C_Teshuva.1.1', 'Rambam defines the essential nature of teshuva', 'הרמב"ם מגדיר את הטבע החיוני של תשובה', 'What does genuine repentance feel like, and how is it different from mere regret?', 'איך מרגישה תשובה אמיתית, ובמה היא שונה מחרטה בלבד?', '["Lechem Mishneh", "Kesef Mishneh", "Radbaz"]', '["Repentance fundamentals", "Spiritual transformation"]', true),
('Steps of Teshuva', 'שלבי התשובה', 'rambam', 'hilchot_teshuva', 25, 20, 30, 'intermediate', 'Mishneh Torah, Teshuva 2:2', 'Mishneh Torah, Teshuva 2:4', 'https://www.sefaria.org/Mishneh_Torah%2C_Teshuva.2.2', 'The detailed process of complete repentance', 'התהליך המפורט של תשובה שלמה', 'Which step of teshuva do you find most challenging, and why?', 'איזה שלב בתשובה אתה מוצא הכי מאתגר, ולמה?', '["Lechem Mishneh", "Kesef Mishneh", "Radbaz"]', '["Teshuva methodology", "Personal transformation process"]', true),
('Confession Requirements', 'דרישות הוידוי', 'rambam', 'hilchot_teshuva', 22, 18, 28, 'intermediate', 'Mishneh Torah, Teshuva 1:1', 'Mishneh Torah, Teshuva 1:4', 'https://www.sefaria.org/Mishneh_Torah%2C_Teshuva.1.1', 'The proper form and requirements for confession', 'הצורה הנכונה והדרישות לוידוי', 'How does verbalizing wrongdoing change your relationship to your actions?', 'כיצד ביטוי מילולי של מעשה שגוי משנה את היחס שלך למעשיך?', '["Lechem Mishneh", "Kesef Mishneh", "Radbaz"]', '["Confession practices", "Verbal accountability"]', true),
('Return vs. Exchange', 'שבה נגד החזרה', 'rambam', 'hilchot_teshuva', 35, 30, 40, 'advanced', 'Mishneh Torah, Teshuva 7:3', 'Mishneh Torah, Teshuva 7:5', 'https://www.sefaria.org/Mishneh_Torah%2C_Teshuva.7.3', 'The difference between teshuva and mere behavioral exchange', 'ההבדל בין תשובה לשינוי התנהגותי בלבד', 'How do you know when you have truly changed versus just modified your behavior temporarily?', 'כיצד אתה יודע מתי השתנית באמת לעומת רק שינית את ההתנהגות זמנית?', '["Lechem Mishneh", "Kesef Mishneh", "Radbaz"]', '["Authentic change", "Deep vs. surface transformation"]', true),
('Love and Fear in Teshuva', 'אהבה ויראה בתשובה', 'rambam', 'hilchot_teshuva', 30, 25, 35, 'advanced', 'Mishneh Torah, Teshuva 10:1', 'Mishneh Torah, Teshuva 10:3', 'https://www.sefaria.org/Mishneh_Torah%2C_Teshuva.10.1', 'Different motivations for repentance and their effects', 'מוטיבציות שונות לתשובה והשפעותיהן', 'Is your spiritual growth motivated more by love or fear, and how does that affect your relationship with the Divine?', 'האם הצמיחה הרוחנית שלך מונעת יותר מאהבה או פחד, וכיצד זה משפיע על היחס שלך עם האלוקים?', '["Lechem Mishneh", "Kesef Mishneh", "Radbaz"]', '["Spiritual motivation", "Love vs. fear dynamics"]', true),
('Complete Teshuva', 'תשובה שלמה', 'rambam', 'hilchot_teshuva', 40, 35, 45, 'advanced', 'Mishneh Torah, Teshuva 2:1', 'Mishneh Torah, Teshuva 2:3', 'https://www.sefaria.org/Mishneh_Torah%2C_Teshuva.2.1', 'What constitutes complete and perfect repentance', 'מה מהווה תשובה שלמה ומושלמת', 'How would you recognize if you had achieved complete teshuva for a particular wrongdoing?', 'כיצד היית מזהה אם השגת תשובה שלמה על מעשה שגוי מסוים?', '["Lechem Mishneh", "Kesef Mishneh", "Radbaz"]', '["Perfect repentance", "Spiritual completeness"]', true),
('Teshuva and Time', 'תשובה וזמן', 'rambam', 'hilchot_teshuva', 45, 40, 50, 'intermediate', 'Mishneh Torah, Teshuva 3:14', 'Mishneh Torah, Teshuva 3:16', 'https://www.sefaria.org/Mishneh_Torah%2C_Teshuva.3.14', 'The relationship between teshuva and different life stages', 'היחס בין תשובה לשלבי חיים שונים', 'How has your capacity for teshuva changed as you have gotten older and gained more life experience?', 'כיצד השתנתה היכולת שלך לתשובה ככל שהתבגרת וצברת יותר ניסיון חיים?', '["Lechem Mishneh", "Kesef Mishneh", "Radbaz"]', '["Life stage spirituality", "Maturation in teshuva"]', true),
('Barriers to Teshuva', 'מכשולים לתשובה', 'rambam', 'hilchot_teshuva', 50, 45, 55, 'advanced', 'Mishneh Torah, Teshuva 4:1', 'Mishneh Torah, Teshuva 4:4', 'https://www.sefaria.org/Mishneh_Torah%2C_Teshuva.4.1', 'What prevents people from achieving genuine repentance', 'מה מונע מאנשים להשיג תשובה אמיתית', 'What personal or cultural barriers make teshuva most difficult for you?', 'אילו מכשולים אישיים או תרבותיים הופכים את התשובה לקשה ביותר עבורך?', '["Lechem Mishneh", "Kesef Mishneh", "Radbaz"]', '["Repentance obstacles", "Spiritual self-awareness"]', true),

-- Guide for the Perplexed (7 sources)
('Divine Knowledge', 'ידיעה אלוקית', 'rambam', 'guide_perplexed', 35, 30, 40, 'advanced', 'Guide for the Perplexed 3:20', 'Guide for the Perplexed 3:21', 'https://www.sefaria.org/Guide_for_the_Perplexed%2C_Part_3.20', 'Rambam explores how Divine knowledge differs from human knowledge', 'הרמב"ם חוקר כיצד הידיעה האלוקית שונה מהידיעה האנושית', 'How do you reconcile the limits of human understanding with faith in Divine wisdom?', 'כיצד אתה מיישב את גבולות ההבנה האנושית עם האמונה בחוכמה האלוקית?', '["Shem Tov", "Efodi", "Crescas"]', '["Divine attributes", "Epistemology and faith"]', true),
('Prophecy and Philosophy', 'נבואה ופילוסופיה', 'rambam', 'guide_perplexed', 40, 35, 45, 'advanced', 'Guide for the Perplexed 2:36', 'Guide for the Perplexed 2:37', 'https://www.sefaria.org/Guide_for_the_Perplexed%2C_Part_2.36', 'The relationship between prophetic knowledge and philosophical understanding', 'היחס בין ידע נבואי להבנה פילוסופית', 'How do you integrate rational thinking with spiritual intuition in your own understanding?', 'כיצד אתה משלב חשיבה רציונלית עם אינטואיציה רוחנית בהבנה שלך?', '["Shem Tov", "Efodi", "Crescas"]', '["Prophecy comprehension", "Reason and revelation"]', true),
('Creation vs. Eternity', 'בריאה נגד נצחיות', 'rambam', 'guide_perplexed', 45, 40, 50, 'advanced', 'Guide for the Perplexed 2:25', 'Guide for the Perplexed 2:26', 'https://www.sefaria.org/Guide_for_the_Perplexed%2C_Part_2.25', 'Rambam\'s analysis of whether the world was created or is eternal', 'ניתוח הרמב"ם האם העולם נברא או נצחי', 'What does it mean for your daily life whether the universe had a beginning or is eternal?', 'מה זה אומר לחיים היומיומיים שלך אם ליקום הייתה התחלה או שהוא נצחי?', '["Shem Tov", "Efodi", "Crescas"]', '["Cosmology and meaning", "Time and eternity concepts"]', true),
('Negative Theology', 'תיאולוגיה שלילית', 'rambam', 'guide_perplexed', 30, 25, 35, 'advanced', 'Guide for the Perplexed 1:58', 'Guide for the Perplexed 1:59', 'https://www.sefaria.org/Guide_for_the_Perplexed%2C_Part_1.58', 'Why we can only describe God by what God is not', 'מדוע אנו יכולים לתאר את האלוקים רק על ידי מה שהוא לא', 'How does the limitation of language affect your personal relationship with the Divine?', 'כיצד מגבלת השפה משפיעה על היחס האישי שלך עם האלוקים?', '["Shem Tov", "Efodi", "Crescas"]', '["Divine description limits", "Language and transcendence"]', true),
('Commandments\' Reasons', 'טעמי המצוות', 'rambam', 'guide_perplexed', 50, 45, 55, 'intermediate', 'Guide for the Perplexed 3:26', 'Guide for the Perplexed 3:28', 'https://www.sefaria.org/Guide_for_the_Perplexed%2C_Part_3.26', 'Rambam\'s explanation for the reasons behind commandments', 'הסברת הרמב"ם לטעמים מאחורי המצוות', 'Do you perform mitzvot differently when you understand their reasoning versus when you don\'t?', 'האם אתה מקיים מצוות בצורה שונה כשאתה מבין את הנימוק שלהן לעומת כשאתה לא?', '["Shem Tov", "Efodi", "Crescas"]', '["Mitzvah comprehension", "Rational religious observance"]', true),
('Providence and Free Will', 'השגחה ובחירה חופשית', 'rambam', 'guide_perplexed', 55, 50, 60, 'advanced', 'Guide for the Perplexed 3:17', 'Guide for the Perplexed 3:18', 'https://www.sefaria.org/Guide_for_the_Perplexed%2C_Part_3.17', 'How Divine providence works with human free choice', 'כיצד ההשגחה האלוקית פועלת עם הבחירה החופשית האנושית', 'How do you balance taking responsibility for your choices with trusting in Divine providence?', 'כיצד אתה מאזן בין נטילת אחריות על הבחירות שלך לביטחון בהשגחה אלוקית?', '["Shem Tov", "Efodi", "Crescas"]', '["Providence understanding", "Choice and destiny balance"]', true),
('Evil and Divine Goodness', 'רוע וטוב אלוקי', 'rambam', 'guide_perplexed', 38, 32, 45, 'advanced', 'Guide for the Perplexed 3:12', 'Guide for the Perplexed 3:13', 'https://www.sefaria.org/Guide_for_the_Perplexed%2C_Part_3.12', 'Rambam\'s approach to the problem of evil in a world created by a good God', 'גישת הרמב"ם לבעיית הרוע בעולם שנברא על ידי אלוקים טוב', 'How do you maintain faith in Divine goodness when confronted with suffering and evil?', 'כיצד אתה שומר על האמונה בטוב האלוקי כשאתה מתמודד עם סבל ורוע?', '["Shem Tov", "Efodi", "Crescas"]', '["Theodicy exploration", "Faith through suffering"]', true);

-- TANAKH SOURCES (30 total)
-- Weekly Portion (12 sources)
INSERT INTO sources (title, title_he, category, subcategory, estimated_time, min_time, max_time, difficulty_level, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, commentaries, learning_objectives, published) VALUES
('Creation and Human Purpose', 'בריאה ותכלית האדם', 'tanakh', 'weekly_portion', 20, 15, 25, 'beginner', 'Genesis 1:26', 'Genesis 1:28', 'https://www.sefaria.org/Genesis.1.26', 'The creation of humanity in God\'s image and the divine mandate', 'בריאת האדם בצלם אלוקים והמנדט האלוקי', 'What does it mean to you to be created "in the image of God" and how does this affect your daily choices?', 'מה זה אומר לך להיבראות "בצלם אלוקים" וכיצד זה משפיע על הבחירות היומיומיות שלך?', '["Rashi", "Ramban", "Ibn Ezra"]', '["Divine image understanding", "Human purpose exploration"]', true),
('Cain and Abel', 'קין והבל', 'tanakh', 'weekly_portion', 25, 20, 30, 'intermediate', 'Genesis 4:3', 'Genesis 4:8', 'https://www.sefaria.org/Genesis.4.3', 'The first brothers and the first murder', 'האחים הראשונים והרצח הראשון', 'How do jealousy and competition affect your relationships with siblings or close friends?', 'כיצד קנאה ותחרות משפיעות על היחסים שלך עם אחים או חברים קרובים?', '["Rashi", "Ramban", "Ibn Ezra"]', '["Sibling rivalry lessons", "Jealousy management"]', true),
('Abraham\'s Call', 'קריאת אברהם', 'tanakh', 'weekly_portion', 18, 12, 25, 'beginner', 'Genesis 12:1', 'Genesis 12:3', 'https://www.sefaria.org/Genesis.12.1', 'God\'s call to Abraham to leave his homeland', 'קריאת האלוקים לאברהם לעזוב את מולדתו', 'When have you had to leave your comfort zone for spiritual growth, and what did you learn?', 'מתי היית צריך לעזוב את אזור הנוחות שלך לצמיחה רוחנית, ומה למדת?', '["Rashi", "Ramban", "Ibn Ezra"]', '["Faith journeys", "Spiritual courage"]', true),
('Binding of Isaac', 'עקדת יצחק', 'tanakh', 'weekly_portion', 35, 30, 40, 'advanced', 'Genesis 22:1', 'Genesis 22:14', 'https://www.sefaria.org/Genesis.22.1', 'Abraham\'s ultimate test of faith', 'המבחן האולטימטיבי של אברהם באמונה', 'How do you respond when your deepest values seem to conflict with what you believe God is asking of you?', 'כיצד אתה מגיב כשהערכים העמוקים ביותר שלך נראים מתנגשים עם מה שאתה מאמין שהאלוקים מבקש ממך?', '["Rashi", "Ramban", "Ibn Ezra"]', '["Ultimate sacrifice", "Faith testing"]', true),
('Jacob\'s Dream', 'חלום יעקב', 'tanakh', 'weekly_portion', 22, 18, 28, 'intermediate', 'Genesis 28:10', 'Genesis 28:17', 'https://www.sefaria.org/Genesis.28.10', 'Jacob\'s ladder and divine encounter', 'סולם יעקב והפגישה האלוקית', 'When have you felt most connected to the Divine, and what was that experience like?', 'מתי הרגשת הכי מחובר לאלוקים, ואיך הייתה החוויה הזו?', '["Rashi", "Ramban", "Ibn Ezra"]', '["Divine encounters", "Spiritual awakening"]', true),
('Joseph\'s Forgiveness', 'סליחת יוסף', 'tanakh', 'weekly_portion', 30, 25, 35, 'intermediate', 'Genesis 45:4', 'Genesis 45:8', 'https://www.sefaria.org/Genesis.45.4', 'Joseph reveals himself and forgives his brothers', 'יוסף מגלה את עצמו וסולח לאחיו', 'How do you find the strength to forgive someone who has deeply hurt you?', 'כיצד אתה מוצא את הכוח לסלוח למישהו שפגע בך עמוקות?', '["Rashi", "Ramban", "Ibn Ezra"]', '["Forgiveness power", "Sibling reconciliation"]', true),
('Burning Bush', 'הסנה הבוער', 'tanakh', 'weekly_portion', 28, 22, 35, 'intermediate', 'Exodus 3:2', 'Exodus 3:6', 'https://www.sefaria.org/Exodus.3.2', 'Moses encounters God at the burning bush', 'משה פוגש את האלוקים בסנה הבוער', 'What "burning bushes" - moments of unexpected divine presence - have you experienced in your life?', 'אילו "סנים בוערים" - רגעים של נוכחות אלוקית בלתי צפויה - חווית בחייך?', '["Rashi", "Ramban", "Ibn Ezra"]', '["Divine calling", "Leadership reluctance"]', true),
('Ten Commandments', 'עשרת הדברות', 'tanakh', 'weekly_portion', 40, 35, 45, 'beginner', 'Exodus 20:1', 'Exodus 20:14', 'https://www.sefaria.org/Exodus.20.1', 'The giving of the Ten Commandments at Sinai', 'מתן עשרת הדברות בסיני', 'Which of the Ten Commandments do you find most challenging to observe in modern life?', 'איזה מעשרת הדברות אתה מוצא הכי מאתגר לקיים בחיים המודרניים?', '["Rashi", "Ramban", "Ibn Ezra"]', '["Fundamental ethics", "Divine law comprehension"]', true),
('Golden Calf', 'עגל הזהב', 'tanakh', 'weekly_portion', 45, 40, 50, 'advanced', 'Exodus 32:1', 'Exodus 32:6', 'https://www.sefaria.org/Exodus.32.1', 'The sin of the golden calf and its aftermath', 'חטא עגל הזהב והשלכותיו', 'What are the "golden calves" in your life - things that compete with your spiritual focus?', 'מה הם "עגלי הזהב" בחייך - דברים שמתחרים עם המיקוד הרוחני שלך?', '["Rashi", "Ramban", "Ibn Ezra"]', '["Idolatry recognition", "Spiritual priorities"]', true),
('Spies Report', 'דוח המרגלים', 'tanakh', 'weekly_portion', 32, 28, 38, 'intermediate', 'Numbers 13:25', 'Numbers 13:33', 'https://www.sefaria.org/Numbers.13.25', 'The report of the spies and the people\'s reaction', 'דוח המרגלים ותגובת העם', 'How do fear and doubt prevent you from pursuing goals that you know are worthwhile?', 'כיצד פחד וספק מונעים ממך לרדוף אחרי מטרות שאתה יודע שהן כדאיות?', '["Rashi", "Ramban", "Ibn Ezra"]', '["Overcoming fear", "Faith vs. doubt"]', true),
('Shema Declaration', 'הצהרת שמע', 'tanakh', 'weekly_portion', 15, 10, 20, 'beginner', 'Deuteronomy 6:4', 'Deuteronomy 6:7', 'https://www.sefaria.org/Deuteronomy.6.4', 'The central declaration of Jewish faith', 'ההצהרה המרכזית של האמונה היהודית', 'How does declaring "God is One" impact the way you see unity and division in the world?', 'כיצד הצהרת "האלוקים אחד" משפיעה על הדרך שבה אתה רואה אחדות וחלוקה בעולם?', '["Rashi", "Ramban", "Ibn Ezra"]', '["Unity concepts", "Faith declaration"]', true),
('Moses\' Final Blessing', 'ברכת משה האחרונה', 'tanakh', 'weekly_portion', 50, 45, 55, 'advanced', 'Deuteronomy 33:1', 'Deuteronomy 33:5', 'https://www.sefaria.org/Deuteronomy.33.1', 'Moses blesses the tribes before his death', 'משה מברך את השבטים לפני מותו', 'What legacy do you hope to leave, and how are you building that legacy now?', 'איזו מורשת אתה מקווה להשאיר, וכיצד אתה בונה את המורשת הזו עכשיו?', '["Rashi", "Ramban", "Ibn Ezra"]', '["Legacy building", "Leadership transition"]', true),

-- Prophets (10 sources)
('Isaiah\'s Vision', 'חזון ישעיהו', 'tanakh', 'prophets', 25, 20, 30, 'intermediate', 'Isaiah 6:1', 'Isaiah 6:8', 'https://www.sefaria.org/Isaiah.6.1', 'Isaiah\'s prophetic calling and vision of God', 'קריאתו הנבואית של ישעיהו וחזון האלוקים', 'When have you felt overwhelmed by a sense of purpose or calling in your life?', 'מתי הרגשת המום מתחושת מטרה או קריאה בחייך?', '["Rashi", "Radak", "Metzudat David"]', '["Prophetic calling", "Divine vision"]', true),
('Comfort My People', 'נחמו עמי', 'tanakh', 'prophets', 20, 15, 25, 'beginner', 'Isaiah 40:1', 'Isaiah 40:5', 'https://www.sefaria.org/Isaiah.40.1', 'God\'s message of comfort to the exiled people', 'מסר הנחמה של האלוקים לעם הגולה', 'How do you find comfort and hope during your most difficult times?', 'כיצד אתה מוצא נחמה ותקווה בזמנים הקשים ביותר שלך?', '["Rashi", "Radak", "Metzudat David"]', '["Divine comfort", "Hope in exile"]', true),
('Jeremiah\'s Call', 'קריאת ירמיהו', 'tanakh', 'prophets', 30, 25, 35, 'intermediate', 'Jeremiah 1:4', 'Jeremiah 1:10', 'https://www.sefaria.org/Jeremiah.1.4', 'Jeremiah\'s reluctant acceptance of his prophetic mission', 'קבלתו הסרבנית של ירמיהו את שליחותו הנבואית', 'What responsibilities do you try to avoid, and why do you think you resist them?', 'מאילו אחריויות אתה מנסה להתחמק, ולמה אתה חושב שאתה מתנגד להן?', '["Rashi", "Radak", "Metzudat David"]', '["Reluctant leadership", "Divine appointment"]', true),
('Ezekiel\'s Vision', 'חזון יחזקאל', 'tanakh', 'prophets', 40, 35, 45, 'advanced', 'Ezekiel 1:4', 'Ezekiel 1:12', 'https://www.sefaria.org/Ezekiel.1.4', 'Ezekiel\'s mystical vision of the divine chariot', 'החזון המיסטי של יחזקאל על המרכבה האלוקית', 'How do you make sense of spiritual experiences that seem beyond ordinary understanding?', 'כיצד אתה מבין חוויות רוחניות שנראות מעבר להבנה רגילה?', '["Rashi", "Radak", "Metzudat David"]', '["Mystical experience", "Divine complexity"]', true),
('Hosea\'s Marriage', 'נישואי הושע', 'tanakh', 'prophets', 35, 30, 40, 'advanced', 'Hosea 1:2', 'Hosea 1:6', 'https://www.sefaria.org/Hosea.1.2', 'Hosea\'s marriage as metaphor for God\'s relationship with Israel', 'נישואי הושע כמטפורה ליחס האלוקים עם ישראל', 'How do human relationships help you understand divine love and commitment?', 'כיצד יחסים אנושיים עוזרים לך להבין אהבה והתחייבות אלוקיות?', '["Rashi", "Radak", "Metzudat David"]', '["Divine relationship metaphors", "Covenant understanding"]', true),
('Jonah\'s Flight', 'בריחת יונה', 'tanakh', 'prophets', 28, 22, 35, 'intermediate', 'Jonah 1:1', 'Jonah 1:6', 'https://www.sefaria.org/Jonah.1.1', 'Jonah attempts to flee from his divine mission', 'יונה מנסה לברוח משליחותו האלוקית', 'When have you tried to run away from something you knew you needed to do?', 'מתי ניסית לברוח ממשהו שידעת שאתה צריך לעשות?', '["Rashi", "Radak", "Metzudat David"]', '["Avoiding responsibility", "Divine pursuit"]', true),
('Micah\'s Justice', 'צדק מיכה', 'tanakh', 'prophets', 22, 18, 28, 'intermediate', 'Micah 6:6', 'Micah 6:8', 'https://www.sefaria.org/Micah.6.6', 'What does God require: justice, mercy, and walking humbly', 'מה דורש האלוקים: צדק, רחמים והליכה בצניעות', 'How do you balance the demands of justice with the call for mercy in your daily decisions?', 'כיצד אתה מאזן בין דרישות הצדק לקריאה לרחמים בהחלטות היומיומיות שלך?', '["Rashi", "Radak", "Metzudat David"]', '["Justice and mercy", "Humble walking"]', true),
('Malachi\'s Rebuke', 'תוכחת מלאכי', 'tanakh', 'prophets', 26, 20, 32, 'intermediate', 'Malachi 1:6', 'Malachi 1:10', 'https://www.sefaria.org/Malachi.1.6', 'Malachi rebukes the people for empty religious observance', 'מלאכי מוכיח את העם על קיום דתי ריק', 'How do you ensure your religious practices remain meaningful rather than just routine?', 'כיצד אתה מוודא שהפרקטיקות הדתיות שלך נשארות משמעותיות ולא רק שגרתיות?', '["Rashi", "Radak", "Metzudat David"]', '["Authentic worship", "Religious sincerity"]', true),
('Amos\' Justice', 'צדק עמוס', 'tanakh', 'prophets', 32, 28, 38, 'intermediate', 'Amos 5:21', 'Amos 5:24', 'https://www.sefaria.org/Amos.5.21', 'Amos demands justice over ritual observance', 'עמוס דורש צדק על פני קיום טקסים', 'When does religious observance become a substitute for ethical behavior rather than inspiring it?', 'מתי קיום דתי הופך למחליף להתנהגות אתית במקום להשריש אותה?', '["Rashi", "Radak", "Metzudat David"]', '["Social justice priority", "Ritual vs. ethics"]', true),
('Habakkuk\'s Questions', 'שאלות חבקוק', 'tanakh', 'prophets', 38, 32, 45, 'advanced', 'Habakkuk 1:2', 'Habakkuk 1:6', 'https://www.sefaria.org/Habakkuk.1.2', 'Habakkuk questions God about justice and suffering', 'חבקוק שואל את האלוקים על צדק וסבל', 'How do you maintain faith when you see injustice seemingly going unpunished?', 'כיצד אתה שומר על אמונה כשאתה רואה אי-צדק שלכאורה לא נענש?', '["Rashi", "Radak", "Metzudat David"]', '["Questioning faith", "Divine justice mysteries"]', true),

-- Writings (8 sources)
('Psalms of Praise', 'תהילים של שבח', 'tanakh', 'writings', 15, 10, 20, 'beginner', 'Psalms 150:1', 'Psalms 150:6', 'https://www.sefaria.org/Psalms.150.1', 'King David\'s call to praise God with all instruments', 'קריאתו של דוד המלך לשבח את האלוקים בכל הכלים', 'What moves you to feel most grateful and full of praise in your daily life?', 'מה גורם לך להרגיש הכי אסיר תודה ומלא שבח בחיים היומיומיים שלך?', '["Rashi", "Radak", "Metzudat David"]', '["Gratitude expression", "Worship diversity"]', true),
('Job\'s Suffering', 'סבל איוב', 'tanakh', 'writings', 45, 40, 50, 'advanced', 'Job 1:8', 'Job 1:12', 'https://www.sefaria.org/Job.1.8', 'Job\'s initial trial and his response to loss', 'המבחן הראשוני של איוב ותגובתו לאובדן', 'How do you maintain faith and integrity when everything seems to be going wrong?', 'כיצד אתה שומר על אמונה ויושרה כשנראה שהכל משתבש?', '["Rashi", "Radak", "Metzudat David"]', '["Suffering theology", "Faith under trial"]', true),
('Ecclesiastes\' Wisdom', 'חוכמת קהלת', 'tanakh', 'writings', 30, 25, 35, 'intermediate', 'Ecclesiastes 3:1', 'Ecclesiastes 3:8', 'https://www.sefaria.org/Ecclesiastes.3.1', 'A time for everything under heaven', 'עת לכל חפץ תחת השמים', 'How do you find meaning and purpose in the seemingly cyclical nature of life?', 'כיצד אתה מוצא משמעות ומטרה בטבע המחזורי לכאורה של החיים?', '["Rashi", "Radak", "Metzudat David"]', '["Life\'s seasons", "Meaning in temporality"]', true),
('Proverbs\' Advice', 'עצות משלי', 'tanakh', 'writings', 20, 15, 25, 'beginner', 'Proverbs 3:5', 'Proverbs 3:8', 'https://www.sefaria.org/Proverbs.3.5', 'Trust in God with all your heart', 'בטח באלוקים בכל לבך', 'When do you find it hardest to trust in God rather than relying solely on your own understanding?', 'מתי אתה מוצא הכי קשה לבטוח באלוקים במקום להסתמך רק על ההבנה שלך?', '["Rashi", "Radak", "Metzudat David"]', '["Trust development", "Wisdom vs. understanding"]', true),
('Song of Songs\' Love', 'אהבת שיר השירים', 'tanakh', 'writings', 35, 30, 40, 'advanced', 'Song of Songs 2:10', 'Song of Songs 2:13', 'https://www.sefaria.org/Song_of_Songs.2.10', 'The beloved calls: arise, my love, and come away', 'הקורא הקרוב: קומי לך רעייתי', 'How do you experience the connection between human love and divine love?', 'כיצד אתה חווה את הקשר בין אהבה אנושית לאהבה אלוקית?', '["Rashi", "Radak", "Ibn Ezra"]', '["Love mysticism", "Divine-human intimacy"]', true),
('Ruth\'s Loyalty', 'נאמנות רות', 'tanakh', 'writings', 25, 20, 30, 'intermediate', 'Ruth 1:16', 'Ruth 1:17', 'https://www.sefaria.org/Ruth.1.16', 'Ruth\'s declaration of loyalty to Naomi', 'הצהרת הנאמנות של רות לנעמי', 'What relationships in your life are worth maintaining even when it requires significant sacrifice?', 'אילו יחסים בחייך שווים שמירה גם כשזה דורש הקרבה משמעותית?', '["Rashi", "Radak", "Metzudat David"]', '["Loyalty demonstration", "Conversion commitment"]', true),
('Esther\'s Courage', 'אומץ אסתר', 'tanakh', 'writings', 40, 35, 45, 'intermediate', 'Esther 4:13', 'Esther 4:16', 'https://www.sefaria.org/Esther.4.13', 'Esther\'s decision to risk her life for her people', 'החלטתה של אסתר לסכן את חייה למען עמה', 'When have you had to choose between personal safety and standing up for what\'s right?', 'מתי היית צריך לבחור בין בטיחות אישית לעמידה על מה שנכון?', '["Rashi", "Radak", "Metzudat David"]', '["Moral courage", "Personal risk for others"]', true),
('Daniel\'s Faith', 'אמונת דניאל', 'tanakh', 'writings', 50, 45, 55, 'advanced', 'Daniel 6:11', 'Daniel 6:17', 'https://www.sefaria.org/Daniel.6.11', 'Daniel continues praying despite the king\'s decree', 'דניאל ממשיך להתפלל למרות גזירת המלך', 'How do you maintain your religious practices when they conflict with social or legal pressures?', 'כיצד אתה שומר על הפרקטיקות הדתיות שלך כשהן מתנגשות עם לחצים חברתיים או משפטיים?', '["Rashi", "Radak", "Metzudat David"]', '["Religious courage", "Faith under persecution"]', true);

-- TALMUD SOURCES (25 total)
-- Pirkei Avot (12 sources)
INSERT INTO sources (title, title_he, category, subcategory, estimated_time, min_time, max_time, difficulty_level, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, commentaries, learning_objectives, published) VALUES
('Three Pillars', 'שלושה עמודים', 'talmud', 'pirkei_avot', 18, 12, 25, 'beginner', 'Avot 1:2', 'Avot 1:2', 'https://www.sefaria.org/Pirkei_Avot.1.2', 'The world stands on three things: Torah, service, and acts of kindness', 'על שלושה דברים העולם עומד: על התורה, ועל העבודה, ועל גמילות חסדים', 'How do you balance Torah study, prayer/service, and acts of kindness in your daily life?', 'כיצד אתה מאזן בין לימוד תורה, תפילה/עבודה ומעשי חסד בחיים היומיומיים שלך?', '["Rashi", "Rambam", "Ruach Chaim"]', '["Foundational values", "Life balance"]', true),
('Say Little, Do Much', 'אמור מעט ועשה הרבה', 'talmud', 'pirkei_avot', 15, 10, 20, 'beginner', 'Avot 1:15', 'Avot 1:15', 'https://www.sefaria.org/Pirkei_Avot.1.15', 'Shammai teaches: Say little and do much', 'שמאי אומר: אמור מעט ועשה הרבה', 'How can you better align your actions with your words and promises?', 'כיצד תוכל ליישר טוב יותר את המעשים שלך עם המילים וההבטחות שלך?', '["Rashi", "Rambam", "Ruach Chaim"]', '["Action over words", "Promise keeping"]', true),
('Who is Wise?', 'איזהו חכם?', 'talmud', 'pirkei_avot', 22, 18, 28, 'intermediate', 'Avot 4:1', 'Avot 4:1', 'https://www.sefaria.org/Pirkei_Avot.4.1', 'Who is wise? One who learns from every person', 'איזהו חכם? הלומד מכל אדם', 'What have you learned recently from someone you wouldn\'t normally consider a teacher?', 'מה למדת לאחרונה ממישהו שבדרך כלל לא היית רואה כמורה?', '["Rashi", "Rambam", "Ruach Chaim"]', '["Wisdom sources", "Continuous learning"]', true),
('Judge Favorably', 'דן לכף זכות', 'talmud', 'pirkei_avot', 20, 15, 25, 'intermediate', 'Avot 1:6', 'Avot 1:6', 'https://www.sefaria.org/Pirkei_Avot.1.6', 'Judge every person favorably', 'והוי דן את כל האדם לכף זכות', 'When was the last time you gave someone the benefit of the doubt, and how did it affect the situation?', 'מתי בפעם האחרונה נתת למישהו את ההכרעה לטובה, וכיצד זה השפיע על המצב?', '["Rashi", "Rambam", "Ruach Chaim"]', '["Positive judgment", "Benefit of doubt"]', true),
('Time for Torah', 'עת לתורה', 'talmud', 'pirkei_avot', 25, 20, 30, 'intermediate', 'Avot 2:5', 'Avot 2:5', 'https://www.sefaria.org/Pirkei_Avot.2.5', 'In a place where there are no menschen, strive to be a mensch', 'במקום שאין אנשים, השתדל להיות איש', 'When have you had to step up and take responsibility because no one else would?', 'מתי היית צריך לקחת על עצמך ולקחת אחריות כי אף אחד אחר לא היה עושה זאת?', '["Rashi", "Rambam", "Ruach Chaim"]', '["Leadership initiative", "Personal responsibility"]', true),
('Torah and Work', 'תורה ומלאכה', 'talmud', 'pirkei_avot', 30, 25, 35, 'intermediate', 'Avot 2:2', 'Avot 2:2', 'https://www.sefaria.org/Pirkei_Avot.2.2', 'Torah study with worldly occupation prevents sin', 'יפה תלמוד תורה עם דרך ארץ', 'How do you integrate spiritual values into your professional or work life?', 'כיצד אתה משלב ערכים רוחניים בחיים המקצועיים או העבודה שלך?', '["Rashi", "Rambam", "Ruach Chaim"]', '["Work-study balance", "Integrated living"]', true),
('Against Your Will', 'בעל כרחך', 'talmud', 'pirkei_avot', 35, 30, 40, 'advanced', 'Avot 4:22', 'Avot 4:22', 'https://www.sefaria.org/Pirkei_Avot.4.22', 'Against your will you were born, against your will you die', 'בעל כרחך אתה נולד ובעל כרחך אתה מת', 'How does recognizing the involuntary nature of birth and death change your perspective on life choices?', 'כיצד הכרה בטבע הלא-רצוני של הלידה והמוות משנה את נקודת המבט שלך על בחירות החיים?', '["Rashi", "Rambam", "Ruach Chaim"]', '["Life acceptance", "Choice within limits"]', true),
('Age and Wisdom', 'גיל וחוכמה', 'talmud', 'pirkei_avot', 28, 22, 35, 'intermediate', 'Avot 5:21', 'Avot 5:21', 'https://www.sefaria.org/Pirkei_Avot.5.21', 'Different ages bring different capacities and responsibilities', 'גילים שונים מביאים יכולות ואחריויות שונות', 'How has your understanding of responsibility and wisdom changed as you\'ve gotten older?', 'כיצד השתנתה ההבנה שלך של אחריות וחוכמה ככל שהתבגרת?', '["Rashi", "Rambam", "Ruach Chaim"]', '["Life stages", "Age-appropriate wisdom"]', true),
('Rich in Content', 'עשיר בתוכן', 'talmud', 'pirkei_avot', 32, 28, 38, 'intermediate', 'Avot 4:1', 'Avot 4:1', 'https://www.sefaria.org/Pirkei_Avot.4.1', 'Who is rich? One who is satisfied with their portion', 'איזהו עשיר? השמח בחלקו', 'What does it mean to be "satisfied with your portion" in a culture that encourages constant improvement?', 'מה זה אומר להיות "שמח בחלקו" בתרבות שמעודדת שיפור מתמיד?', '["Rashi", "Rambam", "Ruach Chaim"]', '["Contentment cultivation", "True wealth"]', true),
('World to Come', 'עולם הבא', 'talmud', 'pirkei_avot', 40, 35, 45, 'advanced', 'Avot 4:17', 'Avot 4:17', 'https://www.sefaria.org/Pirkei_Avot.4.17', 'Better one hour of repentance in this world than all of the world to come', 'יפה שעה אחת בתשובה ומעשים טובים בעולם הזה מכל חיי העולם הבא', 'How does belief in an afterlife affect your priorities and actions in this life?', 'כיצד אמונה בחיים שלאחר המוות משפיעה על הסדרי העדיפויות והמעשים שלך בחיים האלה?', '["Rashi", "Rambam", "Ruach Chaim"]', '["Afterlife perspective", "Present moment value"]', true),
('Study Method', 'שיטת לימוד', 'talmud', 'pirkei_avot', 24, 18, 30, 'intermediate', 'Avot 6:6', 'Avot 6:6', 'https://www.sefaria.org/Pirkei_Avot.6.6', 'Torah is acquired through 48 ways', 'בארבעים ושמונה דברים נקנית התורה', 'Which methods of learning work best for you, and how do you cultivate effective study habits?', 'אילו שיטות למידה עובדות הכי טוב עבורך, וכיצד אתה מטפח הרגלי לימוד יעילים?', '["Rashi", "Rambam", "Ruach Chaim"]', '["Learning methodology", "Study habits"]', true),
('Honor and Crown', 'כבוד וכתר', 'talmud', 'pirkei_avot', 45, 40, 50, 'advanced', 'Avot 4:13', 'Avot 4:13', 'https://www.sefaria.org/Pirkei_Avot.4.13', 'The crown of Torah surpasses the crown of priesthood and kingship', 'כתר תורה גדול מכתר כהונה ומכתר מלכות', 'How do you pursue recognition and honor in your life, and what forms of honor do you value most?', 'כיצד אתה רודף אחרי הכרה וכבוד בחייך, ואילו צורות של כבוד אתה הכי מעריך?', '["Rashi", "Rambam", "Ruach Chaim"]', '["True honor", "Merit hierarchy"]', true),

-- Berakhot (8 sources)
('Blessings Awareness', 'מודעות לברכות', 'talmud', 'berakhot', 20, 15, 25, 'beginner', 'Berakhot 35a', 'Berakhot 35a', 'https://www.sefaria.org/Berakhot.35a', 'It is forbidden to benefit from this world without a blessing', 'אסור לו לאדם שיהנה מן העולם הזה בלא ברכה', 'How does saying blessings change your awareness of daily pleasures and necessities?', 'כיצד אמירת ברכות משנה את המודעות שלך להנאות ולצרכים יומיומיים?', '["Rashi", "Tosafot", "Maharsha"]', '["Blessing consciousness", "Gratitude practice"]', true),
('Prayer Concentration', 'כוונה בתפילה', 'talmud', 'berakhot', 25, 20, 30, 'intermediate', 'Berakhot 31a', 'Berakhot 31a', 'https://www.sefaria.org/Berakhot.31a', 'One should not pray except with a heavy heart', 'אין אדם מתפלל אלא מתוך כובד ראש', 'What helps you achieve the right mindset and concentration for meaningful prayer?', 'מה עוזר לך להשיג את המחשבה וריכוז הנכונים לתפילה משמעותית?', '["Rashi", "Tosafot", "Maharsha"]', '["Prayer focus", "Spiritual preparation"]', true),
('Morning Blessings', 'ברכות השחר', 'talmud', 'berakhot', 30, 25, 35, 'intermediate', 'Berakhot 60b', 'Berakhot 60b', 'https://www.sefaria.org/Berakhot.60b', 'The series of blessings recited upon waking', 'סדרת הברכות הנאמרות בהתעוררות', 'How do morning blessings help you transition from sleep to conscious, purposeful living?', 'כיצד ברכות השחר עוזרות לך לעבור משינה לחיים מודעים ומכוונים?', '["Rashi", "Tosafot", "Maharsha"]', '["Morning consciousness", "Daily spiritual awakening"]', true),
('Dream Interpretation', 'פתרון חלומות', 'talmud', 'berakhot', 35, 30, 40, 'advanced', 'Berakhot 55b', 'Berakhot 55b', 'https://www.sefaria.org/Berakhot.55b', 'Dreams follow their interpretation', 'חלום הולך אחר הפתרון', 'How do you interpret the meaningful dreams or recurring themes in your sleep, and what do they tell you about your concerns?', 'כיצד אתה מפרש את החלומות המשמעותיים או הנושאים החוזרים בשינה שלך, ומה הם אומרים לך על הדאגות שלך?', '["Rashi", "Tosafot", "Maharsha"]', '["Dream wisdom", "Subconscious insight"]', true),
('Mezuzah Protection', 'הגנת המזוזה', 'talmud', 'berakhot', 22, 18, 28, 'intermediate', 'Berakhot 15b', 'Berakhot 15b', 'https://www.sefaria.org/Berakhot.15b', 'The mezuzah protects both inside and outside the house', 'המזוזה שומרת על הבית מבפנים ומבחוץ', 'How do physical objects like mezuzot create spiritual awareness in your living space?', 'כיצד חפצים פיזיים כמו מזוזות יוצרים מודעות רוחנית במרחב המגורים שלך?', '["Rashi", "Tosafot", "Maharsha"]', '["Sacred space", "Physical-spiritual connection"]', true),
('Shema Timing', 'זמני קריאת שמע', 'talmud', 'berakhot', 28, 22, 35, 'intermediate', 'Berakhot 9b', 'Berakhot 9b', 'https://www.sefaria.org/Berakhot.9b', 'The proper times for reciting the Shema', 'הזמנים הנכונים לקריאת שמע', 'How does saying Shema at specific times create a rhythm of consciousness throughout your day?', 'כיצד אמירת שמע בזמנים מסוימים יוצרת קצב של מודעות לאורך היום שלך?', '["Rashi", "Tosafot", "Maharsha"]', '["Time sanctification", "Daily spiritual rhythm"]', true),
('Torah as Antidote', 'תורה כתרופה', 'talmud', 'berakhot', 40, 35, 45, 'advanced', 'Berakhot 5a', 'Berakhot 5a', 'https://www.sefaria.org/Berakhot.5a', 'Torah study is an antidote to suffering', 'תורה תרופה ליצר הרע', 'How does learning and intellectual engagement help you deal with emotional or spiritual difficulties?', 'כיצד למידה ומעורבות אינטלקטואלית עוזרות לך להתמודד עם קשיים רגשיים או רוחניים?', '["Rashi", "Tosafot", "Maharsha"]', '["Torah therapy", "Learning as healing"]', true),
('Hospitality Priority', 'עדיפות האכסון', 'talmud', 'berakhot', 45, 40, 50, 'intermediate', 'Berakhot 63b', 'Berakhot 63b', 'https://www.sefaria.org/Berakhot.63b', 'Welcoming guests is greater than welcoming the Divine Presence', 'גדולה הכנסת אורחים מהקבלת פני שכינה', 'How do you balance time for spiritual practices with time for helping and hosting others?', 'כיצד אתה מאזן זמן לפרקטיקות רוחניות עם זמן לעזרה ואירוח אחרים?', '["Rashi", "Tosafot", "Maharsha"]', '["Hospitality vs. worship", "Social priorities"]', true),

-- Various Sugyot (5 sources)
('Hillel\'s Patience', 'סבלנות הלל', 'talmud', 'various_sugyot', 25, 20, 30, 'intermediate', 'Shabbat 31a', 'Shabbat 31a', 'https://www.sefaria.org/Shabbat.31a', 'The whole Torah while standing on one foot', 'כל התורה כולה על רגל אחת', 'How do you explain your core values and beliefs in simple terms to someone who disagrees with you?', 'כיצד אתה מסביר את הערכים והאמונות המרכזיות שלך במילים פשוטות למישהו שלא מסכים איתך?', '["Rashi", "Tosafot", "Maharsha"]', '["Essential teachings", "Patience in education"]', true),
('Charity Levels', 'דרגות צדקה', 'talmud', 'various_sugyot', 35, 30, 40, 'advanced', 'Bava Batra 9a', 'Bava Batra 9a', 'https://www.sefaria.org/Bava_Batra.9a', 'Different levels and types of charitable giving', 'דרגות וסוגים שונים של נתינת צדקה', 'How do you decide between different charitable causes and what criteria do you use for giving?', 'כיצד אתה מחליט בין מטרות צדקה שונות ואילו קריטריונים אתה משתמש לנתינה?', '["Rashi", "Tosafot", "Maharsha"]', '["Charity wisdom", "Giving strategy"]', true),
('Gossip Damage', 'נזק לשון הרע', 'talmud', 'various_sugyot', 30, 25, 35, 'intermediate', 'Arachin 15b', 'Arachin 15b', 'https://www.sefaria.org/Arachin.15b', 'Gossip kills three people: the speaker, listener, and subject', 'לשון הרע הורגת שלושה: האומר, הקבל, והנאמר עליו', 'How do you handle situations where others want to share negative information about someone you know?', 'כיצד אתה מתמודד עם מצבים שבהם אחרים רוצים לחלוק מידע שלילי על מישהו שאתה מכיר?', '["Rashi", "Tosafot", "Maharsha"]', '["Speech ethics", "Communication responsibility"]', true),
('Partnership with God', 'שותפות עם האלוקים', 'talmud', 'various_sugyot', 40, 35, 45, 'advanced', 'Shabbat 10a', 'Shabbat 10a', 'https://www.sefaria.org/Shabbat.10a', 'When judges judge truly, they become partners with God in creation', 'כשדיינים דנים דין אמת נעשים שותפים בבריאה', 'How do you see your daily decisions and judgments as participating in divine creation and justice?', 'כיצד אתה רואה את ההחלטות והשיפוטים היומיומיים שלך כהשתתפות בבריאה ובצדק האלוקיים?', '["Rashi", "Tosafot", "Maharsha"]', '["Divine partnership", "Justice responsibility"]', true),
('Study Partnership', 'שותפות לימוד', 'talmud', 'various_sugyot', 20, 15, 25, 'beginner', 'Taanit 7a', 'Taanit 7a', 'https://www.sefaria.org/Taanit.7a', 'Much have I learned from my teachers, more from my colleagues', 'הרבה למדתי מרבותי, יותר מחברי', 'Who are your most effective learning partners and what makes those relationships productive?', 'מי הם השותפים הכי יעילים ללמידה שלך ומה הופך את היחסים האלה לפרודוקטיביים?', '["Rashi", "Tosafot", "Maharsha"]', '["Learning relationships", "Peer education"]', true);

-- SPIRITUAL SOURCES (25 total)
-- Mussar (10 sources)
INSERT INTO sources (title, title_he, category, subcategory, estimated_time, min_time, max_time, difficulty_level, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, commentaries, learning_objectives, published) VALUES
('Soul Traits', 'מידות הנפש', 'spiritual', 'mussar', 25, 20, 30, 'intermediate', 'Duties of Hearts 1:1', 'Duties of Hearts 1:2', 'https://www.sefaria.org/Duties_of_the_Heart%2C_Introduction.1', 'The fundamental character traits that require cultivation', 'תכונות האופי הבסיסיות הדורשות טיפוח', 'Which character trait do you most need to work on, and what specific steps can you take?', 'איזו תכונת אופי אתה הכי צריך לעבוד עליה, ואילו צעדים ספציפיים אתה יכול לנקוט?', '["Gates of Repentance", "Path of the Just", "Duties of Hearts"]', '["Character development", "Soul refinement"]', true),
('Fear and Love', 'יראה ואהבה', 'spiritual', 'mussar', 30, 25, 35, 'advanced', 'Duties of Hearts 10:1', 'Duties of Hearts 10:3', 'https://www.sefaria.org/Duties_of_the_Heart%2C_The_Gate_of_the_Love_of_God.1', 'Balancing fear and love in spiritual service', 'איזון יראה ואהבה בעבודה רוחנית', 'How do you experience the balance between reverence and love in your spiritual life?', 'כיצד אתה חווה את האיזון בין יראה ואהבה בחיים הרוחניים שלך?', '["Gates of Repentance", "Path of the Just", "Duties of Hearts"]', '["Spiritual emotions", "Divine relationship"]', true),
('Humility Practice', 'תרגול ענווה', 'spiritual', 'mussar', 20, 15, 25, 'intermediate', 'Path of the Just Ch. 22', 'Path of the Just Ch. 22', 'https://www.sefaria.org/Mesillat_Yesharim%2C_Chapter_22', 'The nature and cultivation of true humility', 'טבע וטיפוח של ענווה אמיתית', 'How do you distinguish between genuine humility and low self-esteem in your own behavior?', 'כיצד אתה מבחין בין ענווה אמיתית להערכה עצמית נמוכה בהתנהגות שלך?', '["Gates of Repentance", "Path of the Just", "Duties of Hearts"]', '["Humility cultivation", "Self-awareness"]', true),
('Solitude Benefits', 'יתרונות הבדידות', 'spiritual', 'mussar', 35, 30, 40, 'advanced', 'Duties of Hearts 8:3', 'Duties of Hearts 8:4', 'https://www.sefaria.org/Duties_of_the_Heart%2C_The_Gate_of_Spiritual_Accounting.3', 'The spiritual benefits of periodic solitude and reflection', 'היתרונות הרוחניים של בדידות והרהור תקופתיים', 'When do you make time for solitude and self-reflection, and what do you discover about yourself?', 'מתי אתה מייחד זמן לבדידות ולהרהור עצמי, ומה אתה מגלה על עצמך?', '["Gates of Repentance", "Path of the Just", "Duties of Hearts"]', '["Solitude value", "Self-examination"]', true),
('Ethical Will', 'צוואה אתית', 'spiritual', 'mussar', 40, 35, 45, 'advanced', 'Letter of Ramban', 'Letter of Ramban', 'https://www.sefaria.org/Ramban%27s_Letter', 'Ramban\'s ethical will to his son', 'הצוואה האתית של הרמב"ן לבנו', 'What ethical guidance would you want to leave for the next generation?', 'איזה הדרכה אתית היית רוצה להשאיר לדור הבא?', '["Gates of Repentance", "Path of the Just", "Duties of Hearts"]', '["Ethical legacy", "Wisdom transmission"]', true),
('Daily Accounting', 'חשבון נפש יומי', 'spiritual', 'mussar', 18, 12, 25, 'beginner', 'Path of the Just Ch. 3', 'Path of the Just Ch. 3', 'https://www.sefaria.org/Mesillat_Yesharim%2C_Chapter_3', 'The practice of daily spiritual accounting', 'תרגול חשבון הנפש היומי', 'What questions do you ask yourself at the end of each day to evaluate your spiritual progress?', 'אילו שאלות אתה שואל את עצמך בסוף כל יום כדי להעריך את ההתקדמות הרוחנית שלך?', '["Gates of Repentance", "Path of the Just", "Duties of Hearts"]', '["Self-evaluation", "Daily reflection"]', true),
('Anger Control', 'שליטה בכעס', 'spiritual', 'mussar', 28, 22, 35, 'intermediate', 'Orchot Tzadikim - Anger', 'Orchot Tzadikim - Anger', 'https://www.sefaria.org/Orchot_Tzadikim%2C_The_Gate_of_Anger', 'Methods for controlling and channeling anger constructively', 'שיטות לשליטה ולהפניית כעס בצורה בונה', 'What triggers your anger most, and what techniques help you respond more thoughtfully?', 'מה הכי מעורר את הכעס שלך, ואילו טכניקות עוזרות לך להגיב בצורה מחושבת יותר?', '["Gates of Repentance", "Path of the Just", "Duties of Hearts"]', '["Anger management", "Emotional control"]', true),
('Gratitude Cultivation', 'טיפוח הכרת הטוב', 'spiritual', 'mussar', 22, 18, 28, 'beginner', 'Duties of Hearts 2:4', 'Duties of Hearts 2:5', 'https://www.sefaria.org/Duties_of_the_Heart%2C_The_Gate_of_Examination.4', 'Developing genuine gratitude and recognition of blessings', 'פיתוח הכרת טוב ומודעות לברכות אמיתיות', 'What are three things you took for granted today that you can now appreciate more deeply?', 'מה שלושה דברים שלקחת כמובן מאליו היום שאתה יכול להעריך עכשיו יותר עמוק?', '["Gates of Repentance", "Path of the Just", "Duties of Hearts"]', '["Gratitude practice", "Blessing recognition"]', true),
('Spiritual Obstacles', 'מכשולים רוחניים', 'spiritual', 'mussar', 45, 40, 50, 'advanced', 'Path of the Just Ch. 5', 'Path of the Just Ch. 5', 'https://www.sefaria.org/Mesillat_Yesharim%2C_Chapter_5', 'Identifying and overcoming barriers to spiritual growth', 'זיהוי והתגברות על מכשולים לצמיחה רוחנית', 'What habits or attitudes in your life create the biggest barriers to your spiritual development?', 'אילו הרגלים או עמדות בחייך יוצרים את המכשולים הגדולים ביותר לפיתוח הרוחני שלך?', '["Gates of Repentance", "Path of the Just", "Duties of Hearts"]', '["Obstacle identification", "Spiritual barriers"]', true),
('Joy in Service', 'שמחה בעבודה', 'spiritual', 'mussar', 32, 28, 38, 'intermediate', 'Duties of Hearts 6:6', 'Duties of Hearts 6:7', 'https://www.sefaria.org/Duties_of_the_Heart%2C_The_Gate_of_Submission.6', 'Finding genuine joy in spiritual service and mitzvot', 'מציאת שמחה אמיתית בעבודה רוחנית ובמצוות', 'How can you cultivate more joy and enthusiasm in your religious observances?', 'כיצד תוכל לטפח יותר שמחה והתלהבות בקיום הדתי שלך?', '["Gates of Repentance", "Path of the Just", "Duties of Hearts"]', '["Joyful service", "Enthusiastic observance"]', true),

-- Chassidut (8 sources)
('Divine Spark', 'ניצוץ אלוקי', 'spiritual', 'chassidut', 20, 15, 25, 'intermediate', 'Tanya Ch. 2', 'Tanya Ch. 2', 'https://www.sefaria.org/Tanya%2C_Likutei_Amarim%2C_Chapter_2', 'Every soul contains a divine spark', 'כל נשמה מכילה ניצוץ אלוקי', 'How do you recognize and nurture the divine spark within yourself and others?', 'כיצד אתה מזהה ומטפח את הניצוץ האלוקי בתוך עצמך ובאחרים?', '["Chassidic masters", "Tanya commentaries", "Zohar"]', '["Soul awareness", "Divine presence"]', true),
('Baal Teshuva', 'בעל תשובה', 'spiritual', 'chassidut', 35, 30, 40, 'advanced', 'Tanya Ch. 14', 'Tanya Ch. 15', 'https://www.sefaria.org/Tanya%2C_Likutei_Amarim%2C_Chapter_14', 'The unique spiritual level of those who return', 'הרמה הרוחנית הייחודית של החוזרים בתשובה', 'How do your past mistakes and current growth contribute to your spiritual uniqueness?', 'כיצד הטעויות שלך בעבר והצמיחה הנוכחית תורמות לייחודיות הרוחנית שלך?', '["Chassidic masters", "Tanya commentaries", "Zohar"]', '["Repentance elevation", "Spiritual transformation"]', true),
('Hitbodedut Practice', 'תרגול התבודדות', 'spiritual', 'chassidut', 25, 20, 30, 'intermediate', 'Likutei Moharan 52', 'Likutei Moharan 52', 'https://www.sefaria.org/Likutei_Moharan%2C_Part_I.52', 'The practice of secluded meditation and self-reflection', 'תרגול של מדיטציה מבודדת והרהור עצמי', 'When and how do you create space for private conversation with the Divine?', 'מתי וכיצד אתה יוצר מקום לשיחה פרטית עם האלוקים?', '["Chassidic masters", "Tanya commentaries", "Zohar"]', '["Meditation practice", "Divine dialogue"]', true),
('Joy and Sadness', 'שמחה ועצבות', 'spiritual', 'chassidut', 30, 25, 35, 'intermediate', 'Tanya Ch. 26', 'Tanya Ch. 27', 'https://www.sefaria.org/Tanya%2C_Likutei_Amarim%2C_Chapter_26', 'Balancing spiritual joy with recognition of shortcomings', 'איזון שמחה רוחנית עם הכרה בחסרונות', 'How do you maintain spiritual joy while honestly acknowledging your areas for improvement?', 'כיצד אתה שומר על שמחה רוחנית תוך הכרה כנה באזורים לשיפור שלך?', '["Chassidic masters", "Tanya commentaries", "Zohar"]', '["Emotional balance", "Honest optimism"]', true),
('Hidden Miracles', 'ניסים נסתרים', 'spiritual', 'chassidut', 28, 22, 35, 'intermediate', 'Sefat Emet', 'Sefat Emet', 'https://www.sefaria.org/Sefat_Emet_on_Torah%2C_Genesis', 'Recognizing divine intervention in everyday events', 'זיהוי התערבות אלוקית באירועים יומיומיים', 'What "hidden miracles" have you noticed in your daily life recently?', 'אילו "ניסים נסתרים" שמת לב אליהם בחיים היומיומיים שלך לאחרונה?', '["Chassidic masters", "Tanya commentaries", "Zohar"]', '["Miracle awareness", "Divine providence"]', true),
('Soul Levels', 'דרגות הנשמה', 'spiritual', 'chassidut', 40, 35, 45, 'advanced', 'Tanya Ch. 3', 'Tanya Ch. 4', 'https://www.sefaria.org/Tanya%2C_Likutei_Amarim%2C_Chapter_3', 'The different levels and aspects of the soul', 'הדרגות וההיבטים השונים של הנשמה', 'Which aspect of your soul - intellectual, emotional, or behavioral - feels strongest in your spiritual practice?', 'איזה היבט של הנשמה שלך - שכלי, רגשי או התנהגותי - מרגיש הכי חזק בפרקטיקה הרוחנית שלך?', '["Chassidic masters", "Tanya commentaries", "Zohar"]', '["Soul structure", "Spiritual psychology"]', true),
('Mystical Unity', 'אחדות מיסטית', 'spiritual', 'chassidut', 45, 40, 50, 'advanced', 'Zohar on Genesis', 'Zohar on Genesis', 'https://www.sefaria.org/Zohar.1.1a', 'The underlying unity that connects all existence', 'האחדות הבסיסית המחברת את כל הקיום', 'How do you experience connection and unity with others and with the Divine in your daily life?', 'כיצד אתה חווה קשר ואחדות עם אחרים ועם האלוקים בחיים היומיומיים שלך?', '["Chassidic masters", "Tanya commentaries", "Zohar"]', '["Unity consciousness", "Mystical awareness"]', true),
('Simple Faith', 'אמונה פשוטה', 'spiritual', 'chassidut', 15, 10, 20, 'beginner', 'Likutei Moharan 7', 'Likutei Moharan 7', 'https://www.sefaria.org/Likutei_Moharan%2C_Part_I.7', 'The power and purity of simple, uncomplicated faith', 'הכוח והטוהר של אמונה פשוטה ולא מסובכת', 'When has simple faith carried you through times when intellectual understanding failed?', 'מתי אמונה פשוטה נשאה אותך בזמנים שההבנה השכלית נכשלה?', '["Chassidic masters", "Tanya commentaries", "Zohar"]', '["Simple faith", "Trust cultivation"]', true),

-- Jewish Philosophy (7 sources)
('Free Will Debate', 'ויכוח הבחירה החופשית', 'spiritual', 'jewish_philosophy', 40, 35, 45, 'advanced', 'Saadia Gaon - Beliefs', 'Saadia Gaon - Beliefs', 'https://www.sefaria.org/Emunot_veDeot', 'Classical Jewish perspectives on free will and determinism', 'נקודות מבט יהודיות קלאסיות על בחירה חופשית ודטרמיניזם', 'How do you balance taking responsibility for your choices with trusting in Divine providence?', 'כיצד אתה מאזן בין נטילת אחריות על הבחירות שלך לביטחון בהשגחה אלוקית?', '["Medieval philosophers", "Rishonim", "Acharonim"]', '["Free will understanding", "Responsibility ethics"]', true),
('Divine Attributes', 'תכונות אלוקיות', 'spiritual', 'jewish_philosophy', 35, 30, 40, 'advanced', 'Guide for Perplexed 1:50', 'Guide for Perplexed 1:55', 'https://www.sefaria.org/Guide_for_the_Perplexed%2C_Part_1.50', 'How we can and cannot describe the Divine', 'כיצד אנו יכולים ולא יכולים לתאר את האלוקים', 'How does the limitation of human language affect your personal prayer and relationship with God?', 'כיצד מגבלת השפה האנושית משפיעה על התפילה האישית והיחס שלך עם האלוקים?', '["Medieval philosophers", "Rishonim", "Acharonim"]', '["Divine description", "Language limits"]', true),
('Exile Purpose', 'מטרת הגלות', 'spiritual', 'jewish_philosophy', 30, 25, 35, 'intermediate', 'Maharal - Netzach Yisrael', 'Maharal - Netzach Yisrael', 'https://www.sefaria.org/Netzach_Yisrael', 'The spiritual purpose and meaning of exile', 'המטרה והמשמעות הרוחנית של הגלות', 'How do you find meaning and purpose in times of displacement or difficulty in your own life?', 'כיצד אתה מוצא משמעות ומטרה בזמנים של עקירה או קושי בחיים שלך?', '["Medieval philosophers", "Rishonim", "Acharonim"]', '["Exile meaning", "Suffering purpose"]', true),
('Soul Immortality', 'נצחיות הנשמה', 'spiritual', 'jewish_philosophy', 45, 40, 50, 'advanced', 'Ramban on Ecclesiastes', 'Ramban on Ecclesiastes', 'https://www.sefaria.org/Ramban_on_Ecclesiastes', 'Jewish perspectives on the soul\'s continued existence', 'נקודות מבט יהודיות על המשך קיום הנשמה', 'How does your belief about what happens after death affect the way you live now?', 'כיצד האמונה שלך על מה שקורה אחרי המוות משפיעה על הדרך שבה אתה חי עכשיו?', '["Medieval philosophers", "Rishonim", "Acharonim"]', '["Afterlife beliefs", "Life impact"]', true),
('Reason vs Revelation', 'שכל נגד גילוי', 'spiritual', 'jewish_philosophy', 50, 45, 55, 'advanced', 'Judah Halevi - Kuzari', 'Judah Halevi - Kuzari', 'https://www.sefaria.org/Kuzari', 'The relationship between rational inquiry and revealed truth', 'היחס בין חקירה רציונלית לאמת נגלית', 'How do you integrate rational thinking with faith-based beliefs in your own spiritual journey?', 'כיצד אתה משלב חשיבה רציונלית עם אמונות מבוססות אמונה במסע הרוחני שלך?', '["Medieval philosophers", "Rishonim", "Acharonim"]', '["Reason-faith integration", "Truth sources"]', true),
('Ethics and Metaphysics', 'אתיקה ומטפיזיקה', 'spiritual', 'jewish_philosophy', 38, 32, 45, 'advanced', 'Or Adonai - Crescas', 'Or Adonai - Crescas', 'https://www.sefaria.org/Or_Adonai', 'How metaphysical beliefs shape ethical obligations', 'כיצד אמונות מטפיזיות מעצבות חובות אתיות', 'How do your deepest beliefs about reality influence your daily ethical decisions?', 'כיצד האמונות העמוקות ביותר שלך על המציאות משפיעות על ההחלטות האתיות היומיומיות שלך?', '["Medieval philosophers", "Rishonim", "Acharonim"]', '["Ethics-metaphysics connection", "Belief-behavior link"]', true),
('Messianic Vision', 'חזון משיחי', 'spiritual', 'jewish_philosophy', 42, 38, 48, 'intermediate', 'Rambam - Hilchot Melachim', 'Rambam - Hilchot Melachim', 'https://www.sefaria.org/Mishneh_Torah%2C_Kings_and_Wars', 'Jewish concepts of ultimate redemption and perfection', 'מושגים יהודיים של גאולה ושלמות אולטימטיביים', 'How does your vision of an ideal world influence your actions to improve the current world?', 'כיצד החזון שלך של עולם אידיאלי משפיע על המעשים שלך לשיפור העולם הנוכחי?', '["Medieval philosophers", "Rishonim", "Acharonim"]', '["Messianic hope", "Present action"]', true);

-- SURPRISE ME SOURCES (15 total)
INSERT INTO sources (title, title_he, category, subcategory, estimated_time, min_time, max_time, difficulty_level, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, commentaries, learning_objectives, published) VALUES
('Butterfly Effect', 'אפקט הפרפר', 'surprise', 'mixed', 12, 8, 18, 'beginner', 'Berakhot 58a', 'Berakhot 58a', 'https://www.sefaria.org/Berakhot.58a', 'Small actions can have massive consequences', 'מעשים קטנים יכולים להביא להשלכות עצומות', 'What small act of kindness today might create ripples you never imagined?', 'איזה מעשה חסד קטן היום עלול ליצור גלים שמעולם לא דמיינת?', '["Rashi", "Tosafot", "Maharsha"]', '["Action awareness", "Ripple effects"]', true),
('Dream Logic', 'היגיון החלום', 'surprise', 'mixed', 18, 12, 25, 'intermediate', 'Berakhot 57b', 'Berakhot 57b', 'https://www.sefaria.org/Berakhot.57b', 'Talmudic interpretations of dreams and their meanings', 'פרשנויות תלמודיות לחלומות ומשמעויותיהם', 'What recurring dream or thought pattern might be trying to teach you something?', 'איזה חלום או דפוס מחשבה חוזר עלול לנסות ללמד אותך משהו?', '["Rashi", "Tosafot", "Maharsha"]', '["Subconscious wisdom", "Pattern recognition"]', true),
('Cosmic Perspective', 'פרספקטיבה קוסמית', 'surprise', 'mixed', 25, 20, 30, 'intermediate', 'Ecclesiastes 3:15', 'Ecclesiastes 3:15', 'https://www.sefaria.org/Ecclesiastes.3.15', 'What has been is what will be, and God seeks what has been pursued', 'מה שהיה הוא שיהיה והאלוקים יבקש את נרדף', 'How does thinking about eternity change your perspective on today\'s worries?', 'כיצד חשיבה על הנצחיות משנה את נקודת המבט שלך על הדאגות של היום?', '["Rashi", "Radak", "Metzudat David"]', '["Time perspective", "Eternal view"]', true),
('Animal Wisdom', 'חוכמת החיות', 'surprise', 'mixed', 20, 15, 25, 'beginner', 'Proverbs 6:6', 'Proverbs 6:8', 'https://www.sefaria.org/Proverbs.6.6', 'Go to the ant, you sluggard; consider its ways and be wise', 'לך אל נמלה עצל ראה דרכיה וחכם', 'What can you learn from observing animals or nature about diligence and preparation?', 'מה תוכל ללמוד מתצפית על חיות או טבע על חריצות והכנה?', '["Rashi", "Radak", "Metzudat David"]', '["Natural wisdom", "Life lessons from nature"]', true),
('Paradox of Strength', 'פרדוקס הכוח', 'surprise', 'mixed', 30, 25, 35, 'intermediate', 'Judges 14:14', 'Judges 14:14', 'https://www.sefaria.org/Judges.14.14', 'Samson\'s riddle: Out of the strong came sweetness', 'חידת שמשון: מהעז יצא מתוק', 'When has something that seemed entirely negative in your life produced unexpected sweetness?', 'מתי משהו שנראה לחלוטין שלילי בחייך הוליד מתיקות בלתי צפויה?', '["Rashi", "Radak", "Metzudat David"]', '["Hidden blessings", "Strength through adversity"]', true),
('Numerical Mysteries', 'תעלומות מספריות', 'surprise', 'mixed', 35, 30, 40, 'advanced', 'Zohar on Numbers', 'Zohar on Numbers', 'https://www.sefaria.org/Zohar.2.1a', 'The mystical significance of numbers in Jewish tradition', 'המשמעות המיסטית של מספרים במסורת היהודית', 'What patterns or numbers keep appearing in your life, and what might they signify?', 'אילו דפוסים או מספרים ממשיכים להופיע בחייך, ומה הם עלולים לסמל?', '["Zohar commentaries", "Kabbalistic sources", "Chassidic masters"]', '["Pattern recognition", "Mystical awareness"]', true),
('Food for Thought', 'מזון למחשבה', 'surprise', 'mixed', 22, 18, 28, 'beginner', 'Berakhot 40a', 'Berakhot 40a', 'https://www.sefaria.org/Berakhot.40a', 'The spiritual dimension of eating and blessing food', 'הממד הרוחני של אכילה וברכת מזון', 'How does saying blessings transform your relationship with food and consumption?', 'כיצד אמירת ברכות משנה את היחס שלך למזון ולצריכה?', '["Rashi", "Tosafot", "Maharsha"]', '["Mindful consumption", "Gratitude practice"]', true),
('Silent Communication', 'תקשורת שקטה', 'surprise', 'mixed', 28, 22, 35, 'intermediate', 'Psalms 19:2', 'Psalms 19:4', 'https://www.sefaria.org/Psalms.19.2', 'The heavens declare God\'s glory without speech or words', 'השמים מספרים כבוד אל בלי דיבור ומלים', 'What do you hear in moments of complete silence, and how does nature speak to you?', 'מה אתה שומע ברגעים של שקט מוחלט, וכיצד הטבע מדבר אליך?', '["Rashi", "Radak", "Metzudat David"]', '["Silent wisdom", "Natural revelation"]', true),
('Time Travel Ethics', 'אתיקה של נסיעה בזמן', 'surprise', 'mixed', 40, 35, 45, 'advanced', 'Sanhedrin 99a', 'Sanhedrin 99a', 'https://www.sefaria.org/Sanhedrin.99a', 'If you could change one thing in your past, should you?', 'אם יכולת לשנות דבר אחד בעבר שלך, האם היית צריך?', 'Looking back at your biggest mistake, how has it contributed to who you are today?', 'כשאתה מסתכל אחורה על הטעות הגדולה ביותר שלך, כיצד היא תרמה למי שאתה היום?', '["Rashi", "Tosafot", "Maharsha"]', '["Regret vs. acceptance", "Growth through mistakes"]', true),
('Invisible Influences', 'השפעות בלתי נראות', 'surprise', 'mixed', 32, 28, 38, 'intermediate', 'Kiddushin 40b', 'Kiddushin 40b', 'https://www.sefaria.org/Kiddushin.40b', 'Every person should see the world as half guilty, half innocent', 'לעולם יראה אדם את עצמו כאילו חצי זכאי וחצי חייב', 'How might your next small action tip the balance of the entire world?', 'כיצד המעשה הקטן הבא שלך עלול להטות את מאזן העולם כולו?', '["Rashi", "Tosafot", "Maharsha"]', '["Individual impact", "Cosmic responsibility"]', true),
('Mirror Meditation', 'מדיטציית מראה', 'surprise', 'mixed', 24, 18, 30, 'intermediate', 'Tanhuma Vayera 8', 'Tanhuma Vayera 8', 'https://www.sefaria.org/Midrash_Tanhuma%2C_Vayera.8', 'When you look at others, you see yourself reflected back', 'כשאתה מסתכל על אחרים, אתה רואה את עצמך מוחזר', 'What do the people who annoy you most reveal about aspects of yourself you need to work on?', 'מה האנשים שהכי מעצבנים אותך מגלים על היבטים של עצמך שאתה צריך לעבוד עליהם?', '["Midrash commentaries", "Chassidic interpretations"]', '["Self-reflection", "Projection awareness"]', true),
('Quantum Faith', 'אמונה קוונטית', 'surprise', 'mixed', 45, 40, 50, 'advanced', 'Chagigah 14b', 'Chagigah 14b', 'https://www.sefaria.org/Chagigah.14b', 'Rabbi Akiva entered the mystical realm and emerged whole', 'רבי עקיבא נכנס לפרדס ויצא בשלום', 'How do you maintain balance when experiencing the deepest spiritual insights?', 'כיצד אתה שומר על איזון כשאתה חווה את התובנות הרוחניות העמוקות ביותר?', '["Rashi", "Tosafot", "Maharsha"]', '["Mystical balance", "Spiritual integration"]', true),
('Laughter Therapy', 'טיפול בצחוק', 'surprise', 'mixed', 16, 10, 22, 'beginner', 'Berakhot 31a', 'Berakhot 31a', 'https://www.sefaria.org/Berakhot.31a', 'Joy breaks through barriers that seriousness cannot', 'שמחה פורצת מכשולים שרצינות לא יכולה', 'When has humor or lightness helped you through a situation that worry couldn\'t solve?', 'מתי הומור או קלילות עזרו לך לעבור מצב שדאגה לא יכלה לפתור?', '["Rashi", "Tosafot", "Maharsha"]', '["Therapeutic joy", "Lightness power"]', true),
('Reverse Psychology', 'פסיכולוגיה הפוכה', 'surprise', 'mixed', 38, 32, 45, 'advanced', 'Sotah 14a', 'Sotah 14a', 'https://www.sefaria.org/Sotah.14a', 'Sometimes the best way to teach is by demonstrating the opposite', 'לפעמים הדרך הטובה ביותר ללמד היא על ידי הדגמת ההפך', 'What have you learned most powerfully from observing what not to do?', 'מה למדת בצורה הכי חזקה מתצפית על מה לא לעשות?', '["Rashi", "Tosafot", "Maharsha"]', '["Negative examples", "Learning from opposites"]', true),
('Elevator Moments', 'רגעי מעלית', 'surprise', 'mixed', 26, 20, 32, 'intermediate', 'Avot 4:18', 'Avot 4:18', 'https://www.sefaria.org/Pirkei_Avot.4.18', 'Better one moment of repentance in this world...', 'טוב שעה אחת בתשובה ומעשים טובים בעולם הזה...', 'If you had only one minute to make a difference in someone\'s life today, what would you do?', 'אם היה לך רק דקה אחת להשפיע על החיים של מישהו היום, מה היית עושה?', '["Rashi", "Rambam", "Ruach Chaim"]', '["Moment awareness", "Instant impact"]', true);