-- Final Phase 1: Adding TALMUD sources (25 total) + SPIRITUAL sources (15 total) + SURPRISE sources (15 total)

-- TALMUD SOURCES - Pirkei Avot (12 sources)
INSERT INTO sources (title, title_he, category, subcategory, estimated_time, min_time, max_time, difficulty_level, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, commentaries, learning_objectives, published) VALUES
('Three Pillars', 'שלושה עמודים', 'talmud', 'pirkei_avot', 18, 12, 25, 'beginner', 'Avot 1:2', 'Avot 1:2', 'https://www.sefaria.org/Pirkei_Avot.1.2', 'The world stands on three things: Torah, service, and acts of kindness', 'על שלושה דברים העולם עומד: על התורה, ועל העבודה, ועל גמילות חסדים', 'How do you balance Torah study, prayer/service, and acts of kindness in your daily life?', 'כיצד אתה מאזן בין לימוד תורה, תפילה/עבודה ומעשי חסד בחיים היומיומיים שלך?', ARRAY['Rashi', 'Rambam', 'Ruach Chaim'], ARRAY['Foundational values', 'Life balance'], true),
('Say Little Do Much', 'אמור מעט ועשה הרבה', 'talmud', 'pirkei_avot', 15, 10, 20, 'beginner', 'Avot 1:15', 'Avot 1:15', 'https://www.sefaria.org/Pirkei_Avot.1.15', 'Shammai teaches: Say little and do much', 'שמאי אומר: אמור מעט ועשה הרבה', 'How can you better align your actions with your words and promises?', 'כיצד תוכל ליישר טוב יותר את המעשים שלך עם המילים וההבטחות שלך?', ARRAY['Rashi', 'Rambam', 'Ruach Chaim'], ARRAY['Action over words', 'Promise keeping'], true),
('Who is Wise', 'איזהו חכם', 'talmud', 'pirkei_avot', 22, 18, 28, 'intermediate', 'Avot 4:1', 'Avot 4:1', 'https://www.sefaria.org/Pirkei_Avot.4.1', 'Who is wise? One who learns from every person', 'איזהו חכם? הלומד מכל אדם', 'What have you learned recently from someone you would not normally consider a teacher?', 'מה למדת לאחרונה ממישהו שבדרך כלל לא היית רואה כמורה?', ARRAY['Rashi', 'Rambam', 'Ruach Chaim'], ARRAY['Wisdom sources', 'Continuous learning'], true),
('Judge Favorably', 'דן לכף זכות', 'talmud', 'pirkei_avot', 20, 15, 25, 'intermediate', 'Avot 1:6', 'Avot 1:6', 'https://www.sefaria.org/Pirkei_Avot.1.6', 'Judge every person favorably', 'והוי דן את כל האדם לכף זכות', 'When was the last time you gave someone the benefit of the doubt, and how did it affect the situation?', 'מתי בפעם האחרונה נתת למישהו את ההכרעה לטובה, וכיצד זה השפיע על המצב?', ARRAY['Rashi', 'Rambam', 'Ruach Chaim'], ARRAY['Positive judgment', 'Benefit of doubt'], true),
('Time for Torah', 'עת לתורה', 'talmud', 'pirkei_avot', 25, 20, 30, 'intermediate', 'Avot 2:5', 'Avot 2:5', 'https://www.sefaria.org/Pirkei_Avot.2.5', 'In a place where there are no menschen, strive to be a mensch', 'במקום שאין אנשים, השתדל להיות איש', 'When have you had to step up and take responsibility because no one else would?', 'מתי היית צריך לקחת על עצמך ולקחת אחריות כי אף אחד אחר לא היה עושה זאת?', ARRAY['Rashi', 'Rambam', 'Ruach Chaim'], ARRAY['Leadership initiative', 'Personal responsibility'], true),
('Torah and Work', 'תורה ומלאכה', 'talmud', 'pirkei_avot', 30, 25, 35, 'intermediate', 'Avot 2:2', 'Avot 2:2', 'https://www.sefaria.org/Pirkei_Avot.2.2', 'Torah study with worldly occupation prevents sin', 'יפה תלמוד תורה עם דרך ארץ', 'How do you integrate spiritual values into your professional or work life?', 'כיצד אתה משלב ערכים רוחניים בחיים המקצועיים או העבודה שלך?', ARRAY['Rashi', 'Rambam', 'Ruach Chaim'], ARRAY['Work-study balance', 'Integrated living'], true),
('Against Your Will', 'בעל כרחך', 'talmud', 'pirkei_avot', 35, 30, 40, 'advanced', 'Avot 4:22', 'Avot 4:22', 'https://www.sefaria.org/Pirkei_Avot.4.22', 'Against your will you were born, against your will you die', 'בעל כרחך אתה נולד ובעל כרחך אתה מת', 'How does recognizing the involuntary nature of birth and death change your perspective on life choices?', 'כיצד הכרה בטבע הלא-רצוני של הלידה והמוות משנה את נקודת המבט שלך על בחירות החיים?', ARRAY['Rashi', 'Rambam', 'Ruach Chaim'], ARRAY['Life acceptance', 'Choice within limits'], true),
('Age and Wisdom', 'גיל וחוכמה', 'talmud', 'pirkei_avot', 28, 22, 35, 'intermediate', 'Avot 5:21', 'Avot 5:21', 'https://www.sefaria.org/Pirkei_Avot.5.21', 'Different ages bring different capacities and responsibilities', 'גילים שונים מביאים יכולות ואחריויות שונות', 'How has your understanding of responsibility and wisdom changed as you have gotten older?', 'כיצד השתנתה ההבנה שלך של אחריות וחוכמה ככל שהתבגרת?', ARRAY['Rashi', 'Rambam', 'Ruach Chaim'], ARRAY['Life stages', 'Age-appropriate wisdom'], true),
('Rich in Content', 'עשיר בתוכן', 'talmud', 'pirkei_avot', 32, 28, 38, 'intermediate', 'Avot 4:1', 'Avot 4:1', 'https://www.sefaria.org/Pirkei_Avot.4.1', 'Who is rich? One who is satisfied with their portion', 'איזהו עשיר? השמח בחלקו', 'What does it mean to be satisfied with your portion in a culture that encourages constant improvement?', 'מה זה אומר להיות שמח בחלקו בתרבות שמעודדת שיפור מתמיד?', ARRAY['Rashi', 'Rambam', 'Ruach Chaim'], ARRAY['Contentment cultivation', 'True wealth'], true),
('World to Come', 'עולם הבא', 'talmud', 'pirkei_avot', 40, 35, 45, 'advanced', 'Avot 4:17', 'Avot 4:17', 'https://www.sefaria.org/Pirkei_Avot.4.17', 'Better one hour of repentance in this world than all of the world to come', 'יפה שעה אחת בתשובה ומעשים טובים בעולם הזה מכל חיי העולם הבא', 'How does belief in an afterlife affect your priorities and actions in this life?', 'כיצד אמונה בחיים שלאחר המוות משפיעה על הסדרי העדיפויות והמעשים שלך בחיים האלה?', ARRAY['Rashi', 'Rambam', 'Ruach Chaim'], ARRAY['Afterlife perspective', 'Present moment value'], true),
('Study Method', 'שיטת לימוד', 'talmud', 'pirkei_avot', 24, 18, 30, 'intermediate', 'Avot 6:6', 'Avot 6:6', 'https://www.sefaria.org/Pirkei_Avot.6.6', 'Torah is acquired through 48 ways', 'בארבעים ושמונה דברים נקנית התורה', 'Which methods of learning work best for you, and how do you cultivate effective study habits?', 'אילו שיטות למידה עובדות הכי טוב עבורך, וכיצד אתה מטפח הרגלי לימוד יעילים?', ARRAY['Rashi', 'Rambam', 'Ruach Chaim'], ARRAY['Learning methodology', 'Study habits'], true),
('Honor and Crown', 'כבוד וכתר', 'talmud', 'pirkei_avot', 45, 40, 50, 'advanced', 'Avot 4:13', 'Avot 4:13', 'https://www.sefaria.org/Pirkei_Avot.4.13', 'The crown of Torah surpasses the crown of priesthood and kingship', 'כתר תורה גדול מכתר כהונה ומכתר מלכות', 'How do you pursue recognition and honor in your life, and what forms of honor do you value most?', 'כיצד אתה רודף אחרי הכרה וכבוד בחייך, ואילו צורות של כבוד אתה הכי מעריך?', ARRAY['Rashi', 'Rambam', 'Ruach Chaim'], ARRAY['True honor', 'Merit hierarchy'], true);

-- TALMUD - Berakhot (8 sources)
INSERT INTO sources (title, title_he, category, subcategory, estimated_time, min_time, max_time, difficulty_level, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, commentaries, learning_objectives, published) VALUES
('Blessings Awareness', 'מודעות לברכות', 'talmud', 'berakhot', 20, 15, 25, 'beginner', 'Berakhot 35a', 'Berakhot 35a', 'https://www.sefaria.org/Berakhot.35a', 'It is forbidden to benefit from this world without a blessing', 'אסור לו לאדם שיהנה מן העולם הזה בלא ברכה', 'How does saying blessings change your awareness of daily pleasures and necessities?', 'כיצד אמירת ברכות משנה את המודעות שלך להנאות ולצרכים יומיומיים?', ARRAY['Rashi', 'Tosafot', 'Maharsha'], ARRAY['Blessing consciousness', 'Gratitude practice'], true),
('Prayer Concentration', 'כוונה בתפילה', 'talmud', 'berakhot', 25, 20, 30, 'intermediate', 'Berakhot 31a', 'Berakhot 31a', 'https://www.sefaria.org/Berakhot.31a', 'One should not pray except with a heavy heart', 'אין אדם מתפלל אלא מתוך כובד ראש', 'What helps you achieve the right mindset and concentration for meaningful prayer?', 'מה עוזר לך להשיג את המחשבה וריכוז הנכונים לתפילה משמעותית?', ARRAY['Rashi', 'Tosafot', 'Maharsha'], ARRAY['Prayer focus', 'Spiritual preparation'], true),
('Morning Blessings', 'ברכות השחר', 'talmud', 'berakhot', 30, 25, 35, 'intermediate', 'Berakhot 60b', 'Berakhot 60b', 'https://www.sefaria.org/Berakhot.60b', 'The series of blessings recited upon waking', 'סדרת הברכות הנאמרות בהתעוררות', 'How do morning blessings help you transition from sleep to conscious, purposeful living?', 'כיצד ברכות השחר עוזרות לך לעבור משינה לחיים מודעים ומכוונים?', ARRAY['Rashi', 'Tosafot', 'Maharsha'], ARRAY['Morning consciousness', 'Daily spiritual awakening'], true),
('Dream Interpretation', 'פתרון חלומות', 'talmud', 'berakhot', 35, 30, 40, 'advanced', 'Berakhot 55b', 'Berakhot 55b', 'https://www.sefaria.org/Berakhot.55b', 'Dreams follow their interpretation', 'חלום הולך אחר הפתרון', 'How do you interpret the meaningful dreams or recurring themes in your sleep, and what do they tell you about your concerns?', 'כיצד אתה מפרש את החלומות המשמעותיים או הנושאים החוזרים בשינה שלך, ומה הם אומרים לך על הדאגות שלך?', ARRAY['Rashi', 'Tosafot', 'Maharsha'], ARRAY['Dream wisdom', 'Subconscious insight'], true),
('Mezuzah Protection', 'הגנת המזוזה', 'talmud', 'berakhot', 22, 18, 28, 'intermediate', 'Berakhot 15b', 'Berakhot 15b', 'https://www.sefaria.org/Berakhot.15b', 'The mezuzah protects both inside and outside the house', 'המזוזה שומרת על הבית מבפנים ומבחוץ', 'How do physical objects like mezuzot create spiritual awareness in your living space?', 'כיצד חפצים פיזיים כמו מזוזות יוצרים מודעות רוחנית במרחב המגורים שלך?', ARRAY['Rashi', 'Tosafot', 'Maharsha'], ARRAY['Sacred space', 'Physical-spiritual connection'], true),
('Shema Timing', 'זמני קריאת שמע', 'talmud', 'berakhot', 28, 22, 35, 'intermediate', 'Berakhot 9b', 'Berakhot 9b', 'https://www.sefaria.org/Berakhot.9b', 'The proper times for reciting the Shema', 'הזמנים הנכונים לקריאת שמע', 'How does saying Shema at specific times create a rhythm of consciousness throughout your day?', 'כיצד אמירת שמע בזמנים מסוימים יוצרת קצב של מודעות לאורך היום שלך?', ARRAY['Rashi', 'Tosafot', 'Maharsha'], ARRAY['Time sanctification', 'Daily spiritual rhythm'], true),
('Torah as Antidote', 'תורה כתרופה', 'talmud', 'berakhot', 40, 35, 45, 'advanced', 'Berakhot 5a', 'Berakhot 5a', 'https://www.sefaria.org/Berakhot.5a', 'Torah study is an antidote to suffering', 'תורה תרופה ליצר הרע', 'How does learning and intellectual engagement help you deal with emotional or spiritual difficulties?', 'כיצד למידה ומעורבות אינטלקטואלית עוזרות לך להתמודד עם קשיים רגשיים או רוחניים?', ARRAY['Rashi', 'Tosafot', 'Maharsha'], ARRAY['Torah therapy', 'Learning as healing'], true),
('Hospitality Priority', 'עדיפות האכסון', 'talmud', 'berakhot', 45, 40, 50, 'intermediate', 'Berakhot 63b', 'Berakhot 63b', 'https://www.sefaria.org/Berakhot.63b', 'Welcoming guests is greater than welcoming the Divine Presence', 'גדולה הכנסת אורחים מהקבלת פני שכינה', 'How do you balance time for spiritual practices with time for helping and hosting others?', 'כיצד אתה מאזן זמן לפרקטיקות רוחניות עם זמן לעזרה ואירוח אחרים?', ARRAY['Rashi', 'Tosafot', 'Maharsha'], ARRAY['Hospitality vs worship', 'Social priorities'], true);

-- TALMUD - Various Sugyot (5 sources)
INSERT INTO sources (title, title_he, category, subcategory, estimated_time, min_time, max_time, difficulty_level, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, commentaries, learning_objectives, published) VALUES
('Hillel Patience', 'סבלנות הלל', 'talmud', 'various_sugyot', 25, 20, 30, 'intermediate', 'Shabbat 31a', 'Shabbat 31a', 'https://www.sefaria.org/Shabbat.31a', 'The whole Torah while standing on one foot', 'כל התורה כולה על רגל אחת', 'How do you explain your core values and beliefs in simple terms to someone who disagrees with you?', 'כיצד אתה מסביר את הערכים והאמונות המרכזיות שלך במילים פשוטות למישהו שלא מסכים איתך?', ARRAY['Rashi', 'Tosafot', 'Maharsha'], ARRAY['Essential teachings', 'Patience in education'], true),
('Charity Levels', 'דרגות צדקה', 'talmud', 'various_sugyot', 35, 30, 40, 'advanced', 'Bava Batra 9a', 'Bava Batra 9a', 'https://www.sefaria.org/Bava_Batra.9a', 'Different levels and types of charitable giving', 'דרגות וסוגים שונים של נתינת צדקה', 'How do you decide between different charitable causes and what criteria do you use for giving?', 'כיצד אתה מחליט בין מטרות צדקה שונות ואילו קריטריונים אתה משתמש לנתינה?', ARRAY['Rashi', 'Tosafot', 'Maharsha'], ARRAY['Charity wisdom', 'Giving strategy'], true),
('Gossip Damage', 'נזק לשון הרע', 'talmud', 'various_sugyot', 30, 25, 35, 'intermediate', 'Arachin 15b', 'Arachin 15b', 'https://www.sefaria.org/Arachin.15b', 'Gossip kills three people: the speaker, listener, and subject', 'לשון הרע הורגת שלושה: האומר, הקבל, והנאמר עליו', 'How do you handle situations where others want to share negative information about someone you know?', 'כיצד אתה מתמודד עם מצבים שבהם אחרים רוצים לחלוק מידע שלילי על מישהו שאתה מכיר?', ARRAY['Rashi', 'Tosafot', 'Maharsha'], ARRAY['Speech ethics', 'Communication responsibility'], true),
('Partnership with God', 'שותפות עם האלוקים', 'talmud', 'various_sugyot', 40, 35, 45, 'advanced', 'Shabbat 10a', 'Shabbat 10a', 'https://www.sefaria.org/Shabbat.10a', 'When judges judge truly, they become partners with God in creation', 'כשדיינים דנים דין אמת נעשים שותפים בבריאה', 'How do you see your daily decisions and judgments as participating in divine creation and justice?', 'כיצד אתה רואה את ההחלטות והשיפוטים היומיומיים שלך כהשתתפות בבריאה ובצדק האלוקיים?', ARRAY['Rashi', 'Tosafot', 'Maharsha'], ARRAY['Divine partnership', 'Justice responsibility'], true),
('Study Partnership', 'שותפות לימוד', 'talmud', 'various_sugyot', 20, 15, 25, 'beginner', 'Taanit 7a', 'Taanit 7a', 'https://www.sefaria.org/Taanit.7a', 'Much have I learned from my teachers, more from my colleagues', 'הרבה למדתי מרבותי, יותר מחברי', 'Who are your most effective learning partners and what makes those relationships productive?', 'מי הם השותפים הכי יעילים ללמידה שלך ומה הופך את היחסים האלה לפרודוקטיביים?', ARRAY['Rashi', 'Tosafot', 'Maharsha'], ARRAY['Learning relationships', 'Peer education'], true);