-- Continue Phase 1: Adding RAMBAM sources (20 total) + TANAKH sources (20 total) + TALMUD sources (20 total)

-- RAMBAM SOURCES - Hilchot Deot (10 sources)
INSERT INTO sources (title, title_he, category, subcategory, estimated_time, min_time, max_time, difficulty_level, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, commentaries, learning_objectives, published) VALUES
('The Golden Mean', 'שביל הזהב', 'rambam', 'hilchot_deot', 15, 10, 20, 'beginner', 'Mishneh Torah, Deot 1:4', 'Mishneh Torah, Deot 1:6', 'https://www.sefaria.org/Mishneh_Torah%2C_Deot.1.4', 'Rambam teaches the middle path in character traits', 'הרמב"ם מלמד על דרך האמצע בתכונות האופי', 'How can you identify and work towards the golden mean in your own character traits?', 'כיצד תוכל לזהות ולפעול לקראת דרך האמצע בתכונות האופי שלך?', ARRAY['Lechem Mishneh', 'Kesef Mishneh', 'Radbaz'], ARRAY['Character development', 'Emotional balance'], true),
('Anger Management', 'ניהול כעס', 'rambam', 'hilchot_deot', 20, 15, 25, 'intermediate', 'Mishneh Torah, Deot 2:3', 'Mishneh Torah, Deot 2:4', 'https://www.sefaria.org/Mishneh_Torah%2C_Deot.2.3', 'Rambam approach to controlling anger', 'גישת הרמב"ם לשליטה בכעס', 'What triggers your anger most, and how can you apply Rambam advice to manage it?', 'מה הכי מעורר את הכעס שלך, וכיצד תוכל ליישם את עצת הרמב"ם לנהל אותו?', ARRAY['Lechem Mishneh', 'Kesef Mishneh', 'Radbaz'], ARRAY['Anger management', 'Emotional self-control'], true),
('Humility and Pride', 'ענווה וגאווה', 'rambam', 'hilchot_deot', 25, 20, 30, 'intermediate', 'Mishneh Torah, Deot 2:3', 'Mishneh Torah, Deot 2:5', 'https://www.sefaria.org/Mishneh_Torah%2C_Deot.2.3', 'The balance between humility and healthy self-regard', 'האיזון בין ענווה להערכה עצמית בריאה', 'How do you distinguish between healthy confidence and harmful pride in your daily interactions?', 'כיצד אתה מבחין בין ביטחון עצמי בריא לגאווה מזיקה באינטראקציות היומיומיות?', ARRAY['Lechem Mishneh', 'Kesef Mishneh', 'Radbaz'], ARRAY['Humility cultivation', 'Self-awareness development'], true),
('Social Interaction', 'יחסים חברתיים', 'rambam', 'hilchot_deot', 30, 25, 35, 'intermediate', 'Mishneh Torah, Deot 6:1', 'Mishneh Torah, Deot 6:3', 'https://www.sefaria.org/Mishneh_Torah%2C_Deot.6.1', 'Guidelines for proper social behavior and relationships', 'הנחיות להתנהגות חברתית נאותה ויחסים', 'How do Rambam social guidelines apply to modern relationship challenges?', 'כיצד ההנחיות החברתיות של הרמב"ם חלות על אתגרי יחסים מודרניים?', ARRAY['Lechem Mishneh', 'Kesef Mishneh', 'Radbaz'], ARRAY['Social ethics', 'Relationship building'], true),
('Truth and Honesty', 'אמת ויושר', 'rambam', 'hilchot_deot', 35, 30, 40, 'intermediate', 'Mishneh Torah, Deot 2:6', 'Mishneh Torah, Deot 2:7', 'https://www.sefaria.org/Mishneh_Torah%2C_Deot.2.6', 'The imperative of truthfulness in speech and action', 'החובה של אמתיות בדיבור ובמעשה', 'When have you found it challenging to be completely truthful, and what did you learn from that experience?', 'מתי מצאת את זה מאתגר להיות אמתי לחלוטין, ומה למדת מהחוויה הזו?', ARRAY['Lechem Mishneh', 'Kesef Mishneh', 'Radbaz'], ARRAY['Honesty cultivation', 'Integrity development'], true),
('Generosity Guidelines', 'הנחיות נדיבות', 'rambam', 'hilchot_deot', 40, 35, 45, 'advanced', 'Mishneh Torah, Deot 1:5', 'Mishneh Torah, Deot 1:7', 'https://www.sefaria.org/Mishneh_Torah%2C_Deot.1.5', 'Proper balance in giving and generosity', 'איזון נכון בנתינה ונדיבות', 'How can you ensure your generosity helps others without enabling dependency?', 'כיצד תוכל להבטיח שהנדיבות שלך עוזרת לאחרים מבלי ליצור תלות?', ARRAY['Lechem Mishneh', 'Kesef Mishneh', 'Radbaz'], ARRAY['Ethical giving', 'Wise generosity'], true),
('Speech Ethics', 'אתיקה בדיבור', 'rambam', 'hilchot_deot', 12, 8, 18, 'beginner', 'Mishneh Torah, Deot 7:1', 'Mishneh Torah, Deot 7:3', 'https://www.sefaria.org/Mishneh_Torah%2C_Deot.7.1', 'Guidelines for proper and ethical speech', 'הנחיות לדיבור נכון ואתי', 'What words do you wish you could take back, and how can you speak more thoughtfully going forward?', 'אילו מילים היית רוצה לקחת בחזרה, וכיצד תוכל לדבר בצורה מחושבת יותר בהמשך?', ARRAY['Lechem Mishneh', 'Kesef Mishneh', 'Radbaz'], ARRAY['Ethical communication', 'Mindful speech'], true),
('Personal Health', 'בריאות אישית', 'rambam', 'hilchot_deot', 45, 40, 50, 'intermediate', 'Mishneh Torah, Deot 4:1', 'Mishneh Torah, Deot 4:4', 'https://www.sefaria.org/Mishneh_Torah%2C_Deot.4.1', 'Rambam approach to maintaining physical and mental health', 'גישת הרמב"ם לשמירה על בריאות גופנית ונפשית', 'How does taking care of your physical health serve your spiritual development?', 'כיצד דאגה לבריאות הגופנית משרתת את ההתפתחות הרוחנית שלך?', ARRAY['Lechem Mishneh', 'Kesef Mishneh', 'Radbaz'], ARRAY['Holistic health', 'Body-soul connection'], true),
('Learning and Teaching', 'למידה והוראה', 'rambam', 'hilchot_deot', 50, 45, 55, 'advanced', 'Mishneh Torah, Deot 6:6', 'Mishneh Torah, Deot 6:8', 'https://www.sefaria.org/Mishneh_Torah%2C_Deot.6.6', 'The character traits needed for effective learning and teaching', 'תכונות האופי הדרושות ללמידה והוראה יעילות', 'What makes someone an effective teacher, and how can you cultivate those qualities?', 'מה הופך מישהו למורה יעיל, וכיצד תוכל לטפח את התכונות הללו?', ARRAY['Lechem Mishneh', 'Kesef Mishneh', 'Radbaz'], ARRAY['Educational excellence', 'Character-based teaching'], true),
('Friendship Ethics', 'אתיקה בידידות', 'rambam', 'hilchot_deot', 28, 22, 35, 'intermediate', 'Mishneh Torah, Deot 6:2', 'Mishneh Torah, Deot 6:4', 'https://www.sefaria.org/Mishneh_Torah%2C_Deot.6.2', 'Guidelines for being a good friend and choosing friends wisely', 'הנחיות להיות חבר טוב ולבחור חברים בחוכמה', 'What qualities do you most value in a friend, and how well do you embody those qualities yourself?', 'אילו תכונות אתה הכי מעריך בחבר, ועד כמה אתה מגלם את התכונות הללו בעצמך?', ARRAY['Lechem Mishneh', 'Kesef Mishneh', 'Radbaz'], ARRAY['Friendship wisdom', 'Social character development'], true);

-- RAMBAM - Hilchot Teshuva (10 sources) 
INSERT INTO sources (title, title_he, category, subcategory, estimated_time, min_time, max_time, difficulty_level, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, commentaries, learning_objectives, published) VALUES
('Nature of Repentance', 'טבע התשובה', 'rambam', 'hilchot_teshuva', 18, 12, 25, 'beginner', 'Mishneh Torah, Teshuva 1:1', 'Mishneh Torah, Teshuva 1:3', 'https://www.sefaria.org/Mishneh_Torah%2C_Teshuva.1.1', 'Rambam defines the essential nature of teshuva', 'הרמב"ם מגדיר את הטבע החיוני של תשובה', 'What does genuine repentance feel like, and how is it different from mere regret?', 'איך מרגישה תשובה אמיתית, ובמה היא שונה מחרטה בלבד?', ARRAY['Lechem Mishneh', 'Kesef Mishneh', 'Radbaz'], ARRAY['Repentance fundamentals', 'Spiritual transformation'], true),
('Steps of Teshuva', 'שלבי התשובה', 'rambam', 'hilchot_teshuva', 25, 20, 30, 'intermediate', 'Mishneh Torah, Teshuva 2:2', 'Mishneh Torah, Teshuva 2:4', 'https://www.sefaria.org/Mishneh_Torah%2C_Teshuva.2.2', 'The detailed process of complete repentance', 'התהליך המפורט של תשובה שלמה', 'Which step of teshuva do you find most challenging, and why?', 'איזה שלב בתשובה אתה מוצא הכי מאתגר, ולמה?', ARRAY['Lechem Mishneh', 'Kesef Mishneh', 'Radbaz'], ARRAY['Teshuva methodology', 'Personal transformation process'], true),
('Confession Requirements', 'דרישות הוידוי', 'rambam', 'hilchot_teshuva', 22, 18, 28, 'intermediate', 'Mishneh Torah, Teshuva 1:1', 'Mishneh Torah, Teshuva 1:4', 'https://www.sefaria.org/Mishneh_Torah%2C_Teshuva.1.1', 'The proper form and requirements for confession', 'הצורה הנכונה והדרישות לוידוי', 'How does verbalizing wrongdoing change your relationship to your actions?', 'כיצד ביטוי מילולי של מעשה שגוי משנה את היחס שלך למעשיך?', ARRAY['Lechem Mishneh', 'Kesef Mishneh', 'Radbaz'], ARRAY['Confession practices', 'Verbal accountability'], true),
('Return vs Exchange', 'שבה נגד החזרה', 'rambam', 'hilchot_teshuva', 35, 30, 40, 'advanced', 'Mishneh Torah, Teshuva 7:3', 'Mishneh Torah, Teshuva 7:5', 'https://www.sefaria.org/Mishneh_Torah%2C_Teshuva.7.3', 'The difference between teshuva and mere behavioral exchange', 'ההבדל בין תשובה לשינוי התנהגותי בלבד', 'How do you know when you have truly changed versus just modified your behavior temporarily?', 'כיצד אתה יודע מתי השתנית באמת לעומת רק שינית את ההתנהגות זמנית?', ARRAY['Lechem Mishneh', 'Kesef Mishneh', 'Radbaz'], ARRAY['Authentic change', 'Deep vs surface transformation'], true),
('Love and Fear in Teshuva', 'אהבה ויראה בתשובה', 'rambam', 'hilchot_teshuva', 30, 25, 35, 'advanced', 'Mishneh Torah, Teshuva 10:1', 'Mishneh Torah, Teshuva 10:3', 'https://www.sefaria.org/Mishneh_Torah%2C_Teshuva.10.1', 'Different motivations for repentance and their effects', 'מוטיבציות שונות לתשובה והשפעותיהן', 'Is your spiritual growth motivated more by love or fear, and how does that affect your relationship with the Divine?', 'האם הצמיחה הרוחנית שלך מונעת יותר מאהבה או פחד, וכיצד זה משפיע על היחס שלך עם האלוקים?', ARRAY['Lechem Mishneh', 'Kesef Mishneh', 'Radbaz'], ARRAY['Spiritual motivation', 'Love vs fear dynamics'], true),
('Complete Teshuva', 'תשובה שלמה', 'rambam', 'hilchot_teshuva', 40, 35, 45, 'advanced', 'Mishneh Torah, Teshuva 2:1', 'Mishneh Torah, Teshuva 2:3', 'https://www.sefaria.org/Mishneh_Torah%2C_Teshuva.2.1', 'What constitutes complete and perfect repentance', 'מה מהווה תשובה שלמה ומושלמת', 'How would you recognize if you had achieved complete teshuva for a particular wrongdoing?', 'כיצד היית מזהה אם השגת תשובה שלמה על מעשה שגוי מסוים?', ARRAY['Lechem Mishneh', 'Kesef Mishneh', 'Radbaz'], ARRAY['Perfect repentance', 'Spiritual completeness'], true),
('Teshuva and Time', 'תשובה וזמן', 'rambam', 'hilchot_teshuva', 45, 40, 50, 'intermediate', 'Mishneh Torah, Teshuva 3:14', 'Mishneh Torah, Teshuva 3:16', 'https://www.sefaria.org/Mishneh_Torah%2C_Teshuva.3.14', 'The relationship between teshuva and different life stages', 'היחס בין תשובה לשלבי חיים שונים', 'How has your capacity for teshuva changed as you have gotten older and gained more life experience?', 'כיצד השתנתה היכולת שלך לתשובה ככל שהתבגרת וצברת יותר ניסיון חיים?', ARRAY['Lechem Mishneh', 'Kesef Mishneh', 'Radbaz'], ARRAY['Life stage spirituality', 'Maturation in teshuva'], true),
('Barriers to Teshuva', 'מכשולים לתשובה', 'rambam', 'hilchot_teshuva', 50, 45, 55, 'advanced', 'Mishneh Torah, Teshuva 4:1', 'Mishneh Torah, Teshuva 4:4', 'https://www.sefaria.org/Mishneh_Torah%2C_Teshuva.4.1', 'What prevents people from achieving genuine repentance', 'מה מונע מאנשים להשיג תשובה אמיתית', 'What personal or cultural barriers make teshuva most difficult for you?', 'אילו מכשולים אישיים או תרבותיים הופכים את התשובה לקשה ביותר עבורך?', ARRAY['Lechem Mishneh', 'Kesef Mishneh', 'Radbaz'], ARRAY['Repentance obstacles', 'Spiritual self-awareness'], true),
('Divine Knowledge', 'ידיעה אלוקית', 'rambam', 'guide_perplexed', 35, 30, 40, 'advanced', 'Guide for the Perplexed 3:20', 'Guide for the Perplexed 3:21', 'https://www.sefaria.org/Guide_for_the_Perplexed%2C_Part_3.20', 'Rambam explores how Divine knowledge differs from human knowledge', 'הרמב"ם חוקר כיצד הידיעה האלוקית שונה מהידיעה האנושית', 'How do you reconcile the limits of human understanding with faith in Divine wisdom?', 'כיצד אתה מיישב את גבולות ההבנה האנושית עם האמונה בחוכמה האלוקית?', ARRAY['Shem Tov', 'Efodi', 'Crescas'], ARRAY['Divine attributes', 'Epistemology and faith'], true),
('Prophecy and Philosophy', 'נבואה ופילוסופיה', 'rambam', 'guide_perplexed', 55, 50, 60, 'advanced', 'Guide for the Perplexed 2:36', 'Guide for the Perplexed 2:37', 'https://www.sefaria.org/Guide_for_the_Perplexed%2C_Part_2.36', 'The relationship between prophetic knowledge and philosophical understanding', 'היחס בין ידע נבואי להבנה פילוסופית', 'How do you integrate rational thinking with spiritual intuition in your own understanding?', 'כיצד אתה משלב חשיבה רציונלית עם אינטואיציה רוחנית בהבנה שלך?', ARRAY['Shem Tov', 'Efodi', 'Crescas'], ARRAY['Prophecy comprehension', 'Reason and revelation'], true);