-- Phase 1: Massive Source Content Expansion
-- Adding 150+ sources across all categories with proper time distribution and commentaries

-- HALACHA SOURCES (30 total)
-- Daily Practice (8 sources)
INSERT INTO sources (title, title_he, category, subcategory, estimated_time, min_time, max_time, difficulty_level, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, commentaries, learning_objectives, published) VALUES
('Morning Blessings Structure', 'סדר ברכות השחר', 'halacha', 'daily_practice', 10, 5, 15, 'beginner', 'Orach Chaim 46:1', 'Orach Chaim 46:3', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.46.1', 'The structure and meaning of morning blessings that begin our day', 'מבנה ומשמעות ברכות השחר המתחילות את יומנו', 'How do morning blessings set the tone for your entire day?', 'כיצד ברכות השחר קובעות את הטון לכל היום שלך?', ARRAY['Mishnah Berurah', 'Aruch HaShulchan', 'Kaf HaChaim'], ARRAY['Understanding daily blessing structure', 'Spiritual preparation for the day'], true),
('Hand Washing Laws', 'הלכות נטילת ידיים', 'halacha', 'daily_practice', 15, 10, 20, 'intermediate', 'Orach Chaim 158:1', 'Orach Chaim 158:12', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.158.1', 'Complete laws governing when and how we wash our hands', 'הלכות המפרטות מתי וכיצד נוטלים ידיים', 'What spiritual significance do you find in the act of washing hands before eating?', 'איזה משמעות רוחנית אתה מוצא במעשה נטילת הידיים לפני האכילה?', ARRAY['Mishnah Berurah', 'Shaar HaTziyun', 'Biur Halakha'], ARRAY['Practical hand washing knowledge', 'Understanding ritual purity'], true),
('Daily Torah Study Obligation', 'חובת תלמוד תורה יומי', 'halacha', 'daily_practice', 20, 15, 25, 'intermediate', 'Yoreh Deah 246:1', 'Yoreh Deah 246:5', 'https://www.sefaria.org/Shulchan_Arukh%2C_Yoreh_De%27ah.246.1', 'The obligation and methods for daily Torah study', 'החובה והשיטות ללימוד תורה יומי', 'How can you structure your day to fulfill the mitzvah of daily Torah study?', 'כיצד תוכל לארגן את יומך כדי לקיים את מצוות תלמוד תורה יומי?', ARRAY['Shach', 'Taz', 'Aruch HaShulchan'], ARRAY['Understanding Torah study requirements', 'Creating sustainable learning habits'], true),
('Mezuzah Placement', 'מקום קביעת המזוזה', 'halacha', 'daily_practice', 25, 20, 30, 'advanced', 'Yoreh Deah 289:1', 'Yoreh Deah 289:6', 'https://www.sefaria.org/Shulchan_Arukh%2C_Yoreh_De%27ah.289.1', 'Detailed laws about where and how to place mezuzot', 'הלכות מפורטות על מיקום וקביעת מזוזות', 'What does the mezuzah represent in terms of sanctifying your living space?', 'מה המזוזה מייצגת מבחינת קידוש מקום המגורים?', ARRAY['Shach', 'Taz', 'Pitchei Teshuvah'], ARRAY['Mezuzah placement requirements', 'Home sanctification concepts'], true),
('Tefillin Laws Overview', 'כללי הלכות תפילין', 'halacha', 'daily_practice', 30, 25, 35, 'advanced', 'Orach Chaim 25:1', 'Orach Chaim 25:15', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.25.1', 'Comprehensive overview of tefillin laws and customs', 'סקירה מקיפה של הלכות ומנהגי תפילין', 'How does wearing tefillin create a connection between thought, speech, and action?', 'כיצד הנחת תפילין יוצרת קשר בין מחשבה, דיבור ומעשה?', ARRAY['Mishnah Berurah', 'Aruch HaShulchan', 'Kaf HaChaim'], ARRAY['Tefillin requirements', 'Mind-body spiritual connection'], true),
('Charity Obligations', 'חובות צדקה', 'halacha', 'daily_practice', 35, 30, 40, 'intermediate', 'Yoreh Deah 249:1', 'Yoreh Deah 249:10', 'https://www.sefaria.org/Shulchan_Arukh%2C_Yoreh_De%27ah.249.1', 'Laws governing our obligations to give charity', 'הלכות החובות לתת צדקה', 'How can giving charity become a meaningful daily practice rather than just an obligation?', 'כיצד נתינת צדקה יכולה להפוך להרגל יומי משמעותי ולא רק חובה?', ARRAY['Shach', 'Taz', 'Aruch HaShulchan'], ARRAY['Charity obligations', 'Developing generosity'], true),
('Blessings on Food', 'ברכות על המזון', 'halacha', 'daily_practice', 40, 35, 45, 'beginner', 'Orach Chaim 202:1', 'Orach Chaim 202:20', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.202.1', 'Comprehensive guide to blessings before and after eating', 'מדריך מקיף לברכות לפני ואחרי האכילה', 'How do food blessings transform eating from a physical act into a spiritual experience?', 'כיצד ברכות על המזון הופכות את האכילה ממעשה גשמי לחוויה רוחנית?', ARRAY['Mishnah Berurah', 'Aruch HaShulchan', 'Kaf HaChaim'], ARRAY['Food blessing mastery', 'Mindful eating practices'], true),
('Evening Prayer Structure', 'מבנה תפילת ערבית', 'halacha', 'daily_practice', 45, 40, 50, 'intermediate', 'Orach Chaim 235:1', 'Orach Chaim 235:5', 'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.235.1', 'Structure and laws of the evening prayer service', 'מבנה והלכות תפילת ערבית', 'What themes in the evening prayers help you reflect on and conclude your day?', 'אילו נושאים בתפילת ערבית עוזרים לך להרהר ולסיים את יומך?', ARRAY['Mishnah Berurah', 'Aruch HaShulchan', 'Kaf HaChaim'], ARRAY['Evening prayer structure', 'Daily spiritual closure'], true);