-- Insert sample sources into the sources table
INSERT INTO public.sources (
  title,
  title_he,
  category,
  subcategory,
  start_ref,
  end_ref,
  text_excerpt,
  text_excerpt_he,
  reflection_prompt,
  reflection_prompt_he,
  estimated_time,
  sefaria_link,
  published
) VALUES 
-- Halacha sources
(
  'Shulchan Aruch Orach Chaim 1:1 – Morning Awakening',
  'שולחן ערוך אורח חיים א:א – התעוררות הבוקר',
  'halacha',
  'daily_practice',
  'Shulchan Aruch OC 1:1',
  '1:1',
  'One should strengthen himself like a lion to get up in the morning to serve his Creator, so that he awakens the dawn.',
  'יתגבר כארי לעמוד בבוקר לעבודת בוראו, שיהא הוא מעורר השחר.',
  'How can you bring this morning determination into your life?',
  'איך תביא התעוררות זו לשגרת יומך?',
  10,
  'https://www.sefaria.org/Shulchan_Arukh%2C_Orach_Chayim.1.1',
  true
),
(
  'Shulchan Aruch Yoreh Deah 249:1 – Giving Charity',
  'שולחן ערוך יורה דעה רמט:א – מצוות צדקה',
  'halacha',
  'charity',
  'Shulchan Aruch YD 249:1',
  '249:1',
  'Every person is obligated to give tzedakah according to his ability, and the poor of his family come first.',
  'חייב כל אדם ליתן צדקה כפי יכולתו ועניי עירו קודמים.',
  'Who around you could benefit most from your support this week?',
  'למי בסביבתך אתה יכול לעזור יותר השבוע?',
  15,
  'https://www.sefaria.org/Shulchan_Arukh%2C_Yoreh_Deah.249.1',
  true
),
-- Rambam sources
(
  'Mishneh Torah Hilchot Teshuva 7:3 – The Nature of Return',
  'משנה תורה הלכות תשובה ז:ג – טבע התשובה',
  'rambam',
  'repentance',
  'Hilchot Teshuva 7:3',
  '7:3',
  'How great is repentance! Yesterday he was separate from God... today he cleaves to the Divine Presence.',
  'גדולה תשובה שאמש היה זה מובדל מה''... והיום הוא דבוק בשכינה.',
  'Recall a moment of transformation in your life. What did it teach you?',
  'הרהר בשינוי שעברת. מה למדת ממנו?',
  20,
  'https://www.sefaria.org/Mishneh_Torah%2C_Repentance.7.3',
  true
),
(
  'Mishneh Torah Hilchot De''ot 2:2 – The Middle Path',
  'משנה תורה הלכות דעות ב:ב – דרך האמצע',
  'rambam',
  'character',
  'Hilchot De''ot 2:2',
  '2:2',
  'The straight path is the midpoint disposition of each and every trait that man possesses.',
  'הדרך הישרה היא שהיא דרך האמצע של כל דעה ודעה מכל הדעות שיש לאדם.',
  'Which trait in your life could benefit from finding a better balance?',
  'באיזו מידה בחייך דרוש איזון נכון יותר?',
  15,
  'https://www.sefaria.org/Mishneh_Torah%2C_Human_Dispositions.2.2',
  true
),
-- Tanakh sources
(
  'Genesis 28:10-12 – Jacob''s Dream',
  'בראשית כח:י–יב – חלום יעקב',
  'tanakh',
  'torah',
  'Genesis 28:10',
  '28:12',
  'And he dreamed, and behold! a ladder was set up on the earth, and its top reached to heaven...',
  'ויחלום והנה סולם מצב ארצה וראשו מגיע השמימה...',
  'What personal vision lifts you toward something higher?',
  'איזו חזון אישי מקרב אותך למעלה?',
  12,
  'https://www.sefaria.org/Genesis.28.10-28.12',
  true
),
(
  'Isaiah 58:6-7 – True Fasting',
  'ישעיהו נח:ו–ז – צום אמיתי',
  'tanakh',
  'prophets',
  'Isaiah 58:6',
  '58:7',
  'Is not this the fast I choose? To loosen the chains of wickedness... to share your bread with the hungry.',
  'הלוא זה צום אבחרהו פתח חרצבות רשע... פרוש לרעב לחמך.',
  'How do acts of kindness express your spiritual ideals?',
  'כיצד מעשי חסד מבטאים את האידיאלים הרוחניים שלך?',
  18,
  'https://www.sefaria.org/Isaiah.58.6-58.7',
  true
),
-- Talmud sources
(
  'Talmud Bavli Berakhot 17a – Prayer of the Heart',
  'תלמוד בבלי ברכות יז. – תפילת הלב',
  'talmud',
  'berakhot',
  'Berakhot 17a',
  '17a',
  'Great is peace, for all blessings are contained within it.',
  'גדול השלום שכל הברכות ניתנות בתוכו.',
  'How can you be a peacemaker in your daily interactions?',
  'איך תוכל להיות משכן שלום ביחסים יומיומיים?',
  25,
  'https://www.sefaria.org/Berakhot.17a',
  true
),
-- Spiritual/mussar sources
(
  'Mesillat Yesharim Chapter 1 – The Purpose of Life',
  'מסילת ישרים פרק א – תכלית האדם',
  'spiritual',
  'mussar',
  'Mesillat Yesharim 1',
  '1',
  'The foundation of piety and the root of perfect service is for a person to clarify and realize what his obligation is in his world.',
  'יסוד החסידות ושורש העבודה התמימה הוא שיתברר ויתאמת אצל האדם מה חובתו בעולמו.',
  'What do you see as your unique purpose in this world?',
  'מה אתה רואה כייעוד הייחודי שלך בעולם הזה?',
  20,
  'https://www.sefaria.org/Mesillat_Yesharim.1',
  true
),
(
  'Pirkei Avot 1:14 – Hillel''s Teaching',
  'פרקי אבות א:יד – דברי הלל',
  'spiritual',
  'ethics',
  'Pirkei Avot 1:14',
  '1:14',
  'If I am not for myself, who will be for me? And if I am only for myself, what am I? And if not now, when?',
  'אם אין אני לי מי לי? וכשאני לעצמי מה אני? ואם לא עכשיו אימתי?',
  'How do you balance self-care with caring for others?',
  'איך אתה מאזן בין דאגה לעצמך לדאגה לאחרים?',
  10,
  'https://www.sefaria.org/Pirkei_Avot.1.14',
  true
);