-- Final completion: Adding SPIRITUAL sources (15 total) + SURPRISE sources (15 total) to reach 150+ total

-- SPIRITUAL SOURCES - Mussar (7 sources)
INSERT INTO sources (title, title_he, category, subcategory, estimated_time, min_time, max_time, difficulty_level, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, commentaries, learning_objectives, published) VALUES
('Soul Traits', 'מידות הנפש', 'spiritual', 'mussar', 25, 20, 30, 'intermediate', 'Duties of Hearts 1:1', 'Duties of Hearts 1:2', 'https://www.sefaria.org/Duties_of_the_Heart%2C_Introduction.1', 'The fundamental character traits that require cultivation', 'תכונות האופי הבסיסיות הדורשות טיפוח', 'Which character trait do you most need to work on, and what specific steps can you take?', 'איזו תכונת אופי אתה הכי צריך לעבוד עליה, ואילו צעדים ספציפיים אתה יכול לנקוט?', ARRAY['Gates of Repentance', 'Path of the Just', 'Duties of Hearts'], ARRAY['Character development', 'Soul refinement'], true),
('Fear and Love', 'יראה ואהבה', 'spiritual', 'mussar', 30, 25, 35, 'advanced', 'Duties of Hearts 10:1', 'Duties of Hearts 10:3', 'https://www.sefaria.org/Duties_of_the_Heart%2C_The_Gate_of_the_Love_of_God.1', 'Balancing fear and love in spiritual service', 'איזון יראה ואהבה בעבודה רוחנית', 'How do you experience the balance between reverence and love in your spiritual life?', 'כיצד אתה חווה את האיזון בין יראה ואהבה בחיים הרוחניים שלך?', ARRAY['Gates of Repentance', 'Path of the Just', 'Duties of Hearts'], ARRAY['Spiritual emotions', 'Divine relationship'], true),
('Humility Practice', 'תרגול ענווה', 'spiritual', 'mussar', 20, 15, 25, 'intermediate', 'Path of the Just Ch. 22', 'Path of the Just Ch. 22', 'https://www.sefaria.org/Mesillat_Yesharim%2C_Chapter_22', 'The nature and cultivation of true humility', 'טבע וטיפוח של ענווה אמיתית', 'How do you distinguish between genuine humility and low self-esteem in your own behavior?', 'כיצד אתה מבחין בין ענווה אמיתית להערכה עצמית נמוכה בהתנהגות שלך?', ARRAY['Gates of Repentance', 'Path of the Just', 'Duties of Hearts'], ARRAY['Humility cultivation', 'Self-awareness'], true),
('Daily Accounting', 'חשבון נפש יומי', 'spiritual', 'mussar', 18, 12, 25, 'beginner', 'Path of the Just Ch. 3', 'Path of the Just Ch. 3', 'https://www.sefaria.org/Mesillat_Yesharim%2C_Chapter_3', 'The practice of daily spiritual accounting', 'תרגול חשבון הנפש היומי', 'What questions do you ask yourself at the end of each day to evaluate your spiritual progress?', 'אילו שאלות אתה שואל את עצמך בסוף כל יום כדי להעריך את ההתקדמות הרוחנית שלך?', ARRAY['Gates of Repentance', 'Path of the Just', 'Duties of Hearts'], ARRAY['Self-evaluation', 'Daily reflection'], true),
('Anger Control', 'שליטה בכעס', 'spiritual', 'mussar', 28, 22, 35, 'intermediate', 'Orchot Tzadikim - Anger', 'Orchot Tzadikim - Anger', 'https://www.sefaria.org/Orchot_Tzadikim%2C_The_Gate_of_Anger', 'Methods for controlling and channeling anger constructively', 'שיטות לשליטה ולהפניית כעס בצורה בונה', 'What triggers your anger most, and what techniques help you respond more thoughtfully?', 'מה הכי מעורר את הכעס שלך, ואילו טכניקות עוזרות לך להגיב בצורה מחושבת יותר?', ARRAY['Gates of Repentance', 'Path of the Just', 'Duties of Hearts'], ARRAY['Anger management', 'Emotional control'], true),
('Gratitude Cultivation', 'טיפוח הכרת הטוב', 'spiritual', 'mussar', 22, 18, 28, 'beginner', 'Duties of Hearts 2:4', 'Duties of Hearts 2:5', 'https://www.sefaria.org/Duties_of_the_Heart%2C_The_Gate_of_Examination.4', 'Developing genuine gratitude and recognition of blessings', 'פיתוח הכרת טוב ומודעות לברכות אמיתיות', 'What are three things you took for granted today that you can now appreciate more deeply?', 'מה שלושה דברים שלקחת כמובן מאליו היום שאתה יכול להעריך עכשיו יותר עמוק?', ARRAY['Gates of Repentance', 'Path of the Just', 'Duties of Hearts'], ARRAY['Gratitude practice', 'Blessing recognition'], true),
('Joy in Service', 'שמחה בעבודה', 'spiritual', 'mussar', 32, 28, 38, 'intermediate', 'Duties of Hearts 6:6', 'Duties of Hearts 6:7', 'https://www.sefaria.org/Duties_of_the_Heart%2C_The_Gate_of_Submission.6', 'Finding genuine joy in spiritual service and mitzvot', 'מציאת שמחה אמיתית בעבודה רוחנית ובמצוות', 'How can you cultivate more joy and enthusiasm in your religious observances?', 'כיצד תוכל לטפח יותר שמחה והתלהבות בקיום הדתי שלך?', ARRAY['Gates of Repentance', 'Path of the Just', 'Duties of Hearts'], ARRAY['Joyful service', 'Enthusiastic observance'], true);

-- SPIRITUAL - Chassidut (4 sources)
INSERT INTO sources (title, title_he, category, subcategory, estimated_time, min_time, max_time, difficulty_level, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, commentaries, learning_objectives, published) VALUES
('Divine Spark', 'ניצוץ אלוקי', 'spiritual', 'chassidut', 20, 15, 25, 'intermediate', 'Tanya Ch. 2', 'Tanya Ch. 2', 'https://www.sefaria.org/Tanya%2C_Likutei_Amarim%2C_Chapter_2', 'Every soul contains a divine spark', 'כל נשמה מכילה ניצוץ אלוקי', 'How do you recognize and nurture the divine spark within yourself and others?', 'כיצד אתה מזהה ומטפח את הניצוץ האלוקי בתוך עצמך ובאחרים?', ARRAY['Chassidic masters', 'Tanya commentaries', 'Zohar'], ARRAY['Soul awareness', 'Divine presence'], true),
('Hitbodedut Practice', 'תרגול התבודדות', 'spiritual', 'chassidut', 25, 20, 30, 'intermediate', 'Likutei Moharan 52', 'Likutei Moharan 52', 'https://www.sefaria.org/Likutei_Moharan%2C_Part_I.52', 'The practice of secluded meditation and self-reflection', 'תרגול של מדיטציה מבודדת והרהור עצמי', 'When and how do you create space for private conversation with the Divine?', 'מתי וכיצד אתה יוצר מקום לשיחה פרטית עם האלוקים?', ARRAY['Chassidic masters', 'Tanya commentaries', 'Zohar'], ARRAY['Meditation practice', 'Divine dialogue'], true),
('Joy and Sadness', 'שמחה ועצבות', 'spiritual', 'chassidut', 30, 25, 35, 'intermediate', 'Tanya Ch. 26', 'Tanya Ch. 27', 'https://www.sefaria.org/Tanya%2C_Likutei_Amarim%2C_Chapter_26', 'Balancing spiritual joy with recognition of shortcomings', 'איזון שמחה רוחנית עם הכרה בחסרונות', 'How do you maintain spiritual joy while honestly acknowledging your areas for improvement?', 'כיצד אתה שומר על שמחה רוחנית תוך הכרה כנה באזורים לשיפור שלך?', ARRAY['Chassidic masters', 'Tanya commentaries', 'Zohar'], ARRAY['Emotional balance', 'Honest optimism'], true),
('Simple Faith', 'אמונה פשוטה', 'spiritual', 'chassidut', 15, 10, 20, 'beginner', 'Likutei Moharan 7', 'Likutei Moharan 7', 'https://www.sefaria.org/Likutei_Moharan%2C_Part_I.7', 'The power and purity of simple, uncomplicated faith', 'הכוח והטוהר של אמונה פשוטה ולא מסובכת', 'When has simple faith carried you through times when intellectual understanding failed?', 'מתי אמונה פשוטה נשאה אותך בזמנים שההבנה השכלית נכשלה?', ARRAY['Chassidic masters', 'Tanya commentaries', 'Zohar'], ARRAY['Simple faith', 'Trust cultivation'], true);

-- SPIRITUAL - Jewish Philosophy (4 sources)
INSERT INTO sources (title, title_he, category, subcategory, estimated_time, min_time, max_time, difficulty_level, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, commentaries, learning_objectives, published) VALUES
('Free Will Debate', 'ויכוח הבחירה החופשית', 'spiritual', 'jewish_philosophy', 40, 35, 45, 'advanced', 'Saadia Gaon - Beliefs', 'Saadia Gaon - Beliefs', 'https://www.sefaria.org/Emunot_veDeot', 'Classical Jewish perspectives on free will and determinism', 'נקודות מבט יהודיות קלאסיות על בחירה חופשית ודטרמיניזם', 'How do you balance taking responsibility for your choices with trusting in Divine providence?', 'כיצד אתה מאזן בין נטילת אחריות על הבחירות שלך לביטחון בהשגחה אלוקית?', ARRAY['Medieval philosophers', 'Rishonim', 'Acharonim'], ARRAY['Free will understanding', 'Responsibility ethics'], true),
('Exile Purpose', 'מטרת הגלות', 'spiritual', 'jewish_philosophy', 30, 25, 35, 'intermediate', 'Maharal - Netzach Yisrael', 'Maharal - Netzach Yisrael', 'https://www.sefaria.org/Netzach_Yisrael', 'The spiritual purpose and meaning of exile', 'המטרה והמשמעות הרוחנית של הגלות', 'How do you find meaning and purpose in times of displacement or difficulty in your own life?', 'כיצד אתה מוצא משמעות ומטרה בזמנים של עקירה או קושי בחיים שלך?', ARRAY['Medieval philosophers', 'Rishonim', 'Acharonim'], ARRAY['Exile meaning', 'Suffering purpose'], true),
('Soul Immortality', 'נצחיות הנשמה', 'spiritual', 'jewish_philosophy', 45, 40, 50, 'advanced', 'Ramban on Ecclesiastes', 'Ramban on Ecclesiastes', 'https://www.sefaria.org/Ramban_on_Ecclesiastes', 'Jewish perspectives on the soul continued existence', 'נקודות מבט יהודיות על המשך קיום הנשמה', 'How does your belief about what happens after death affect the way you live now?', 'כיצד האמונה שלך על מה שקורה אחרי המוות משפיעה על הדרך שבה אתה חי עכשיו?', ARRAY['Medieval philosophers', 'Rishonim', 'Acharonim'], ARRAY['Afterlife beliefs', 'Life impact'], true),
('Reason vs Revelation', 'שכל נגד גילוי', 'spiritual', 'jewish_philosophy', 50, 45, 55, 'advanced', 'Judah Halevi - Kuzari', 'Judah Halevi - Kuzari', 'https://www.sefaria.org/Kuzari', 'The relationship between rational inquiry and revealed truth', 'היחס בין חקירה רציונלית לאמת נגלית', 'How do you integrate rational thinking with faith-based beliefs in your own spiritual journey?', 'כיצד אתה משלב חשיבה רציונלית עם אמונות מבוססות אמונה במסע הרוחני שלך?', ARRAY['Medieval philosophers', 'Rishonim', 'Acharonim'], ARRAY['Reason-faith integration', 'Truth sources'], true);

-- SURPRISE ME SOURCES (15 total)
INSERT INTO sources (title, title_he, category, subcategory, estimated_time, min_time, max_time, difficulty_level, start_ref, end_ref, sefaria_link, text_excerpt, text_excerpt_he, reflection_prompt, reflection_prompt_he, commentaries, learning_objectives, published) VALUES
('Butterfly Effect', 'אפקט הפרפר', 'surprise', 'mixed', 12, 8, 18, 'beginner', 'Berakhot 58a', 'Berakhot 58a', 'https://www.sefaria.org/Berakhot.58a', 'Small actions can have massive consequences', 'מעשים קטנים יכולים להביא להשלכות עצומות', 'What small act of kindness today might create ripples you never imagined?', 'איזה מעשה חסד קטן היום עלול ליצור גלים שמעולם לא דמיינת?', ARRAY['Rashi', 'Tosafot', 'Maharsha'], ARRAY['Action awareness', 'Ripple effects'], true),
('Dream Logic', 'היגיון החלום', 'surprise', 'mixed', 18, 12, 25, 'intermediate', 'Berakhot 57b', 'Berakhot 57b', 'https://www.sefaria.org/Berakhot.57b', 'Talmudic interpretations of dreams and their meanings', 'פרשנויות תלמודיות לחלומות ומשמעויותיהם', 'What recurring dream or thought pattern might be trying to teach you something?', 'איזה חלום או דפוס מחשבה חוזר עלול לנסות ללמד אותך משהו?', ARRAY['Rashi', 'Tosafot', 'Maharsha'], ARRAY['Subconscious wisdom', 'Pattern recognition'], true),
('Cosmic Perspective', 'פרספקטיבה קוסמית', 'surprise', 'mixed', 25, 20, 30, 'intermediate', 'Ecclesiastes 3:15', 'Ecclesiastes 3:15', 'https://www.sefaria.org/Ecclesiastes.3.15', 'What has been is what will be, and God seeks what has been pursued', 'מה שהיה הוא שיהיה והאלוקים יבקש את נרדף', 'How does thinking about eternity change your perspective on today worries?', 'כיצד חשיבה על הנצחיות משנה את נקודת המבט שלך על הדאגות של היום?', ARRAY['Rashi', 'Radak', 'Metzudat David'], ARRAY['Time perspective', 'Eternal view'], true),
('Animal Wisdom', 'חוכמת החיות', 'surprise', 'mixed', 20, 15, 25, 'beginner', 'Proverbs 6:6', 'Proverbs 6:8', 'https://www.sefaria.org/Proverbs.6.6', 'Go to the ant, you sluggard; consider its ways and be wise', 'לך אל נמלה עצל ראה דרכיה וחכם', 'What can you learn from observing animals or nature about diligence and preparation?', 'מה תוכל ללמוד מתצפית על חיות או טבע על חריצות והכנה?', ARRAY['Rashi', 'Radak', 'Metzudat David'], ARRAY['Natural wisdom', 'Life lessons from nature'], true),
('Paradox of Strength', 'פרדוקס הכוח', 'surprise', 'mixed', 30, 25, 35, 'intermediate', 'Judges 14:14', 'Judges 14:14', 'https://www.sefaria.org/Judges.14.14', 'Samson riddle: Out of the strong came sweetness', 'חידת שמשון: מהעז יצא מתוק', 'When has something that seemed entirely negative in your life produced unexpected sweetness?', 'מתי משהו שנראה לחלוטין שלילי בחייך הוליד מתיקות בלתי צפויה?', ARRAY['Rashi', 'Radak', 'Metzudat David'], ARRAY['Hidden blessings', 'Strength through adversity'], true),
('Food for Thought', 'מזון למחשבה', 'surprise', 'mixed', 22, 18, 28, 'beginner', 'Berakhot 40a', 'Berakhot 40a', 'https://www.sefaria.org/Berakhot.40a', 'The spiritual dimension of eating and blessing food', 'הממד הרוחני של אכילה וברכת מזון', 'How does saying blessings transform your relationship with food and consumption?', 'כיצד אמירת ברכות משנה את היחס שלך למזון ולצריכה?', ARRAY['Rashi', 'Tosafot', 'Maharsha'], ARRAY['Mindful consumption', 'Gratitude practice'], true),
('Silent Communication', 'תקשורת שקטה', 'surprise', 'mixed', 28, 22, 35, 'intermediate', 'Psalms 19:2', 'Psalms 19:4', 'https://www.sefaria.org/Psalms.19.2', 'The heavens declare God glory without speech or words', 'השמים מספרים כבוד אל בלי דיבור ומלים', 'What do you hear in moments of complete silence, and how does nature speak to you?', 'מה אתה שומע ברגעים של שקט מוחלט, וכיצד הטבע מדבר אליך?', ARRAY['Rashi', 'Radak', 'Metzudat David'], ARRAY['Silent wisdom', 'Natural revelation'], true),
('Time Travel Ethics', 'אתיקה של נסיעה בזמן', 'surprise', 'mixed', 40, 35, 45, 'advanced', 'Sanhedrin 99a', 'Sanhedrin 99a', 'https://www.sefaria.org/Sanhedrin.99a', 'If you could change one thing in your past, should you?', 'אם יכולת לשנות דבר אחד בעבר שלך, האם היית צריך?', 'Looking back at your biggest mistake, how has it contributed to who you are today?', 'כשאתה מסתכל אחורה על הטעות הגדולה ביותר שלך, כיצד היא תרמה למי שאתה היום?', ARRAY['Rashi', 'Tosafot', 'Maharsha'], ARRAY['Regret vs acceptance', 'Growth through mistakes'], true),
('Invisible Influences', 'השפעות בלתי נראות', 'surprise', 'mixed', 32, 28, 38, 'intermediate', 'Kiddushin 40b', 'Kiddushin 40b', 'https://www.sefaria.org/Kiddushin.40b', 'Every person should see the world as half guilty, half innocent', 'לעולם יראה אדם את עצמו כאילו חצי זכאי וחצי חייב', 'How might your next small action tip the balance of the entire world?', 'כיצד המעשה הקטן הבא שלך עלול להטות את מאזן העולם כולו?', ARRAY['Rashi', 'Tosafot', 'Maharsha'], ARRAY['Individual impact', 'Cosmic responsibility'], true),
('Mirror Meditation', 'מדיטציית מראה', 'surprise', 'mixed', 24, 18, 30, 'intermediate', 'Tanhuma Vayera 8', 'Tanhuma Vayera 8', 'https://www.sefaria.org/Midrash_Tanhuma%2C_Vayera.8', 'When you look at others, you see yourself reflected back', 'כשאתה מסתכל על אחרים, אתה רואה את עצמך מוחזר', 'What do the people who annoy you most reveal about aspects of yourself you need to work on?', 'מה האנשים שהכי מעצבנים אותך מגלים על היבטים של עצמך שאתה צריך לעבוד עליהם?', ARRAY['Midrash commentaries', 'Chassidic interpretations'], ARRAY['Self-reflection', 'Projection awareness'], true),
('Quantum Faith', 'אמונה קוונטית', 'surprise', 'mixed', 45, 40, 50, 'advanced', 'Chagigah 14b', 'Chagigah 14b', 'https://www.sefaria.org/Chagigah.14b', 'Rabbi Akiva entered the mystical realm and emerged whole', 'רבי עקיבא נכנס לפרדס ויצא בשלום', 'How do you maintain balance when experiencing the deepest spiritual insights?', 'כיצד אתה שומר על איזון כשאתה חווה את התובנות הרוחניות העמוקות ביותר?', ARRAY['Rashi', 'Tosafot', 'Maharsha'], ARRAY['Mystical balance', 'Spiritual integration'], true),
('Laughter Therapy', 'טיפול בצחוק', 'surprise', 'mixed', 16, 10, 22, 'beginner', 'Berakhot 31a', 'Berakhot 31a', 'https://www.sefaria.org/Berakhot.31a', 'Joy breaks through barriers that seriousness cannot', 'שמחה פורצת מכשולים שרצינות לא יכולה', 'When has humor or lightness helped you through a situation that worry could not solve?', 'מתי הומור או קלילות עזרו לך לעבור מצב שדאגה לא יכלה לפתור?', ARRAY['Rashi', 'Tosafot', 'Maharsha'], ARRAY['Therapeutic joy', 'Lightness power'], true),
('Reverse Psychology', 'פסיכולוגיה הפוכה', 'surprise', 'mixed', 38, 32, 45, 'advanced', 'Sotah 14a', 'Sotah 14a', 'https://www.sefaria.org/Sotah.14a', 'Sometimes the best way to teach is by demonstrating the opposite', 'לפעמים הדרך הטובה ביותר ללמד היא על ידי הדגמת ההפך', 'What have you learned most powerfully from observing what not to do?', 'מה למדת בצורה הכי חזקה מתצפית על מה לא לעשות?', ARRAY['Rashi', 'Tosafot', 'Maharsha'], ARRAY['Negative examples', 'Learning from opposites'], true),
('Elevator Moments', 'רגעי מעלית', 'surprise', 'mixed', 26, 20, 32, 'intermediate', 'Avot 4:18', 'Avot 4:18', 'https://www.sefaria.org/Pirkei_Avot.4.18', 'Better one moment of repentance in this world...', 'טוב שעה אחת בתשובה ומעשים טובים בעולם הזה...', 'If you had only one minute to make a difference in someone life today, what would you do?', 'אם היה לך רק דקה אחת להשפיע על החיים של מישהו היום, מה היית עושה?', ARRAY['Rashi', 'Rambam', 'Ruach Chaim'], ARRAY['Moment awareness', 'Instant impact'], true),
('Numerical Mysteries', 'תעלומות מספריות', 'surprise', 'mixed', 35, 30, 40, 'advanced', 'Zohar on Numbers', 'Zohar on Numbers', 'https://www.sefaria.org/Zohar.2.1a', 'The mystical significance of numbers in Jewish tradition', 'המשמעות המיסטית של מספרים במסורת היהודית', 'What patterns or numbers keep appearing in your life, and what might they signify?', 'אילו דפוסים או מספרים ממשיכים להופיע בחייך, ומה הם עלולים לסמל?', ARRAY['Zohar commentaries', 'Kabbalistic sources', 'Chassidic masters'], ARRAY['Pattern recognition', 'Mystical awareness'], true);